"""Exact retained CP9 pixel oracles, shared by embedded and actual-entry tests."""
MATERIAL_PROBE = "()=>{\n   SalahRealSky.compose();\n   const target=document.querySelector('.real-sky-canvas'),rect=target.getBoundingClientRect(),photo=document.querySelector('.mphoto'),t=photo.getScreenCTM(),c=document.createElement('canvas');c.width=325;c.height=530;const x=c.getContext('2d');const sx=325/rect.width,sy=530/rect.height;\n   x.setTransform(t.a*sx,t.b*sy,t.c*sx,t.d*sy,(t.e-rect.left)*sx,(t.f-rect.top)*sy);x.drawImage(_moonCv,-48,-48,96,96);\n   const expected=x.getImageData(0,0,325,530).data,actual=target.getContext('2d').getImageData(0,0,325,530).data;let count=0,max=0,sum=0;\n   for(let i=0;i<expected.length;i+=4)if(expected[i+3]===255){count++;for(let k=0;k<3;k++){const d=Math.abs(expected[i+k]-actual[i+k]);max=Math.max(max,d);sum+=d;}}\n   return {opaquePixels:count,maxCodeDifference:max,meanAbsoluteCodeDifference:sum/(count*3),nativeBacking:[_moonCv.width,_moonCv.height],composition:realSkyState().last.composition,criterion:'All fully opaque native lunar material samples at clear-cloud transmission must survive shared inverse/forward encoding to <=1 code value.'};\n  }"
COMPOSITION_PROBE = "()=>{\n   const times=[];for(let n=0;n<6;n++){const t=performance.now();SalahRealSky.compose();times.push(performance.now()-t);}\n   const target=document.querySelector('.real-sky-canvas'),actual=target.getContext('2d').getImageData(0,0,325,530).data,r=realSkyFrame().raster,E=r.effectiveExposure,C=__fullCapture.capture(),disc=document.querySelector('.moon-mask-disc'),matrix=disc.getScreenCTM();\n   const mask=disc.classList.contains('mask-on')&&+getComputedStyle(disc).opacity!==0?__mask(325,530,target.getBoundingClientRect(),matrix,+disc.getAttribute('r')):null;\n   const inv=Array.from({length:256},(_,i)=>{const q=i/255,s=q<=.04045?q/12.92:((q+.055)/1.055)**2.4;return -Math.log1p(-Math.min(1-1/131072,s))/E;});\n   const code=L=>{const v=-Math.expm1(-E*Math.max(0,L));return Math.round(255*(v<=.0031308?12.92*v:1.055*v**(1/2.4)-.055));};\n   let max=0,changed=0,doubleT=0,doubleColour=0,wrongOrder=0,outsideCloud=0,cutDirectPixels=0,caSum=0;\n   for(let p=0;p<325*530;p++){\n    const a=C.cloudRGBA[p*4+3]/255,T=1-a,m=C.moonRGBA[p*4+3]/255,k=mask?mask[p]:1;caSum+=a;if(p>=325*183&&a)outsideCloud++;\n    if(k<1)cutDirectPixels++;\n    for(let c=0;c<3;c++){\n     const i=p*3+c,j=p*4+c,sky=(r.skyBackgroundLinear??r.backgroundLinear)[i],direct=r.stellarLinear[i]+(r.diffusePhysicalLinear?.[i]??0),base=sky+direct*k;\n     const moon=inv[C.moonRGBA[j]],cloud=inv[C.cloudRGBA[j]],withMoon=base*(1-m)+moon*m;\n     const join=(b,t,c,a)=>-Math.log1p(-Math.min(1-1/131072,(-Math.expm1(-E*b))*t+(-Math.expm1(-E*c))*a))/E;const expected=code(join(withMoon,T,cloud,a)),d=Math.abs(expected-actual[j]);max=Math.max(max,d);if(d)changed++;\n     if(code(join(withMoon,T*T,cloud,a))!==expected)doubleT++;\n     if(code(join(withMoon,T,cloud,a*a))!==expected)doubleColour++;\n     if(code(join(base,T,cloud,a)*(1-m)+moon*m)!==expected)wrongOrder++;\n    }\n   }\n   return {timesMs:times,maxCodeDifference:max,differentChannels:changed,cloudAlphaMean:caSum/(325*530),cloudOutsideDeclaredSupport:outsideCloud,calendarCutoutPixels:cutDirectPixels,mutations:{doubleTransmission:doubleT,doubleColourAlpha:doubleColour,moonAfterCloud:wrongOrder},composition:realSkyState().last.composition,exposure:E,skyInputsUnchanged:r.diffuseState,criterion:'All 325Ã—530 encoded pixels exactly equal the full-frame reference equation; all three deliberately wrong equations must disagree.'};\n  }"

def install_composition_probe(page, root):
    helpers="\n".join((root/"real-sky"/s).read_text(encoding="utf-8").replace("export ", "") for s in ["native-cloud-transfer.mjs", "native-composition.mjs", "native-contract.mjs"])
    import re
    helpers=re.sub(r'^import .*?;\s*$', '', helpers, flags=re.M)
    page.evaluate("(()=>{"+helpers+';window.__fullCapture=new NativeForegroundCapture(document.querySelector(".real-sky-canvas"));window.__mask=nativeDiscMask;})()')
