import test from 'node:test';import assert from 'node:assert/strict';
import {NativeAssetLoader} from '../../real-sky/native-assets.mjs';
import {readFileSync} from 'node:fs';
const tick=async()=>{for(let i=0;i<8;i++)await Promise.resolve();};
function harness(){const loads=[],started=[],reset=[];const loader=new NativeAssetLoader({load:signal=>new Promise((resolve,reject)=>loads.push({signal,resolve,reject})),start:p=>started.push(p),onReset:()=>reset.push(true),timeoutMs:1000});return{loads,started,reset,loader};}
test('page suspension aborts acquisition and fences its late result',async()=>{const h=harness(),p=h.loader.retry();assert.equal(typeof h.loader.suspend,'function');h.loader.suspend();assert.equal(h.loads[0].signal.aborted,true);h.loads[0].resolve({obsolete:true});await p;assert.equal(h.loader.state.status,'suspended');assert.deepEqual(h.started,[]);h.loader.dispose();});
test('return resumes once with a new asset generation, not old work',async()=>{const h=harness();let p=h.loader.retry();h.loads[0].resolve({id:'A'});await p;assert.equal(typeof h.loader.suspend,'function');h.loader.suspend();assert.equal(h.loader.state.status,'suspended');await h.loader.retry();assert.equal(h.loads.length,1);p=h.loader.resume();h.loads[1].resolve({id:'B'});await p;assert.deepEqual(h.started,[{id:'A'},{id:'B'}]);await h.loader.resume();assert.equal(h.loads.length,2);h.loader.dispose();});
test('permanent dispose cannot be reversed by a page return',async()=>{const h=harness();assert.equal(typeof h.loader.resume,'function');h.loader.suspend();h.loader.dispose();await h.loader.resume();assert.equal(h.loader.state.status,'disposed');assert.equal(h.loads.length,0);});
test('host lifecycle wires paired pagehide/pageshow and removes both on explicit dispose',()=>{const s=readFileSync(new URL('../../real-sky/native-assets.mjs',import.meta.url),'utf8');for(const kind of ['pagehide','pageshow']){assert.ok(s.includes(`addEventListener('${kind}'`));assert.ok(s.includes(`removeEventListener('${kind}'`));}});
