import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {NativeSkyEngine} from '../../real-sky/native-engine.mjs';
import {nativeJob} from '../../real-sky/native-contract.mjs';
const root=new URL('../../vendor/real-sky/',import.meta.url),text=p=>fs.readFileSync(new URL(p,root),'utf8');
const pack={catalogueText:text('data/bright-stars.json'),manifestText:text('data/registered-starlight/runtime-manifest.json'),assetTexts:{}};
const input={utcMs:Date.parse('2026-09-07T20:30:00Z'),lat:24.47,lon:39.61,heightM:0,generation:0,sceneIdentity:'native-accepted',weather:null,lp:0,reducedMotion:true,camera:{azDeg:180,altDeg:45,fovYDeg:90,rollDeg:0}};
test('native engine renders only the admitted actual catalogue',async()=>{const e=new NativeSkyEngine(pack),r=await e.render(nativeJob(input,false));assert.equal(r.status,'ready');assert.equal(r.catalogue.records,8921);assert.equal(r.catalogue.emitters,8884);assert.ok(r.raster.drawn>100);const allowed=new Set(JSON.parse(pack.catalogueText).stars.filter(s=>s.emission.enabled).map(s=>s.id));assert.ok(r.sources.every(s=>allowed.has(s.id)&&s.altDeg>=0));assert.ok(r.sources.some(s=>s.hip===113368));assert.equal(r.utcMs,input.utcMs);assert.equal(r.raster.atmosphere.cloudTransmission,1);assert.equal(r.diffuseAsset.mode,'disabled');e.dispose();});
test('same-length corrupt catalogue is rejected before native rendering',()=>assert.throws(()=>new NativeSkyEngine({...pack,catalogueText:pack.catalogueText.replace('HYG4.0','FYG4.0')}),/hash/));
test('wrong manifest is rejected rather than repaired or replaced',()=>assert.throws(()=>new NativeSkyEngine({...pack,manifestText:pack.manifestText+' '}),/hash/));
test('native geometry changes with accepted time and observer',async()=>{const e=new NativeSkyEngine(pack);const a=await e.render(nativeJob(input,false));const b=await e.render(nativeJob({...input,utcMs:input.utcMs+3600000},false));const c=await e.render(nativeJob({...input,lat:-33.8688,lon:151.2093,generation:1},false));const signature=r=>r.sources.map(x=>[x.id,x.x,x.y]);assert.notDeepEqual(signature(a),signature(b));assert.notDeepEqual(signature(a),signature(c));assert.equal(b.utcMs,input.utcMs+3600000);e.dispose();});

const realPack={...pack,assetTexts:{128:text('data/registered-starlight/V-nside128.json')}};
test('native physical mode admits the retained real diffuse source with gas-only worker transport',async()=>{const e=new NativeSkyEngine(realPack),r=await e.render(nativeJob(input,true));assert.equal(r.status,'ready');assert.equal(r.diffuseAsset.mode,'registered');assert.equal(r.raster.diffuseState.sourceSha256,'69f3c6ede4a730e0ca4699f5943fca59d0b203f37c4dfc4b7e6927f063250446');assert.equal(r.raster.diffuseState.nightBudget.mode,'nonstellar-residual-replaces-legacy-floor');const b=r.raster.diffuseState.budget;assert.equal(b.afterGas,b.afterCloud);assert.equal(r.raster.atmosphere.cloudTransmission,1);assert.ok(r.raster.diffuseState.estimatedPixels>0);e.dispose();});
test('missing native map yields fresh explicitly labelled CP6 sky at current native UTC',async()=>{const e=new NativeSkyEngine(pack),r=await e.render(nativeJob({...input,utcMs:input.utcMs+7200000},true));assert.equal(r.status,'ready');assert.equal(r.diffuseAsset.mode,'cp6-fallback');assert.match(r.diffuseAsset.error,/missing/);assert.equal(r.utcMs,input.utcMs+7200000);assert.ok(r.raster.drawn>0);e.dispose();});
test('same-byte-count corrupt map is not displayed or silently replaced',async()=>{const t=realPack.assetTexts[128],e=new NativeSkyEngine({...pack,assetTexts:{128:t.replace('Gaia','Faia')}}),r=await e.render(nativeJob(input,true));assert.notEqual(t,t.replace('Gaia','Faia'));assert.equal(r.status,'ready');assert.equal(r.diffuseAsset.mode,'cp6-fallback');assert.match(r.diffuseAsset.error,/hash/);e.dispose();});
test('rejecting map estimates keeps incomplete exposure explicit in native mode',async()=>{const e=new NativeSkyEngine(realPack),r=await e.render(nativeJob({...input,allowEstimates:false},true));assert.equal(r.diffuseAsset.mode,'registered');assert.ok(r.raster.diffuseState.missingPixels>0);assert.equal(r.raster.diffuseState.exposureComplete,false);e.dispose();});
