"""Reconcile F-owned packets from executed receipts and primary's bounded steering."""
import datetime,hashlib,json,pathlib,shutil,subprocess
OUT=pathlib.Path(__file__).parent;AUDIT=OUT.parents[1]
ROOT=pathlib.Path('C:/Users/theis/.codex/worktrees/hotfix-startup-clouds/salah_widget')
SHA='18ff14860ff41c084b1db5f396bb62aa9c22b1be';TREE='35208181eea714c17f5e77b2644e76434345db60';RUNTIME='f443cf0820e6879dfa7c3ce857d6b2baf554b1fdd2f889433d22e2c532cec260';INDEX='ff728552442f4bcce7f213a089bf01d4cf70ea8d74040bdd3323768ca453beee'
FINAL='docs/real-sky/evidence/startup-cloud-20261007/final-v49/'
digest=lambda b:hashlib.sha256(b).hexdigest()
readj=lambda p:json.loads(p.read_text(encoding='utf-8'))
git=lambda *a:subprocess.check_output(['git','--no-optional-locks',*a],cwd=ROOT,text=True).strip()
assert git('rev-parse',SHA+'^{tree}')==TREE==git('rev-parse','HEAD^{tree}')
assert git('status','--porcelain')=='' and digest((ROOT/'index.html').read_bytes())==INDEX
backup=OUT/'pre-followup';backup.mkdir(exist_ok=True)
for n in [23,24,26,29,33,34,37]:
 for suffix in ['assessment.json','comment.md']:
  f=OUT/f'{n}-{suffix}'
  if not (backup/f.name).exists():shutil.copyfile(f,backup/f.name)
if not (backup/'summary.json').exists():shutil.copyfile(OUT/'summary.json',backup/'summary.json')
A={n:readj(backup/f'{n}-assessment.json') for n in [23,24,26,29,33,34,37]}
light=readj(OUT/'followup-tests/receipt.json');adapt=readj(OUT/'followup-tests/adaptation-receipt.json');replacement=readj(OUT/'followup-tests/replacement-receipt.json')
models=readj(AUDIT/'reviewer-model-settings.json');ms=next(s for s in models['sessions'] if s['session']['agent_path']=='/root/rlgwo_f')
assert all(t['model']=='gpt-6.1-sol' and t['effort']=='max' for t in ms['turnConfigurations'])
release=readj(AUDIT/'release.json');public=readj(AUDIT/'public-browser-summary.json');assert release['status']=='DELIVERED_VERIFIED' and len(public['cases'])==16 and all(x['status']=='PASS' for x in public['cases'])
radio={e:readj(AUDIT/f'primary-native-F2-{e}/results.json') for e in ['chromium','firefox']}
debug=readj(AUDIT/'primary-native-F-moon-debug/results.json')
assert debug['status']=='PASS' and debug['servedIndexSha256']==INDEX and debug['current']['runtime']['visibleSource']=='terrain-preview'
assert all(r['status']=='PASS' and len(r['cases'])==6 and all(c['status']=='PASS' for c in r['cases']) for r in radio.values())
def ref(p,lo=None,hi=None):return {'path':p,'lines':[lo,hi or lo] if lo else None,'url':f'https://github.com/theislampill/salah_widget/blob/{SHA}/{p}'+(f'#L{lo}-L{hi or lo}' if lo else '')}
def patch(n,i,status,observed):
 r=next(r for r in A[n]['requirementMatrix'] if r['id']==i);r['status']=status;r['observed']=observed;return r
def ev(n,i,p,scope):next(r for r in A[n]['requirementMatrix'] if r['id']==i)['evidence'].append({'source':ref(p),'freshness':'historical exact-source reuse inspected in follow-up','scope':scope})
for n,a in A.items():
 a['model'].update(effectiveConfigurationConfirmed=True,confirmationKind=models['confirmationKind'],recordedSessionId=ms['session']['id'],recordSha256=digest((AUDIT/'reviewer-model-settings.json').read_bytes()))
 a['freshExecution']={'productTests':[x for x in light['commands'] if x['issue']==n], 'browsers':[], 'scope':'F ran bounded Node/VM/command controls only after resource authorization. All actual browser launches below were executed serially by primary; F inspected receipts and crops.'}
 for x in adapt['adaptations']:
  if (n==29 and x['name'].startswith('r001d-')) or (n==37 and x['name'].startswith('r0025-')):a['freshExecution']['productTests'].append(x)
 if n in [29,33,34]:a['freshExecution']['replacementControls']=replacement
 a['executedCommands'] += a['freshExecution']['productTests']
 a['ownerDecisions']=[]
 a['publication'].update(deliveredBaseline='DELIVERED_VERIFIED; 16 public browser cases PASS; root/V1 actual sources and 330x534 wrapper checked',publicEvidenceLinksPending=True,hold='Primary reconciliation, publication approval and public links to fresh audit receipts are still required. No reviewer GitHub effects.')
 a['reuseBasis']+=' Follow-up credits final normal1x images/public replacement proof for actual motion and current surface continuity. Owner-adopted physical astronomical scattering is distinct from native calendar-derived light. No complete Moon phase campaign is inferred from the opt-in raw sampler.'

# R0017: concrete documentation defect already fixes the decision; do not rerun a Moon campaign for confidence.
patch(23,'17-02','satisfied','Fresh original contract controls pass (35 cases), including suppressed callbacks, late results and timeout-as-execution negatives; full required accounting remains honest. Actual healthy browser execution is separately unverified.')
patch(23,'17-05','satisfied','Fresh original contract controls exercise original valid/malformed/absent values and unrelated sentinel bytes across pass/fail/throw/timeout, denied default-storage getters and both resolve consumers. These are source/contained-transport controls, not a new native30/30 result.')
patch(23,'17-06','satisfied','Fresh transport controls pass17; actual original wrapper intercepts fetch/Response/json before parsing and binds source/attempt/document/hash. Its DOMParser is deliberately a boundary stop; actual loaded widget is not claimed by this transport check.')
A[23]['gaps']=['README has no required safe-origin/isolation and PASS/FAIL/INCOMPLETE instructions. This is a direct mandatory documentation gap.', 'An exact-current actual smoke healthy30/30 execution and reject/hang/bootstrap-error consumer matrix are not retained in inspected evidence. Earlier healthy receipts retain earlier runtime identities; source-level35+17 controls do not replace the required browser consumer matrix.']
A[23]['proposedNextRlgwoIncrement']={'owner':'README.md plus tests/smoke.html and tests/widget-fixture.html; current native runtime remains the actual consumer','preserve':'Keep all30 named required cases, original strict assertions, optional storage seam, private settings, exact source/attempt/document binding and truthful timeout outcomes.','steps':['Add the original required safe-origin/storage-isolation and status instructions under ordinary change authorization.','After that bounded documentation increment, qualify only the exact-current original healthy/reject/hang/bootstrap-error browser matrix, including sentinels, actual response consumption, moon orientation and matchMedia controls. Retain red outcomes; do not weaken deadlines or count a timeout as execution.'],'acceptance':'README explains the safe isolated origin and outcomes; healthy fixture reaches every required case; all three faults terminate non-PASS; sentinels and actual consumed source/attempt identity remain proven.','nonGoals':'No appearance/motion certification from the frozen font-suppressed fixture; no new Moon or weather programme, fake30/30 or unrelated renderer repair.'}
A[23]['missingChecksRequested']=[{'name':'future original consumer matrix after README repair','command':'Use the existing tests/smoke.html and widget-fixture.html four separate isolated-origin modes healthy/reject/hang/bootstrap-error; preserve every original assertion.','reason':'Already LEAVE OPEN for a direct documentation gap; no new expensive run is requested during this audit just to change confidence.'}]

# R0018: direct original policy gap, without inventing an owner-decision conflict.
patch(24,'18-01','satisfied','Current CSS retains row geometry/fonts/strings and325x530 card; public16 cases verify root/V1 card/layout and approved330x534 production wrapper. The next-row emphasis change is approved and local.')
patch(24,'18-02','unmet','Default glass still applies .p.past opacity .42 to names/times. H6 requests subdued elapsed rows and readable future rows, without forcing high-contrast mode; it does not waive full information opacity. Both requirements can coexist through local style treatment.')
patch(24,'18-03','unmet','Fresh authored intended-color white-stress calculation gives default normal glass1.1554847908734267:1; opt-in contrast satisfies >=4.5 and opacity1. The calculator itself asserts default glass <4.5. This is a bounded intended-color stress result, not a measurement of every photograph or the untested frozen-noon12 rectangles.')
A[24]['gaps']=['The original default full-information-opacity requirement remains unmet: .p.past attenuates text at .42. No new owner decision is inherently needed.', 'Default glass lacks the original intended-color >=4.5 guarantee under the specified bright stress; the existing PASS applies to the optional contrast surface. Original frozen-noon12-rectangle/native text-free proof remains unverified.']
A[24]['dependencies']=['H6/R000A row classification: elapsed subdued, future readable, NEXT/CURRENT distinct; these requirements are compatible with original full information opacity and local readability.','Approved atmospheric scene/card/production wrapper preserved; no all-photo contrast requirement is invented.']
A[24]['proposedNextRlgwoIncrement']={'owner':'src/native/index.html timetable styles and authored readability tests; regenerate root through the existing builder','preserve':'Preserve the approved scene, glass choice, elapsed/future classification, opaque NEXT emphasis, CURRENT outline, six rows/fonts and card/layout.','steps':['Apply the smallest local default-glass backing/foreground treatment that preserves subdued elapsed hierarchy while keeping name/time information at full opacity. Do not force selection of the optional contrast mode.','Run the original pinned2026-09-07 noon intended-color/text-free12-rectangle procedure and specified bright stress; retain past/NEXT mutants, matched crops and representative source-required scene/geometry controls.'],'acceptance':'Every original required row state retains full information opacity and meets the specified intended-color >=4.5 evaluation; hierarchy, approved atmosphere and geometry remain readable without a mode switch.','nonGoals':'No global repaint, mandatory high-contrast preference, contrast claim for arbitrary photographs or new owner decision unless a genuine implementation conflict arises.'}
A[24]['missingChecksRequested']=[{'name':'bounded default-style proof after repair','command':'Existing tests/r0018-appearance-browser-fixture.cjs current source, original frozen noon and text-hidden12 rectangles plus declared bright stress and past/NEXT mutants.','reason':'The current default policy is already unmet; proof follows the authorized local style repair, not a new broad campaign.'}]

# R001A: exact actual native green and both meaningful red mutations.
A[26]['verdict']='CLOSE — SATISFIED WITH DEMONSTRATED IMPROVEMENTS';A[26]['gaps']=[];A[26]['missingChecksRequested']=[]
A[26]['scopeOfDone']='The existing two-button Embed group now has one selected/tabbable radio, native arrow wrap/focus, native Tab/ShiftTab/Enter/Space and synchronized generated output. Primary executed the final V2 native matrix in Chromium148 and Firefox150 at375x800 and1100x900; F inspected all four focus crops.'
for r in A[26]['requirementMatrix']:r['status']='satisfied'
patch(26,'1A-03','satisfied','Both native engines execute all four arrows/wrap with focus+state+output agreement and revision+1; V2 explicitly checks scroll offsets unchanged. Disabled controls and unrelated native event target are excluded.')
patch(26,'1A-04','satisfied','V2 presses actual Enter and complete Space on both local and portable, each revision+1; actual Tab exits the group and Shift+Tab re-enters selected radio without a reload or trap.')
patch(26,'1A-05','satisfied','Both native engines verify click and programmatic mode changes, code/preview local flag, allow=geolocation and preserved325x530 emitted snippet. Native Tab/ShiftTab is repeated immediately after click. Blank preview is explicitly an output-contract boundary; it does not certify sky rendering. Public16 actual widget cases separately support card/wrapper rendering.')
patch(26,'1A-06','satisfied','Both original mutants reject at first native Right: arrows -> embedMode expected local; tabindex -> mode-portable tabIndex must follow selected state. All four mutant documents per engine reach the intended assertions without page errors; bootstrap failures are not counted. Source VM8/8 and both mutants also pass fresh.')
patch(26,'1A-07','satisfied','F viewed four native375/desktop focus crops. Portable label and unselected local label are intact; actual yellow2px keyboard outline is visible. No screen-reader speech matrix is claimed or required.')
patch(26,'1A-08','satisfied','Final V2 records bind exact builder66f1cd86cfb3d1e53b75c8840057564ccfa514a46cf1f13b6863673b0d83279e and indexff7285; both engines6/6. Full record/crop publication links await primary evidence-only custody; closure proposal is not posted or approved here.')
A[26]['freshExecution']['browsers']=[{'executedBy':'primary','freshExecution':True,'receipt':str(AUDIT/f'primary-native-F2-{e}/results.json'),'receiptSha256':digest((AUDIT/f'primary-native-F2-{e}/results.json').read_bytes()),'browser':r['browser'],'cases':[{k:c.get(k) for k in ['name','status','negativeControlDetected','discriminator']} for c in r['cases']],'driverSha256':r['driverSha256'],'fixtureSha256':r['fixtureSha256']} for e,r in radio.items()]
A[26]['proposedNextRlgwoIncrement']={'owner':'Primary reconciliation/publication only','steps':['Publish immutable evidence-only links for the final V2 native receipts/crops and the exact prepared fixture; reconcile this closure comment individually.'],'acceptance':'Every original obligation is satisfied at the delivered target; no runtime repair remains in this issue.','nonGoals':'No new accessibility framework, screen-reader programme, live owner storage mutation or inference that blank preview renders the widget.'}

# R001D: current raw surface + actual consumer controls, scoped away from optical/art claims.
A[29]['verdict']='CLOSE — SATISFIED WITH DEMONSTRATED IMPROVEMENTS';A[29]['gaps']=[];A[29]['missingChecksRequested']=[]
for r in A[29]['requirementMatrix']:r['status']='satisfied'
patch(29,'1D-02','satisfied','Fresh whole-render diagnostics21/21 and lifecycle11/11 reach real atmosphere/paint and direct producers; reordered/omitted updates, pre-first/empty/error/failed stages, date/location collisions and immutable snapshots discriminate. Both not-false and recompute-after-consume mutants are detected.')
patch(29,'1D-03','satisfied','All original cadence/cache assertions retained: .001 reuses raster/buffer and .006 repaints using storage. Consumed warnings are bounded; atmosphere stays pure. The diagnostic source is opt-in/read-only and does not change default material; current V5 appearance is qualified separately by retained source-bound controls.')
patch(29,'1D-04','satisfied','Disclosed current-surface adapter supplies the same original synthetic disc to SalahMoonRuntime.surface() instead of only legacy _moonCv; all21 assertions pass without changing expected coordinates. Actual public raw300x300/R144 readout also agrees with independent current backing pixels. Missing-context/throwing-read are unavailable and5 bounds are OOB, all restored.')
patch(29,'1D-05','satisfied','Actual public current preview at(222/293/294/295/299,150) reads14/255,15/108,0/0,0/0,0/0 respectively. Raw edge AA is preserved as observed; these labels are not composited-sky proof. The original synthetic dark/bright positives independently prevent hardcoded labels.')
patch(29,'1D-06','satisfied','All original21 cases retained; first6 original semantic mutants detected with healthy controls, including R58 and removed bounds. Seventh legacy synthetic-star refresh mutation is explicitly excluded from these6; actual host/catalogue/currentness/opacity replacements are separately4+3+27 controls, not a seventh mutant relabel.')
patch(29,'1D-07','satisfied','Primary native opt-in probe PASS at exact publicff7285/f443cf: initial unavailable at345.2ms, first current V5 TERRAIN PREVIEW, strict completed consumedFresh, actual overlay/raw pixels, nonthrowing error/OOB controls and no page errors. F viewed card/readout crops. This does not claim refined terrain; common public release and exact final-v49 references separately prove normal refinement/presence/motion. Diagnostic source has no default material writer, so appearance evidence is reused at the unchanged accepted V5 material interface, not a new phase campaign.')
patch(29,'1D-08','satisfied','Affected diagnostic source/comments and strict smoke projection traced to delivered source; fresh current-surface readout closes the mandatory browser instrument gate. Exact-tree independent review and this evidence comment complete instrument proof; public raw-sampler delivery is narrowly supported, not public optical accuracy.')
A[29]['scopeOfDone']='Produced geometry owns absolute time/context; completed paint owns immutable consumed freshness; QA never converts unavailable/stale into fresh. Raw Moon labels use current V5 backing dimensions/shared geometry with integer bounds and explicit unavailable states. Primary current-surface browser probe and F21/21+11/11+6 semantic mutants satisfy both instrument subcases.'
A[29]['freshExecution']['browsers']=[{'executedBy':'primary','freshExecution':True,'receipt':str(AUDIT/'primary-native-F-moon-debug/results.json'),'receiptSha256':digest((AUDIT/'primary-native-F-moon-debug/results.json').read_bytes()),'browser':debug['browser'],'harnessSha256':debug['harnessSha256'],'servedIndexSha256':debug['servedIndexSha256'],'initial':debug['initial'],'sample':debug['current']['sample'],'quality':debug['current']['runtime']['visibleSource'],'consumedFresh':debug['current']['truth']['moonSkyFresh'],'errorControls':debug['errorControls'],'pageErrors':debug['pageErrors']}]
A[29]['proposedNextRlgwoIncrement']={'owner':'Primary reconciliation/publication only','steps':['Publish immutable exact current-surface native receipt/crop links and disclosed fixture adaptation; reconcile this bounded instrument closure.'],'acceptance':'Both original instrument subcases and their mandatory native sanity/consumer/negative controls are satisfied; no diagnostic repair remains.','nonGoals':'No Moon art/physics improvement claim, full-refinement claim from the8s preview, universal optical accuracy, new scheduler or default-frame readback.'}

# R0021: mapped current preservation proof plus new actual human-owner startup successor.
patch(33,'21-01','satisfied','Exact final-v49 sixteen cold/warm scene pairs, successful native lifecycle and current public16 cases establish committed geometry and normal acquisition/retention. Current source suppresses initial transforms and forces style resolution before reveal; old intermittent CSS growth is not a current-source counterexample. This credits the original coherent-neutral acquisition requirement, not the newly amended first-complete celestial scene.')
patch(33,'21-03','satisfied','Accepted host/nativeJob/currentResult interfaces bind UTC/target/generation; actual catalogue tests reject malformed/currentness inputs. Final acquiring/config/target lifecycle proves replacement of obsolete initial fallback projection; no removed synthetic-array success is inferred.')
patch(33,'21-04','satisfied','Actual local detail join blocks direct stars/diffuse at coverage independently of calendar fade;4 fresh interface controls include bright inside/outside positive and a detected fade-scaled leak mutation. Current catalogue opaque-cutout/once-only-cloud/prepared-source controls3/3 and composition/current-terrain controls27/27 combine with exact current final-v49 source/layer/native imagery. This is bounded equivalent compositing proof, not a claim that a new arbitrary SVG star screenshot was captured.')
patch(33,'21-05','satisfied','Current source-bound material/presentation/admission and final/public normal surface references preserve current V5 textured calendar presence; public refinement/refresh has no withdrawal after acquisition. Authorised V5/camera composition replaces old PBR byte identity; exact reference/kernel/linear+encoded composition controls, not the obsolete string guard, discriminate preservation. First-complete celestial startup remains open in new row21-10.')
patch(33,'21-07','satisfied','Final normal1x WebM/contact sheets show real visible cloud position/shape change over20..98s; public normal1x clock/unchanged-scene replacement evidence and final native reduced/full lifecycle source controls are reused. No cloud hash is motion proof and no repeat motion campaign is requested.')
patch(33,'21-08','unverified','Public root/V1 geometry, mobile/constrained wrapper and one-loop source checks are satisfied. Original one-quiescent setup startup/steady callback-cost comparison is not identified; broad loaded N001 status is not this measurement.')
patch(33,'21-09','satisfied','Current comments/docs retain truthful neutral acquisition/current terrain/independent occlusion and qualified approximations. Original old-PBR byteguard failure is accounted with actual accepted V5/current composition replacements; existing evidence is preserved under the new startup successor.')
amendment={'kind':'verified direct human-owner instruction reported by primary','date':'2026-10-08','threadId':'01a11e50-a65e-7e30-a8e6-202f4490f31f','threadTitle':'Fix Moon and star startup pop-in','authority':'Primary verified direct owner request in the separate chat; not inferred from code, issue events or model output. F applies parent-confirmed authority; fresh pixels do not prove the requested repair.','scope':'Owner excludes growing/zooming V1 captures; actual root concern is atmosphere-only first scene followed seconds later by Moon/obvious stars. New first-complete-celestial-scene requirement at main18ff/runtimef443. Separate source-only repair lane is unmerged and cannot change this audit target or issue disposition.'}
A[33]['discussionAmendments']+=' '+amendment['scope'];A[33]['ownerAmendments']=[amendment]
A[33]['requirementMatrix'].append({'id':'21-10','obligation':'Owner amendment2026-10-08: the first visibly exposed celestial scene is complete; root must not expose atmosphere alone then pop in Moon/obvious stars seconds later. V1 growing/zooming captures are excluded from this new root concern.','authoredOwners':[ref('src/native/index.html',2060,2094),ref('moon/src/moon-native.mjs',70,98)],'deliveredConsumers':[ref('index.html',2060,2094),ref('moon/moon-host.js')],'discriminator':'Actual same-document first atmospheric/celestial exposure sequence at exact current root, cold and warm; retain the supplied owner scene and current public first-surface timings.','expected':'First visible complete astronomical scene/current calendar source appears coherently; usable prayer UI remains independent while acquisition occurs.','observed':'Current public root cold scene acquires Moon after seconds (Chromium first visible7.3847s); source commitSkyScene does not require a current V5 surface. Existing rollout proves acquisition then no withdrawal, not immediate complete first celestial exposure. Owner-requested successor repair is not merged.','status':'unmet','evidence':[{'source':ref(FINAL+'runs/joined-v49-final-chromium-startup-warm-moon/results.json'),'freshness':'exact-current retained native startup plus fresh common public receipt summarized inline','scope':'Acquisition and retention are distinct from new first-complete startup acceptance.'}]})
A[33]['gaps']=['New verified owner requirement21-10 is unmet at this audited target: root exposes an atmospheric scene before current Moon/obvious stars arrive. Existing no-withdrawal evidence remains valid after first acquisition.', 'Original scoped startup/steady callback-cost comparison remains unverified; do not convert loaded N001 PARTIAL into a blanket blocker or a cost PASS.']
A[33]['proposedNextRlgwoIncrement']={'owner':'Named startup successor Fix Moon and star startup pop-in; src/native initial scene/real-sky preview/current Moon presentation boundary','preserve':'All current accepted-source fences, V5 material/opacity, neutral usable prayer UI, normal motion and current post-acquisition continuity. Audit target18ff remains immutable; separate source-only repair is unmerged.','steps':['Under the verified owner amendment, implement a first-complete celestial scene commit at the actual root interfaces without hiding usable prayer information or fabricating Moon/stars.','Use the owner-supplied root scene and exact cold/warm current-source timeline to distinguish first atmosphere exposure from first complete celestial scene. Exclude V1 zoom/growth as instructed; retain existing no-withdrawal proof.','Qualify only affected entry/reinit/transition and one-quiescent startup/steady callback cost; reuse unchanged current V5/opacity/motion/UI evidence narrowly.'],'acceptance':'The first exposed celestial scene is complete and coherent; subsequent normal source changes/motion/current terrain remain; cost/retained state does not regress materially in the original scoped comparison.','nonGoals':'No V1 edit, Moon material/profile rewrite, ephemeris/prayer/clock redesign, fake early object, whole-widget loading hide or closure by this audit of an unmerged successor.'}
A[33]['missingChecksRequested']=[{'name':'startup successor first-complete scene discriminator','command':'Future exact successor cold/warm native first-exposure captures on the verified owner root scene, plus one-quiescent callback inventory/cost comparison.','reason':'A named owner-authorized source-only lane is already active; no duplicate repair/campaign in this audit.'}]

# R0022: do not impose calendar synthetic permission on legitimate actual astronomy.
patch(34,'22-01','satisfied','Owner-adopted CP9 explicitly retains physical astronomical Moon illumination/occultation separately from the enlarged calendar Moon. Actual whole-source host capture -> nativeJob -> physicalSkyState is unchanged by forced calendar phase/altitude at equal accepted UTC; native false-calendar light stays0.4 fresh interface controls demonstrate this actual boundary.')
patch(34,'22-02','validly superseded','Original native calendar-derived light consumers still obey the shared zero gate: fresh24/24 including near-new/below/daylight/forced/weather faults. Applying the synthetic near-new/day gate to independent legitimate astronomical scattering is superseded by explicit owner CP9 physical/calendar separation; actual accepted astronomy/currentness supplies that term, not decorative calendar permission. The public opt-in below-horizon case also has every native consumer0 while calendar remains visible.')
patch(34,'22-03','validly superseded','Synthetic _starEls/_glintEls wash/projection mechanism is replaced by owner-adopted actual catalogue and accepted astronomical transport. Current source is independently owned/fenced, never calendar phase/opacity-derived. Three fresh current catalogue controls include actual contrast-driven return, opaque cutout and owned source buffers;4 interface controls reject stale accepted UTC/target and detect fade-scaled star leakage. No removed-array exclusion alone earns a pass.')
patch(34,'22-04','satisfied','Fresh native24 cases and six semantic mutants cover local glow floor/independent optics leaks, forcing, weather expiry/recovery and native zero permission. Condition gains remain distinct; the two original leak mutants are caught at actual paint.')
patch(34,'22-05','unverified','Native allowed-state consumers are covered24/24; authorised actual astronomy/current V5 material have separate accepted reference, admission and composition controls. The six original combined balance comparisons stop at removed synthetic arrays before their full comparison; a narrowly scoped native eligible-gain/current-material replacement is not yet mapped completely. This does not assert loss of current approved art or require a Lambert curve.')
patch(34,'22-07','satisfied','Current V5 surface/admission/opaque local join keeps direct stars/diffuse out independently of calendar emphasis, with outside-positive and leak-negative controls. Final/public current source/layer/native images and no-withdrawal/refinement receipts are reused at matching interfaces; the8s sampler is preview/raw only and is not promoted to a complete phase or optical test.')
patch(34,'22-08','unverified','Actual normal1x visible motion/public replacement, native reduced/full lifecycle, geometry, weather and one-loop/source retention are supported by bounded current reuse. Original same-scene warmed paint-cost before/after measurement remains unverified; broad performance/solver qualification is not this gate.')
patch(34,'22-09','satisfied','Authoritative ownership docs explicitly separate numerical physical astronomy from native calendar geometry/light. Current native shared-gate comments remain applicable to native consumers; no new policy decision or categorical astronomy-zero mandate is required. Retained eight legacy failures stay individually accounted; actual replacement controls are mapped here.')
A[34]['scopeOfDone']='All native calendar-derived lunar atmospheric consumers share the consumed zero/eligible permission, including local glow and distinct optics. Explicitly owner-adopted physical astronomical scattering and real stars use independent accepted UTC/observer/source currentness; false decorative calendar light is not promoted into that system. Current opacity/currentness interfaces have meaningful positive/negative replacement controls.'
A[34]['gaps']=['The six old combined native eligible-phase balance comparisons terminate at removed synthetic star/glint arrays. Current native/astronomical/V5 controls satisfy several sub-obligations, but a narrowly mapped replacement for the still-binding native eligible-gain preservation comparison is incomplete.', 'The original one-scene warmed native paint before/after cost comparison is not identified. No numerical/calendar astronomy-zero policy decision is needed.']
A[34]['dependencies']=['Native consumed light follows R001D; current terrain/occlusion follows independent admitted V5/composition interfaces.','Owner-adopted CP9 physical astronomical scattering/current catalogue remain separate from native decorative calendar permission. No legacy synthetic near-new/day gate is imposed on legitimate actual astronomy.','R0021 new first-complete startup remains a distinct interface; it is not a blanket R0022 blocker.']
A[34]['proposedNextRlgwoIncrement']={'owner':'Native eligible-light comparison fixture in tests/r0022-baseline-balance.cjs and scoped current material/astronomical qualification mapping','preserve':'Keep shared native zero gate and existing24/24+leak mutants, actual astronomical accepted-source/currentness, current V5 material and approved atmospheric scene.','steps':['Replace the old combined array/PBR-byteguard baseline with explicit semantic native allowed-gain preservation assertions at original fractions, and independently map the already owner-adopted actual catalogue/material references. Do not restore synthetic arrays or force calendar eligibility onto actual astronomy.','Retain existing current opacity/motion/optics/provider/UI proof; add only a still-missing narrowly mapped comparison, not a new all-phase science campaign.','Measure original one-quiescent scene warmed native paint cost before/after the shared-gate path and retained state; repair only an observed regression under ordinary authorization.'],'acceptance':'Every still-binding native zero/allowed and preservation obligation has an actual reaching discriminator; physical/calendar source separation remains explicit; original scoped warmed-cost proof is supplied without optical/GPU/battery overclaim.','nonGoals':'No Lambert mandate, new policy debate, false calendar-derived astronomical moonlight, ephemeris/material redesign, synthetic array shim or blanket N001/N002/N003 prerequisite.'}
A[34]['missingChecksRequested']=[{'name':'native eligible-gain replacement plus warmed paint measurement','command':'Bounded adaptation of tests/r0022-baseline-balance.cjs to current semantic owners, preserving original eligible native assertions; reuse current catalogue/V5 controls separately. One original-scope quiescent warmed native paint comparison.','reason':'Only these mapped preservation/cost gaps remain; the alleged mandatory-zero conflict with actual astronomical scattering is withdrawn.'}]

# R0025: preserve actual motion; leave only named native pixel/operator and cost proof gaps.
patch(37,'25-01','satisfied','Fresh9/9 continuity+16/16 lifecycle controls pass exact current source. Six original cloud mutants are caught with full reached-terminal/source-hash/count safeguards; removing the obsolete reveal/PBR baseline is explicitly a cloud-only adaptation, not an aggregate all-suite pass.')
patch(37,'25-02','satisfied','Fresh actual painter gradients/noise/columns assert equal-time windspeed/heading/calm/reversal/gust state, elapsed old-velocity integration before setter and future positive motion. All25 original cloud cases and six cloud fault mutants discriminate.')
patch(37,'25-06','satisfied','Fresh actual source16-case lifecycle verifies visible columns/drops/expiry and independent immediate weather/target permissions; final native positive rain/controlled layer imagery is reused only at the unchanged cloud-column/permission interfaces. No radar-alpha rate/observed-rain claim is made.')
patch(37,'25-07','unverified','Current source commands/noise are discriminating for exact original wind/day mechanisms, and final rendered normal motion proves the real painter remains active. A source-bound native actual RGBA/crop comparison for the named equal-time wind/day/month/year/no-op operators has not been identified. The retained continuity-v45 panel concerns Moon acquisition/retention, so it is not falsely credited to cloud wind/day pixels.')
patch(37,'25-08','satisfied','Exact current final normal1x motion contact sheet/WebM shows visible cloud travel/lifecycle over20..98s; public unchanged normal1x root observations and source-bound reduced/full/hidden lifecycle controls support the scoped preservation interfaces. Frozen simTime/hash are not motion proof; no repeat live-motion campaign is requested.')
patch(37,'25-09','satisfied','Current beginSkyScene clears coverage/density/canvas; source/command target and permission-expiry controls reach actual consumers, and current geography/native lifecycle validates accepted target reinit. A full administrative issue dependency is not introduced.')
patch(37,'25-11','satisfied','Current high-value old-velocity/suspension/seed comments and source-bound docs remain true. Public card/wrapper/UI, current V5/opacity, honest dawn/registered solar interface and approved scene are reused at unaffected owners. This row does not close the still-missing wind/day pixel/cost rows.')
A[37]['gaps']=['The original specifically named equal-time wind/day/month/year/no-op actual native painter RGBA/crop discriminator is unverified. Exact-source25 command/state cases and six mutations prove mechanisms but do not automatically satisfy the separately required native pixel comparison.', 'The original one-quiescent setup steady cloud-painter before/after cost and retained-state measurement is unverified; broad loaded performance and Moon-continuity panels are not substitutes.']
A[37]['proposedNextRlgwoIncrement']={'owner':'Actual native cloud painter fixture/captured RGBA and scoped cost receipt; src/native cloud phase/population owners only if a demonstrated fault requires repair','preserve':'Stable accepted-target population, integrated old wind, bounded axes, first coverage, immediate precipitation permissions and all25 fresh source controls/6 detected faults; current actual normal motion is already retained.','steps':['Add only the original equal-time wind/day/month/year/no-op native painter pixel operators with original finite synthetic inputs, healthy and relevant phase/reseed fault controls; retain earlier failure witnesses.','Reuse final/public actual normal1x motion, current Moon/solar/UI/rain interfaces and reduced/full/hidden controls through explicit source equivalence; do not repeat a whole browser/terrain campaign.','Run the original single-quiescent before/after steady cloud-painter cost/retained-state comparison; add no provider/history/cluster allocation/loop and repair only a demonstrated regression.'],'acceptance':'Named native pixels agree with the25 already proven source/state mechanisms and relevant faults discriminate; original scoped cost/state comparison shows no material regression.','nonGoals':'No new renderer, Plan07 governor, battery programme, owner observation, terrain/phase campaign, palette/physics rewrite or cloud-hash motion credit.'}
A[37]['missingChecksRequested']=[{'name':'only named cloud pixel operators and quiescent painter cost','command':'Original issue finite Date/prayer/weather scene; real current cloud canvas RGBA/crops at equalT wind3->3.1, heading/calm/reversal/gust and UTC/day/month/year/no-op operators, with relevant phase/reseed negatives; one quiescent steady painter comparison.','reason':'Visible live motion already proven; no new motion/terrain/whole-phase campaign requested.'}]

def cell(x):return str(x).replace('|','\\|').replace('\n',' ')
def label(r):return f'[{r["path"]}]({r["url"]})'
def comment(a):
 closed=a['verdict'].startswith('CLOSE');title=f'RLGWO closure proof — {a["canonicalId"]} — {a["title"]}' if closed else f'RLGWO closure audit — {a["canonicalId"]} — REMAINS OPEN'
 lines=[f'# {title}','',f'<!-- RLGWO-AUDIT:{SHA}:{a["canonicalId"]}:2026-10-08 -->','',f'**Recommendation: {a["verdict"]}.** {a["scopeOfDone"]}','',f'Target `{SHA}`, tree `{TREE}`, runtime `{RUNTIME}`, root index `{INDEX}`. Audit date2026-10-08. Original complete body SHA-256 `{a["originalBodySha256"]}`, revision `{a["originalUpdatedAt"]}`. All body/discussion/events were read; no event is treated as permission.','', 'Delivered baseline is independently recorded as DELIVERED_VERIFIED with16 actual public root/V1 Chromium/Firefox cases PASS. Actual browser launches were serialized by the primary; F ran only authorized lightweight Node/VM controls and inspected receipts/crops. Sol6.1/max is confirmed by recorded client turn configuration, not hardware/backend attestation.','', '| Mandatory obligation | Source owner → delivered consumer | Discriminator and expected | Observed / disposition |','|---|---|---|---|']
 for r in a['requirementMatrix']:
  lines.append('| '+' | '.join(cell(v) for v in [r['id']+': '+r['obligation'],', '.join(label(x) for x in r['authoredOwners'])+' → '+', '.join(label(x) for x in r['deliveredConsumers']),r['discriminator']+' Expected: '+r['expected'],r['observed']+' **'+r['status'].upper()+'**'])+' |')
 lines += ['', 'Fresh controls (actual target/source binding; attempts and results remain separate):']
 for x in a['freshExecution']['productTests']:
  t=x.get('terminal');obs=t if t else 'Full JSON/log retained; exit='+str(x.get('exitCode'))
  lines += ['- `'+cell(' '.join(x['command']))+'` — exit'+str(x.get('exitCode'))+'; '+cell(json.dumps(obs,separators=(',',':')))+'. Log SHA-256 `'+x['logSha256']+'`.']
  for change in x.get('changes',[]):lines += ['  '+change]
 if a['issueNumber'] in [33,34]:
  lines += ['- Current actual host/calendar/scientific interface controls4/4; fade-scaled direct-star leak mutant caught with a bright outside-positive control. Fixture SHA-256 `8c3609830205f3fea9fb2983278bb1ded210fba5c8466025d693ef4b7ef344ff`; local join source SHA-256 `3cfa1498918706adf21a5f8462f27f9919bed9402f179b03ae3e932500c5cba0`. Actual current-catalogue selected controls3/3 and current contract/composition/terrain-admission27/27. These are real numerical/encoded-source controls, not new native hostile-star photographs.']
 for x in a['freshExecution']['browsers']:
  lines += ['- Primary native '+x['browser']['family']+' '+x['browser']['version']+' on Windows: receipt SHA-256 `'+x['receiptSha256']+'`; driver/fixture SHA-256 `'+x.get('driverSha256',x.get('harnessSha256',''))+'` / `'+x.get('fixtureSha256','actual served index '+x.get('servedIndexSha256',''))+'`.']
  if 'cases' in x:lines += ['  '+cell(json.dumps(x['cases'],separators=(',',':')))]
  else:lines += ['  Raw sampler current quality `'+x['quality']+'`, consumedFresh=true, initial unavailable, all5 invalid coordinates OOB, missing-context/throwing-read unavailable, methods restored and no page errors. Native sample values are retained in row1D-05; no refined/optical claim from preview.']
 if a.get('ownerAmendments'):lines += ['', 'Owner amendment2026-10-08: '+a['ownerAmendments'][0]['scope']+' '+a['ownerAmendments'][0]['authority']]
 paths={}
 for r in a['requirementMatrix']:
  for e in r['evidence']:paths[e['source']['path']]=e
 lines += ['', 'Retained immutable evidence (historical executions, not reruns):']
 for e in paths.values():lines += ['- '+label(e['source'])+' — '+e['scope']+'.']
 if a['issueNumber'] in [29,33,34]:lines += ['- Historical moon-visual-acceptance at earlier ef263 runtime is FAIL (worker/published/legacy canvas inequality); it is not credited as an all-phase PASS. Current final-v49 reference/source-layer/native and mathematical currentness/opaque composition controls are the mapped replacements.']
 lines += ['', 'N001/N002 PARTIAL and N003 BLOCKED are considered only at mapped interfaces. Eight retained native legacy failures remain individually named; absent synthetic arrays and old PBR byte equality are neither product defects by themselves nor automatic passes. No all-browser, optical-calibration, GPU/battery, CI or external human-approval claim is made.','']
 if not closed:
  lines += ['## Next RLGWO increment required for closure','']
  for gap in a['gaps']:lines += ['- '+gap]
 else:lines += ['Every mandatory row is satisfied or validly superseded. No runtime repair remains for this instrument/control issue.','']
 nxt=a['proposedNextRlgwoIncrement'];lines += ['', 'Bounded owner/scope: '+nxt['owner']+'.']
 if nxt.get('preserve'):lines += ['', 'Preserve: '+nxt['preserve']]
 for i,step in enumerate(nxt['steps'],1):lines += [f'{i}. {step}']
 lines += ['', '**Acceptance:** '+nxt['acceptance'],'','**Non-goals:** '+nxt['nonGoals'],'','Dependencies:']
 for dep in a['dependencies']:lines += ['- '+dep]
 lines += ['', 'Fresh local receipts/fixtures/crops above await the primary evidence-only commit and immutable public links; essential expected/observed results and hashes are included inline. This is a returned reviewer proposal, not a posted or approved comment. Primary must reconcile this issue individually and approve publication after evidence custody. No reviewer source/GitHub/commit/push effect occurred.']
 return '\n'.join(lines)+'\n'

for n,a in A.items():
 # Protected original literal/hash/range contract retained after all follow-up edits.
 p=readj(AUDIT/'issues'/f'{n}.json');assert a['originalBodySha256']==digest(p['issue']['body'].encode())
 for r in a['requirementMatrix']:
  assert r['status'] in ['satisfied','validly superseded','unmet','unverified']
  for x in r['authoredOwners']+r['deliveredConsumers']:
   assert (ROOT/x['path']).is_file()
   if x['lines']:assert 1<=x['lines'][0]<=x['lines'][1]<=len((ROOT/x['path']).read_text(encoding='utf-8').splitlines())
 if a['verdict'].startswith('CLOSE'):assert not a['gaps'] and all(r['status'] in ['satisfied','validly superseded'] for r in a['requirementMatrix'])
 (OUT/f'{n}-assessment.json').write_text(json.dumps(a,indent=2,ensure_ascii=False)+'\n',encoding='utf-8');(OUT/f'{n}-comment.md').write_text(comment(a),encoding='utf-8')
summary={'schema':'rlgwo-worker-summary-v2','reviewer':'F','target':SHA,'tree':TREE,'runtime':RUNTIME,'requestedModel':'gpt-6.1-sol','requestedEffort':'max','effectiveConfigurationConfirmed':True,'effectiveConfigurationEvidence':{'path':'reviewer-model-settings.json','sha256':digest((AUDIT/'reviewer-model-settings.json').read_bytes()),'kind':models['confirmationKind'],'sessionId':ms['session']['id']},'assigned':list(A),'sourceDirtyState':'clean','deliveredBaseline':'DELIVERED_VERIFIED; common public16casesPASS','productTestsExecuted':light['commands'],'fixtureAdaptations':adapt['adaptations'],'replacementControls':replacement,'browserTestsExecutedBy':'primary only; F inspected actual receipts/crops','results':[{'issue':n,'canonicalId':a['canonicalId'],'verdict':a['verdict'],'gaps':a['gaps'],'assessment':f'{n}-assessment.json','comment':f'{n}-comment.md','requirements':len(a['requirementMatrix'])} for n,a in A.items()],'crossIssueDependencies':{str(n):a['dependencies'] for n,a in A.items()},'missingChecksRequested':[{'issue':n,**x} for n,a in A.items() for x in a['missingChecksRequested']],'primaryQuestions':[],'ownerAmendments':{'33':amendment},'publication':'HOLD: individual primary reconciliation/approval and fresh immutable evidence links required; no worker GitHub effects.','noBlanketBlocker':'N001/N002/N003 status not a blanket dependency; no closure quota.','stop':'Bounded follow-up complete; no new programme or browser launch by F.'}
(OUT/'summary.json').write_text(json.dumps(summary,indent=2,ensure_ascii=False)+'\n',encoding='utf-8')
(OUT/'README.md').write_text('# Reviewer F final bounded follow-up\n\nSource target '+SHA+'; tree '+TREE+'; runtime '+RUNTIME+'. All original packets read. F owns only this directory. Source stayed clean; no production/GitHub/commit effects.\n\nF ran authorized lightweight source/VM controls. Primary ran all browsers serially; F inspected receipts and crops. Native radio V2 both engines and actual current-surface opt-in sampler complete #26/#29 recommendations. #33 explicitly carries the new verified owner first-complete celestial scene successor. #24 direct default-policy gap remains without an invented owner decision; #34 legitimate astronomy is separated from false calendar light. See per-issue complete matrices/comments and summary.json.\n\nInitial packets are preserved in pre-followup. Prepared V1/V2 radio fixtures are retained for receipt hash custody; no browser was launched by F. Sol6.1/max confirmed by recorded client configuration, without hardware/backend attestation. Publication remains primary-held pending reconciliation and immutable fresh evidence links.\n',encoding='utf-8')
assert git('status','--porcelain')==''
print(json.dumps({'issues':list(A),'matrices':sum(len(a['requirementMatrix']) for a in A.values()),'verdicts':{n:a['verdict'] for n,a in A.items()},'sourceClean':True,'out':str(OUT)}))
