import datetime,hashlib,json,pathlib,subprocess
ROOT=pathlib.Path('C:/Users/theis/.codex/worktrees/hotfix-startup-clouds/salah_widget');OUT=pathlib.Path(__file__).parent
NODE='C:/workspace/ai/cp9-integration-20261005/toolchain/node-v22.16.0-win-x64/node.exe'
definitions=[('lunar-interface-controls',[str(OUT/'lunar-interface-controls.cjs')]),('native-catalogue-currentness-opacity',['--test','--test-name-pattern=current bright-catalogue|preview rejects corrupt catalogue|prepared sky owns','tests/real-sky/native-star-preview.test.mjs'])]
receipt={'target':'18ff14860ff41c084b1db5f396bb62aa9c22b1be','indexSha256':hashlib.sha256((ROOT/'index.html').read_bytes()).hexdigest(),'scope':'No browsers/terrain/solvers; bounded replacement controls for actual accepted host, astronomical source, catalogue and local opacity join. Current real-sky source is called, not removed synthetic arrays. Numerical encoded frame data are not native screenshots.','commands':[],'setupAttempts':[{'result':'fixture setup error, no product conclusion','reason':'First custom adapter re-injected native-host hooks that the whole-source harness already executes, causing duplicate _cp9SiteElevation declaration. Removed the redundant injection.'},{'result':'fixture input-order failure, no product conclusion','reason':'A same-minute in-memory boot-flag change was initially followed only by render(), which deliberately reuses geometry. Corrected the test to call the actual renderMoon producer before actual render; no assertion/production code changed.'}],'earlierFreshToolReceipt':{'command':[NODE,'--test','tests/real-sky/native-contract.test.mjs','tests/real-sky/native-composition.test.mjs','tests/real-sky/native-moon-admission.test.mjs'],'exitCode':0,'tests':27,'pass':27,'fail':0,'durationMs':91.7811,'kind':'Fresh execution in tool output, summarized here without claiming a retained full stdout log'}}
for name,args in definitions:
 start=datetime.datetime.now(datetime.timezone.utc);r=subprocess.run([NODE,*args],cwd=ROOT,capture_output=True,timeout=40,encoding='utf-8',errors='replace');log=r.stdout+r.stderr;p=OUT/'followup-tests'/(name+'.log');p.write_text(log,encoding='utf-8')
 item={'name':name,'command':[NODE,*args],'cwd':str(ROOT),'freshExecution':True,'exitCode':r.returncode,'seconds':(datetime.datetime.now(datetime.timezone.utc)-start).total_seconds(),'log':str(p),'logSha256':hashlib.sha256(log.encode()).hexdigest(),'tail':log.splitlines()[-12:]}
 receipt['commands'].append(item);print(json.dumps(item),flush=True)
(OUT/'followup-tests/replacement-receipt.json').write_text(json.dumps(receipt,indent=2)+'\n',encoding='utf-8')
