import json, hashlib, re, subprocess
from pathlib import Path

OUT=Path(__file__).resolve().parent
AUDIT=OUT.parent.parent
REPO=Path('C:/Users/theis/.codex/worktrees/hotfix-startup-clouds/salah_widget')
SHA='18ff14860ff41c084b1db5f396bb62aa9c22b1be'
TREE='35208181eea714c17f5e77b2644e76434345db60'
RUNTIME='f443cf0820e6879dfa7c3ce857d6b2baf554b1fdd2f889433d22e2c532cec260'
INDEX='ff728552442f4bcce7f213a089bf01d4cf70ea8d74040bdd3323768ca453beee'
NODE='C:/workspace/ai/cp9-integration-20261005/toolchain/node-v22.16.0-win-x64/node.exe'

def read_text(p):
    b=Path(p).read_bytes()
    return b.decode('utf-16' if b.startswith((b'\xff\xfe',b'\xfe\xff')) else 'utf-8-sig')
def read_json(p): return json.loads(read_text(p))
def link(path,a,b=None):
    return {'path':path,'start':a,'end':b or a,'url':f'https://github.com/theislampill/salah_widget/blob/{SHA}/{path}#L{a}'+(f'-L{b}' if b and b!=a else '')}
def S(a,b=None): return link('src/native/index.html',a,b)
def C(a,b=None): return link('index.html',a,b)
def T(p,a=1,b=None): return link('tests/'+p,a,b)
def D(p,a,b=None): return link(p,a,b)
def row(ref,obligation,source,consumer,discriminator,expected,observed,state='satisfied'):
    return dict(contractReference=ref,mandatory=True,obligation=obligation,authoredOwner=source,deliveredConsumer=consumer,
      discriminator=discriminator,expected=expected,observed=observed,disposition=state)

SPEC={}
SPEC[1]={
 'suite':'r0001-date-sinks.cjs','count':13,
 'scope':'Actual config module, complete native inline runtime, model and real render with recording DOM; async boot and unrelated art callbacks are suspended. Raw sink markup is checked. Browser node creation and event execution are not emulated.',
 'rows':[
 row('Smallest repair 1; Incident mechanism','CE formatted output is inert at its final HTML sink; constant CE era markup survives.',S(836,846),C(2960,2970),T('r0001-date-sinks.cjs',57,60),'Hostile hash is literal, once encoded; no raw SVG at CE; ordinary era span remains.','Fresh real-render cases pass; CE-only encoding mutant reaches raw SVG and is detected.'),
 row('Smallest repair 1; Incident mechanism','Selected AH formatted output is inert at its final HTML sink; era/stale markup survives.',S(839,849),C(2963,2973),T('r0001-date-sinks.cjs',58,71),'No raw hostile markup at selected AH, with trusted fixed era/stale spans retained.','Fresh hash/provider/stale/after-Maghrib cases pass; AH-only mutant is detected.'),
 row('Smallest repair 1; preview control','Pre-Maghrib tomorrow-day preview has its own inert boundary, independently of upstream numeric rejection.',S(815,816),C(2965,2966),T('r0001-date-sinks.cjs',28,40),'Admitted-state fixture reaches a present preview and renders the hostile day as literal text.','Test-only reached-projection injection preserves production admission; preview-only mutant emits raw SVG and is detected.'),
 row('Smallest repair 2','Keep configuration ingress/serialization literal and formatter plain text; escape once only at HTML output.',link('src/native/config.js',47,47),link('config.js',101,122),T('r0001-date-sinks.cjs',62,64),'Arabic, quotes, ampersands and angle literals survive without double encoding; exact held-out token string is 1448 48 Safar Saf 02 2 19 19.','Fresh literal/held-out controls pass; fmtDate remains a plain-text substitution owner.'),
 row('Public recipe: hash and saved format','Both actual configuration input paths reach both sinks; saved path runs without overriding hash format.',link('src/native/config.js',101,122),C(2960,2973),T('r0001-date-sinks.cjs',57,59),'Hash reports CONFIG.source=hash; saved path reports localStorage; both rows are inert.','Fresh two-path controls pass with real config module and isolated Map storage.'),
 row('Public recipe: provider month','Untrusted accepted provider/cache month text remains inert independently of malicious datefmt.',S(780,789),C(2960,2973),T('r0001-date-sinks.cjs',59,59),'DD MMMM YYYY with hostile Gregorian/Hijri month names reaches both sinks safely.','Fresh provider-month case passes without malformed numeric fields.'),
 row('Public recipe: after Maghrib','Actual selected tomorrow AH stays inert after Maghrib and preview is absent; do not import a wrong selector.',S(800,824),C(2924,2948),T('r0001-date-sinks.cjs',61,61),'Tomorrow AH day26 selected at19:00; no mph pre preview; hostile month remains inert.','Fresh actual-model/render case passes.'),
 row('Public recipe: held-out ordinary/empty','Normal token order, Arabic/quotes/&/<>, empty/missing-date behavior and CE/AH markers are preserved.',S(769,789),C(2960,2980),T('r0001-date-sinks.cjs',56,66),'Token output exact; trusted markers present; accepted invalid/missing data never becomes injected HTML.','Fresh held-out/ordinary/escaping controls pass. Missing-date output is explicit Gregorian/Hijri unavailable under successor admission, not a fabricated date.','validly superseded'),
 row('Smallest repair 3-4; mutation matrix','Fixture runs actual config/renderer, fails on missing rendering, isolates storage/network and independently discriminates three sink removals.',S(3068,3103),C(5096,5131),T('r0001-date-sinks.cjs',2,73),'Non-empty six-row actual render plus selected prayer/next time; removing one sink repair fails its reached case while other sinks remain healthy.','Fresh 13 cases pass. Timers/network throw if unexpectedly used; per-realm Map storage; three independent sink mutants detected.'),
 row('Integration: runtime/date-output','Qualification consumers R0009/R0019 share the same selected inert projection; no date validity/calendar/request policy bypass.',S(800,855),C(2924,2979),T('r0009-date-selection.cjs',6,18),'Footer/dateTruth/dialog use one decision, and upstream rejection is retained.','Fresh date selection22 and disclosure16 cases also pass; no production bypass or new persisted schema.'),
 row('DONE; real local browser requirement','Execute hostile hash/saved/month/preview and after-Maghrib controls in an actual disposable browser; inspect CE/AH nodes, visible literal text and canary after confirmed render.',S(836,855),C(2960,2979),T('r0001-browser-fixture.cjs',1,157),'Zero #ce/#ah svg,img,script and no __sw_sec_probe event; real date rendering must have completed.','Prepared fixture exists. No retained issue-specific final-tree browser hostile readback was established; fresh worker execution is Node only. General startup/lifecycle PASS is not this discriminator.','unverified'),
 row('DONE; footer crop','Ordinary footer/era/preview appearance and fixed card geometry need actual crop evidence.',S(427,443),C(2694,2710),T('r0001-browser-fixture.cjs',10,18),'Readable ordinary CE/AH and pre-Maghrib preview crop on325x530 card, with no geometry regression.','No issue-specific final-tree ordinary security-control footer crop was qualified by this worker. Pixel proof remains a primary serial check.','unverified'),
 row('Closure/publication boundary','Final-tree evidence comment and independent source/consumer reconciliation precede manual closure; public protection claims need served-byte identity and consumer readback.',S(836,855),C(2960,2979),D('docs/real-sky/evidence/startup-cloud-20261007/final-v49/CANDIDATE_RUNTIME.json',1,12),'Exact target/runtime/tree and qualifying browser receipt, reconciled by primary.','Source/tree/hash confirmed and relevant source reviewed. Primary public smoke/publication is held outside this worker; browser exploit-control proof is incomplete.','unverified'),
 ],
 'gaps':['Mandatory final-tree actual local-browser hostile/control readback has not been established.','Mandatory ordinary footer/era/preview crop and consumer reconciliation are incomplete.'],
 'next':'Preserve all three final sink encodings and real config/renderer controls. Run the existing hostile cases on a disposable local origin serving unchanged final generated assets. Record confirmed date render, both sink texts/nodes, canary, era/preview crop and three mutation detections. Do not weaken admission to admit a malicious preview day; retain fixture-only output-boundary injection. Reconcile exact bytes and publish only after primary approval.',
 'checks':[{'purpose':'Actual-browser security sink controls and ordinary footer crop','preparationCommand':'node tests/r0001-browser-fixture.cjs <isolated-evidence-directory>','driverRequired':'Primary serial browser driver must navigate each case in a fresh context, serve final dependent assets, inspect CE/AH only, and record canary/nodes/text after ready.'}],
 'dependencies':['R0002 supplies accepted numeric-date validity; do not bypass it for preview injection.','R0009 supplies actual selected AH; R0019 consumes identical inert projection. These interfaces are implemented and source tests pass; their administrative states are not closure proof.']}

SPEC[8]={
 'suite':'r0008-timezone.cjs','count':37,
 'scope':'Actual temporal source and actual boot/apply/render/loop boundary slices with recording DOM and real prayer transport owner; excluded art/catalogue/canvas producers are explicit. Intl is native Node Intl except declared offset/counting controls.',
 'rows':[
 row('Numeric compatibility interface','epochForTzTime returns a finite epoch only for exactly one strictly matching supported inverse; all invalid/gap/fold/unsupported inputs return NaN.',S(924,929),C(3048,3053),T('r0008-timezone.cjs',40,73),'NY2026-03-08 03:30=07:30Z; pretransition01:30=06:30Z; ordinary03:30=07:30Z; fold03:30=08:30Z; gap02:30 and fold01:30 unavailable.','Fresh literal-oracle conversions and fail-closed cases pass.'),
 row('Precision domain','Validate Gregorian fields, finite integer h/m, positive representable year and explicit usable zone; preserve years1-99 and never accept device-zone fallback.',S(880,898),C(3004,3022),T('r0008-timezone.cjs',42,63),'Kathmandu prior UTC day21:45Z, leap day, years1/99 exact; Feb30, NaN, fractions,24:00,minute60,year0 and invalid zone fail closed.','Fresh exact outputs/rejections pass.'),
 row('Algorithm steps1-4','Index every UTC minute U-24h through U+48h inclusive,4321 projections, h23/Gregorian/Latin formatting, strict full-field final round trip; no sparse offsets or first-fold choice.',S(888,929),C(3012,3053),T('r0008-timezone.cjs',75,86),'Supported profile covers full bounded window; zero/multiple entries unavailable; seconds/non-minute/>24h offsets unsupported.','Source implements the bound; fresh count/unsupported-profile controls pass; first-fold mutant is detected.'),
 row('Algorithm step5','At most four in-memory exact-zone/day profiles, unsupported profiles cached, reuse same-day callers and simple eviction; no storage/schema/scheduler addition.',S(903,922),C(3027,3046),T('r0008-timezone.cjs',65,86),'First successful day has4321 profile projections+one final check;23 further hourly conversions add23 projections; fifth day evicts; invalid profile not rescanned.','Fresh counting/eviction controls pass; no localStorage profile owner exists.'),
 row('initSim validity','Assign anchor/timezone/monotonic base only after valid explicit resolution; rejected scene cannot retain prior anchor as new scene.',S(931,947),C(3055,3071),T('r0008-timezone.cjs',88,104),'Rejected NY spring02:30 has no finite anchor; valid UTC recovers; return to bad zone rejects; existing27:30 parsing/frozen/accelerated modes survive.','Fresh validity/legacy-mode cases pass.'),
 row('Consumer boot/apply/adoption guards','Guard explicit validity before first celestial work, reset/config and eligible provider-zone adoption; ordinary no-sim loads remain usable.',S(3251,3327),C(5321,5394),T('r0008-timezone.cjs',107,139),'Invalid boot has0stars/0moon/0requests, nt em dash, left Simulation time unavailable and SIM unavailable; valid configuration restores prior visibility.','Fresh actual-boundary cases pass; guard-bypass mutant is detected. Provider adoption guards source-read; native browser adoption picture not implied.'),
 row('Invalid visible scene and recovery','A scene invalidated after valid state withdraws prior clock-dependent sky/weather/arc/prayer/date outputs; fixed geometry/settings survive and valid config can initialize builders once.',S(950,966),C(3074,3090),T('r0008-timezone.cjs',117,139),'Old moon/cloud callback count does not increase; clock-dependent surfaces hidden; header/settings remain reachable; valid recovery restores prior visibility.','Fresh invalid-after-valid, settings local/preferLocal and once-only builder controls pass.'),
 row('Captured-zone hourly interface','Async weather retains requestZone and passes sixth argument, checks operation ownership before adopting, rejects any invalid/ambiguous/non-increasing track without sorting NaNs.',S(1236,1242),C(3387,3400),T('r0017-weather.cjs',1,20),'A NY03:30 request completed after global zone changes still converts07:30Z; obsolete generation cannot commit; gap/fold track unavailable.','Source reads captured ctx.zone and all ep values must be finite and strictly increasing. Dedicated combined captured-zone async control was not freshly executed or established from a mapped retained assertion here.','unverified'),
 row('Current-weather independence/source age','Rejecting hourly track must not discard independently valid current model data or let invalid time become age evidence; approved owner model presentation remains model estimate.',S(1263,1286),C(3498,3509),T('r0017-weather.cjs',1,20),'Track rejection is independent of admitted current, and no invalid epoch can qualify interpolation/source age.','Current and track admitted separately at src1374-1383; track rejection leaves current eligible under its own TTL. Current-policy amendment is unrelated to inversion precision. Full combined issue-specific negative control remains unmapped.','unverified'),
 row('Countdown interface','Actual elapsed endpoint caller uses the same inverse and branches on finite endpoints; gap/fold produces Countdown unavailable rather than approximate duration.',S(2164,2167),C(4191,4194),T('r0007-countdown.cjs',47,60),'Unresolved endpoint cannot create finite elapsed duration; next actual render states Countdown unavailable.','Source model gates nextEpoch and render gates leftMin. Dedicated gap/fold assertions read in countdown fixture; not rerun by this worker.'),
 row('Independent mutants','Single offset, first fold, ignored sixth-zone argument and invalid consumer bypass each must be discriminated on reached owners.',S(924,961),C(3048,3085),T('r0008-timezone.cjs',146,175),'Ordinary control remains healthy while corresponding spring/fold/zone/boot violation is detected.','Fresh four mutation controls pass; spring mutant08:30Z differs from literal07:30Z, ignored-zone mutant returns Riyadh00:30Z.'),
 row('Browser/currentness acceptance','Actual browser requested clock/error/recovery, settled provider-zone reinitialization, frozen/accelerated controls must use valid pre-script setup and matching accepted input days.',S(931,969),C(3055,3093),T('r0008-clock-harness.cjs',1,30),'Browser shows valid NY03:30 and explicit invalid gap/fold; invalid-to-valid reload/config and adoption work without stale scene.','Fresh tests are source slices/recording DOM. Final-v49 geo gap/fold records are explicitly source/scalar, and generic lifecycle or native clock seek is not this browser pathway.','unverified'),
 row('Browser cold-build/reuse responsiveness','Record profile-build count in repeated actual same-day model/hourly calls and actual supported-browser responsiveness; stop if cold cost unacceptable.',S(903,929),C(3027,3053),T('r0008-timezone.cjs',75,86),'Four-profile bound/reuse observable in real callers; browser remains responsive without claiming an unmeasured deadline.','Node projection counts pass. No mapped browser build-count/cold inverse responsiveness receipt established; generic Moon/sky heartbeat measurements do not isolate inverse builds.','unverified'),
 row('Valid scene regressions','Keep default real motion/reduction override, opaque calendar moon, readable card and no invalid scene credited as normal motion/empty night.',S(950,966),C(3074,3090),D('docs/real-sky/evidence/startup-cloud-20261007/final-v49/QUALIFICATION.json',1,12),'Valid scenes retain visual invariants; invalid scenes remain explicitly unavailable.','General final-v49 scenes are retained for broader owners. No issue-specific invalid/recovered browser crop or matched motion control qualified here.','unverified'),
 row('Documentation obligation','DESIGN explicitly states minute precision, whole-minute offsets within24h, gap/fold unavailable, explicit invalid-scene boundary and revised two-authority clock description.',S(900,902),D('DESIGN.md',138,143),D('DESIGN.md',318,320),'User/developer design matches actual resolver domain and ordinary wall versus explicit preview behavior.','Source comments describe inverse domain, but DESIGN still describes a universal anchored formula and contains no resolver minute/gap/fold/error boundary contract.','unmet'),
 row('Ownership/effects/closure','No dependency/provider/config schema/cache/scheduler redesign; overlapping semantic owners integrated; final source/caller review plus browser proof before closure.',S(924,947),C(3048,3071),D('docs/real-sky/INTEGRATION.md',79,90),'Preserve actual captured-zone/time/day interfaces and prior completed work; publication is separate.','Read-only source review complete; generated consumers match target. Missing interface/browser/docs proof prevents closure; no new owner decision is required.','unverified'),
 ],
 'gaps':['Mandatory DESIGN precision/domain/error-boundary/two-authority update is absent.','Actual browser explicit-clock invalid/error/recovery and settled-provider-zone readback is missing from mapped issue evidence.','Real-caller profile-build count/cold browser responsiveness and combined captured-zone async hourly/current-independence controls remain unverified.'],
 'next':'Preserve the exhaustive four-day profile and all validity guards. Add the narrow DESIGN domain/error/clock clarification; qualify the actual final generated consumer in a serial disposable browser with pre-script clock and day-matching responses. Run NY spring/fold, Kathmandu/leap/year controls, captured-zone held completion/current independence, invalid-before-first-render and valid recovery. Instrument profile builds only in the isolated fixture and retain measured responsiveness without changing thresholds or production precision.',
 'checks':[{'purpose':'Browser clock/error/recovery and bounded resolver cost with captured hourly zones','command':'No existing complete issue-specific browser driver was established. Use primary serial browser on unchanged final root/index with a pre-script Date/performance fixture; preserve node tests/r0008-timezone.cjs as source discriminator.','driverRequired':'Record requested clock/zone/day, render readiness, first-celestial ordering, explicit SIM unavailable, recovered crop, actual profile builds, held captured-zone hourly/current controls.'}],
 'dependencies':['R0003 captures requestZone and owns commit eligibility; source ctx propagation is present.','R0007 consumes finite endpoint; source Number.isFinite gate and exact Countdown unavailable branch are present.','R000B consumes source epoch; invalid hourly tracks are rejected. Source admission is separate from approved model weather presentation.','R0004/R0005 share provider-zone adoption/day identity; R0020 supplies ordinary wall instant. No whole-issue administrative predecessor is invented.']}

SPEC[9]={
 'suite':'r0009-date-selection.cjs','count':22,
 'scope':'Complete actual config/native-inline/model/render with Date installed before initialization, admitted controlled records and recording DOM. Async boot/loaders and unrelated art are suspended. dateTruth is the last-painted snapshot, not a recomputed selector.',
 'rows':[
 row('Causal contract','One ephemeral display decision captures requested/loaded day, location zone, selected payload/method, before/after Maghrib and availability/reason; footer/dialog/dateTruth consume it.',S(791,824),C(2924,2948),T('r0009-date-selection.cjs',6,18),'Painted AH/title/full values/dateTruth agree; later unpainted source change does not alter dateTruth.','Fresh sameProjection, midnight instant-coherence and last-painted diagnostic cases pass.'),
 row('Selection before/boundary','Before17:59:59 show today19+preview20; exactly18:00 select tomorrow20 and remove preview.',S(804,816),C(2928,2940),T('r0009-date-selection.cjs',19,20),'Boundary inclusive at Maghrib; actual tomorrow payload and selected convention supply AH; no arithmetic day increment.','Fresh actual model/render boundary controls pass.'),
 row('Unavailable tomorrow','After18:01 missing/invalid/wrong-day/wrong-zone tomorrow retains usable today with explicit Sunset date update unavailable independently of prayerStale.',S(804,824),C(2928,2948),T('r0009-date-selection.cjs',21,23),'applied=false and unavailableReason exact even prayerStale=false; truthy invalid/wrong context cannot advance/preview.','Fresh missing/wrong-day/wrong-zone/invalid-next controls pass in recording sinks.'),
 row('Unavailable selected AH','When neither usable AH is selected, disclose Hijri date unavailable; do not fabricate date or conceal calendar failure as prayer stale.',S(808,824),C(2932,2948),T('r0009-date-selection.cjs',24,36),'Missing AH, invalid day, wrong current model context and missing name for named format have explicit unavailable output.','Fresh absent/invalid/context/name controls pass; numeric format remains usable without month name.'),
 row('Provenance','Explain actual selected HJCoSA/UAQ code or calendar convention unavailable; prayer method4 does not prove UAQ and today convention cannot label selected tomorrow.',S(812,824),C(2936,2948),T('r0009-date-selection.cjs',27,29),'Tomorrow UAQ identifies UAQ; absent method stays unknown; CONFIG.method unchanged.','Fresh selected-UAQ, missing-method and hostile-method literal controls pass.'),
 row('Removal route','Supersede unsupported global backwards hold/ordinal anomaly policy; accepted correction10->09 and post->pre boundary can return provider selection; duplicates/skips/long sleep cannot support anomaly certainty.',S(791,824),C(2915,2948),T('r0009-date-selection.cjs',25,39),'No locked future date; hijriAnomaly neutral/null; no automatic correction or religious policy change.','No hold state is shipped; fresh correction/reverse/duplicate/skip/long-sleep controls pass; backwards-hold mutant is detected.','validly superseded'),
 row('Delayed tomorrow/midnight','Late valid tomorrow selects once and clears only calendar unavailability; two renders idempotent; midnight promotion keeps20 without synthetic21.',S(804,824),C(2928,2948),T('r0009-date-selection.cjs',24,26),'Same accepted decision after repeated render; prayer stale remains independently owned.','Fresh delayed-arrival/idempotency and admitted midnight selection cases pass. This does not by itself test actual loader late routing.'),
 row('Calendar bounds/security','Valid29/30-day month/year transitions remain provider derived; missing/invalid/hostile format/month/method output stays literal.',S(769,789),C(2960,2979),T('r0009-date-selection.cjs',32,37),'No fixed30 rule or -2 correction; literal text at sinks.','Fresh transitions and missing-name/method cases pass; source sink suite13 cases corroborates real render boundaries.'),
 row('Disclosure access interface','Selected formatted strings/reason feed complete existing keyboard/touch disclosure; do not create second date computation or fetch loop.',S(826,855),C(2950,2979),T('r0019-date-disclosure.cjs',29,35),'Both triggers open same last-painted values, post-Maghrib tomorrow; open updates stable, no storage/request/config effects.','Fresh disclosure16 source cases and today-on-click/rebuild/bounds mutants pass. Native interaction remains its own missing R0019 proof.'),
 row('Actual dependencies','R0002 validity,R0005 day promotion,R0001 inert output,R0020 current instant and timezone-bearing cache remain integrated; selector state is not persisted.',S(800,824),C(2924,2948),T('r0009-date-selection.cjs',33,39),'Wrong current context unavailable; request generation/day ownership retained; no migration into audit-only zone-free namespace.','Source model/adoption interfaces read and controlled selector cases pass. Administrative issue state does not supply actual loader/browser proof.'),
 row('Affected documentation/removal claims','Do not retain unsupported monotonic/anomaly or UAQ claims; explain neutral diagnostic/no algorithmic adjustment within affected owner comments.',S(791,793),D('DESIGN.md',98,104),D('README.md',204,205),'Affected explanations do not claim automatic calendar correction or universal monotonic calendar validity.','Current source comment explicitly excludes increment/hold/anomaly inference. No old candidate monotonic promise or hardcoded UAQ claim was found in reviewed root docs; not importing the audit branch preserves this boundary.','validly superseded'),
 row('Owner24-vs26 report','Keep owner reported24-versus26 disagreement UNVERIFIED until same instant/site/authority/boundary captured; no automatic -2 correction/golden24 fixture.',S(791,824),C(2915,2948),T('r0009-calendar-harness.cjs',8,12),'Synthetic fixture days are display data, not religious adjudication; source method remains provider derived.','Fresh tests use declared synthetic19/20; no correction code or religious-policy decision was made.'),
 row('Mutation reachability','Restore after-only title and backwards hold separately; actual missing-tomorrow/correction guard must fail while healthy render survives.',S(836,855),C(2960,2979),T('r0009-date-mutations.cjs',13,40),'Broken title/hold detected by exact through-render consumers, not helper-only status.','Fresh date mutation harness detects both and second-calendar-instant independently; each preserves healthy before-Maghrib case.'),
 row('Browser closure proof','Compare actual footer cue,text,accessible explanation and last-painted dateTruth across boundary/missing/late/midnight/correction/convention cases with real pre-script clock and matched responses.',S(800,855),C(2924,2979),T('r0009-browser-fixture.cjs',7,80),'325x530 actual crop; cue visibly/accessibly explains missing sunset update despite prayerStale=false; after-only title/hold controls discriminate real browser consumer.','Prepared22-case fixture and source tests are not execution. Final-v49 generic lifecycle carries ordinary dateTruth but lacks the required matched calendar failure/correction/accessibility matrix.','unverified'),
 row('Closure/public delivery','Exact-final-tree independent selection/claim review and browser evidence comment precede manual closure; served-date claim separate.',S(800,855),C(2924,2979),D('docs/real-sky/evidence/startup-cloud-20261007/final-v49/QUALIFICATION.json',1,12),'Reconciled proof scoped to provider disclosure, not calendar authority correctness.','Exact source review and source controls complete; required browser evidence remains missing, and primary publication remains separate.','unverified'),
 ],
 'gaps':['Mandatory exact-tree browser footer/accessibility/dateTruth readback for failure/correction/convention and boundary sequences is missing.','Matched325x530 footer/available-unavailable crops and native access reconciliation remain unverified.'],
 'next':'Preserve the accepted single selector, neutral anomaly output, output encoding and stable disclosure. Complete the existing22-case calendar fixture on a disposable local origin with actual final dependent assets, pre-script fixed Date and matching accepted records. Capture missing-tomorrow despite prayerStale=false, delayed arrival/idempotence, midnight/correction and selected-UAQ/unknown convention. Compare painted text/cue/accessibility/dateTruth and retain title/hold mutants. The24-versus26 religious reference question stays separately unverified.',
 'checks':[{'purpose':'Exact-tree calendar truth/footer/native-access proof','preparationCommand':'node tests/r0009-browser-fixture.cjs <isolated-evidence-directory> <final-worktree-root>','driverRequired':'Primary serial browser must run complete cases with assets served, capture actual325x530 footer/disclosure and accessibility, plus held late/midnight/correction transitions.'}],
 'dependencies':['R0002 usable date admission and R0005 actual day routing remain source interfaces; admitted-state tests do not certify their async browser paths.','R0001 supplies literal safe text; current-source13-case sink evidence is relevant.','R0020 supplies current wall instant and coherent model snapshot.','R0019 supplies native keyboard/touch full-value access; current source event tests are relevant but native focus proof remains missing.']}

SPEC[10]={
 'suite':'r000a-markers.test.cjs','count':25,
 'scope':'Actual source admission/model/solarElevationDeg/full drawArc emitted SVG. Full London/Tromso/Madinah controls retain actual elevation. Explicit numerical boundary tests replace elevation extrema only; no native pixels are emulated.',
 'rows':[
 row('Accepted snapshot','Read per-prayer params from accepted today.meta.method.params synchronously with actual model/arc; no refetch, registry or new config selection against old payload.',S(2262,2286),C(4289,4313),T('r000a-markers.test.cjs',70,76),'New accepted Fajr12/Isha17 replaces old18/17 on next actual arc.','Fresh accepted-payload refresh control passes; no method cache/new prayer setting exists.'),
 row('Numeric interpretation','Fajr/Isha interpreted independently; only finite positive numeric parameter is degree depression; interval/missing/malformed/NaN/zero/negative/string angles are unknown.',S(2265,2274),C(4292,4301),T('r000a-markers.test.cjs',59,68),'90 min is not angle90; unsupported metadata never gets confident unadjusted classification or nonfinite SVG.','Fresh unsupported/missing/nonfinite controls pass; parseFloat interval mutant is detected.'),
 row('Modeled range/equality','Use existing minimum and maximum, exact equality within range; classify target outside wholly-below range unreachable without new tolerance/observational accuracy claim.',S(2191,2204),C(4298,4300),T('r000a-markers.test.cjs',47,58),'min=-18 equality/reached side reachable, -17.999 unreachable; min=-40,max=-20,target-18 unreachable.','Fresh numerical boundaries pass; ignoring maximum and strict-equality mutants detected. These are model numerical semantics, not astronomy certification.'),
 row('Actual classes and descriptions','Only unreachable Fajr/Isha receives adj; reachable ordinary; unknown ordinary with explicit accessible adjustment-classification-unavailable description.',S(2275,2286),C(4302,4313),T('r000a-markers.test.cjs',15,36),'SVG classes AND status/title correspond; description-only change cannot pass.','Fresh full SVG assertions pass; description-only/unknown-reachable mutants detected.'),
 row('London RED->GREEN witness','London2026-06-21 51.5074,-0.1278 Europe/London method3 Fajr18/Isha17 must both gain adjusted rings.',S(2264,2286),C(4291,4313),T('r000a-markers.test.cjs',7,22),'Both adj; Fajr19.37/134.93/r5, Isha274.41/133.93/r5; ordinary -14 comparator must fail.','Fresh actual London model/markup matches positions/radii and both unreachable classifications; universal14 mutant loses both and is detected.'),
 row('Tromso/Madinah controls','Tromso summer retains both adjusted rings/finite output; Madinah18.5 Fajr reachable and90min Isha explicitly unknown ordinary.',S(2265,2286),C(4292,4313),T('r000a-markers.test.cjs',23,36),'No coerced minute angle or global ANGLE_BASED per-prayer assertion.','Fresh complete controls pass; global latitudeAdjustmentMethod label never supplies interval adjustment certainty.'),
 row('Asymmetry','Synthetic min=-17.5,max40,Fajr18/Isha17 flags only Fajr; swapped values swap only classifications.',S(2265,2278),C(4292,4305),T('r000a-markers.test.cjs',47,58),'Both prayers cannot share one Boolean.','Fresh asymmetric cases pass; shared-Fajr mutant wrongly flags Isha and is detected.'),
 row('Preserved arc/prayer semantics','Keep path samples/timing positions/radii, Sunrise hollow ring/horizon, Maghrib horizon and Dhuhr post-transit; no clock/countdown/order changes.',S(2278,2300),C(4305,4327),T('r000a-markers.test.cjs',15,22),'London Sunrise/Maghrib y104, Dhuhrx149.84, original marker positions/r5; finite polar layout.','Fresh actual SVG geometry assertions pass. Source geometry remains existing owner; visually distinct native rings still require pixels.'),
 row('Mutations reached full consumer','Universal14, shared Fajr, parseFloat interval and description-only mutants must fail actual returned class/status/title assertions.',S(2264,2286),C(4291,4313),T('r000a-markers.test.cjs',78,119),'Each named fault detected despite actual admitted timing/model remains functional.','Fresh suite detects all four required and three additional range/status mutants.'),
 row('Documentation and scope','Update existing indicator explanation/regressions only; docs affected only where they describe it; no provider adjustment policy/prayer algorithm/high-lat setting or new method system.',S(2262,2274),D('DESIGN.md',96,118),D('README.md',189,205),'Explanation explicitly model reachability/unknown; no promise provider did/did not adjust interval method.','Source/title comments updated; current reviewed DESIGN/README do not define a universal14 indicator rule to retain. No unrequested provider/method change; no new mandatory documentation scope invented.'),
 row('Actual browser visual closure','Capture actual London both adjusted rings visibly distinct, ordinary Madinah and polar finite-layout arc crops at325x530; CSS class alone insufficient.',S(2264,2286),C(4291,4313),T('r000a-markers.test.cjs',15,36),'Native London crop shows both distinct rings and correct arc; controls preserve header/footer/Sunrise/Maghrib/Dhuhr invariants.','Fresh source25 cases pass. No mapped retained exact-tree London method3 18/17 crop or complete required visual-control set was established. General geography sky crops use different fixtures.','unverified'),
 row('Independent review/public boundary','Exact-tree parameter interpretation review plus RED/GREEN/control/mutation and crops before evidence comment/closure; public visual claim requires served source and crop.',S(2264,2286),C(4291,4313),D('docs/real-sky/evidence/startup-cloud-20261007/final-v49/QUALIFICATION.json',1,12),'Source review and native pixel evidence separately reconciled by primary.','Independent source review and fresh controls complete; required native visual gate remains unverified; no GitHub effect.','unverified'),
 ],
 'gaps':['Mandatory native London adjusted-ring crop plus ordinary Madinah and polar finite-layout controls are missing from mapped exact-tree evidence.'],
 'next':'Preserve independent numeric parameter interpretation, min/max equality contract, unknown interval semantics, actual returned classes/titles and existing geometry. Run a serial actual-entry browser fixture using the issue London/Tromso/Madinah accepted payloads and pre-script local-noon clock. Crop the actual arc/card, confirm both London rings are visible and compare ordinary/unknown/polar controls. Reconcile classes/descriptions/pixels; do not alter solar/prayer algorithms to improve the picture.',
 'checks':[{'purpose':'Native adjusted-marker visibility and geometry controls','command':'No complete existing issue-specific native browser driver was established. Prepare a disposable actual-entry fixture from tests/r000a-markers.test.cjs London/Tromso/Madinah data, then primary serial browser capture at325x530.','driverRequired':'Record method params, accepted day/site/zone/noon, SVG class/status/title, arc crop, Sunrise/Maghrib line,Dhuhr position and visible header/footer.'}],
 'dependencies':['No administrative hard predecessor. Accepted timing+method snapshot must stay coherent.','R0002 complete polar payload is relevant fixture control; numeric admission does not certify provider adjustment policy.']}

SPEC[25]={
 'suite':'r0019-date-disclosure.cjs','count':16,
 'scope':'Actual config/native-inline/model/render/date click/close handlers and authored markup/CSS with recording focus/DOM identity/effect controls. Native Enter/Space/Escape, modal focus containment, touch, layout/overflow/font loading are expressly not emulated.',
 'rows':[
 row('Trigger/layout contract','Stable type=button wrappers around ce/ah preserve IDs/compact ellipsis and flex/min-inline-size allocation; keep footer dimensions/direction; discoverable affordance and focus treatment.',S(427,433),C(2694,2698),T('r0019-date-disclosure.cjs',25,27),'Either actual date is native keyboard/touch entry; compact row remains325x530.','Fresh native-button/source CSS controls pass; title-only trigger mutant detected. Rendered geometry/affordance remains unverified.'),
 row('Bounded labeled dialog','One same-document native labeled dialog overlays iframe, has safe width/height and vertical scroll, wrapping/anywhere/selectable full text; no framework or tiny-font fallback.',S(434,443),C(2698,2710),T('r0019-date-disclosure.cjs',27,39),'Complete long strings within card-minus28px and297px max, viewport-minus28px height; native modal accessible name.','Fresh authored CSS/markup/value controls pass; nowrap and unbounded mutants detected. Actual browser containment is not inferred.'),
 row('Same selected projection','Both full Gregorian/Hijri values, preview and stale/unavailable/provenance explanation are exact last-painted footer projection; no provider fetch/increment/fmtDate reselection on click.',S(826,855),C(2950,2979),T('r0019-date-disclosure.cjs',29,32),'Either trigger exposes both labeled values; post-Maghrib AH is tomorrow20, not today19.','Fresh four-preset and wrong-selection-sensitive click controls pass; today-on-click mutant detected.'),
 row('Saved/incoming input paths','All four supplied presets and saved long-format path show complete selected values from either trigger; safe custom literal/month text preserves content.',link('src/native/config.js',47,47),C(2972,2979),T('r0019-date-disclosure.cjs',28,30),'YYYY-MM-DD,MM/DD/YYYY,DD/MM/YYYY,DD MMMM YYYY full values and preview are accessible through real event handler.','Fresh source cases pass; saved CONFIG.source=localStorage; disclosure is literal textContent.'),
 row('Opening/closing actual handlers','Opening either trigger opens modal; Close restores initiating connected control; native focus behavior must be qualified separately.',S(826,834),C(2950,2958),T('r0019-date-disclosure.cjs',29,29),'Actual click/close handler selects initiator and returns focus; no settings autosave route.','Fresh recording event/focus-return assertions pass. Native showModal focus containment and Escape default semantics not emulated.'),
 row('Stable nodes/tick behavior','Keep triggers/dialog/close/value owners stable, only changed text/attrs rewritten; open panel remains open/focused during tick and source/date transitions without unchanged whole-panel announcement.',S(836,855),C(2960,2979),T('r0019-date-disclosure.cjs',33,35),'Repeated unchanged render does not write values/attrs or replace focus; Maghrib/late source change updates same nodes and reason.','Fresh identity/write/focus/open transitions pass; focused-close-rebuild mutant detected. Native assistive announcements still unverified.'),
 row('Unavailable/late/midnight','Missing/invalid/no-model state clears prior hidden full dates; sunset-unavailable clears on late arrival independently of prayer stale; latest open never shows stale old selection.',S(800,855),C(2924,2979),T('r0019-date-disclosure.cjs',34,36),'Full values exactly match dateTruth; no old1448 value after invalid state; delayed UAQ20 clears sunset cue but retains prayer-stale reason.','Fresh source controls pass; midnight admitted selection corroborated by R0009 suite. Actual browser ongoing-loader/open-panel transition remains unverified.'),
 row('Inert literal/security','Canary,Arabic,ampersands,quotes,angles stay text at compact and full-value owners; no injected node/event or stale hidden text.',S(838,854),C(2962,2978),T('r0019-date-disclosure.cjs',28,38),'No raw SVG in recording innerHTML; full text includes exact literal canary and Arabic punctuation.','Fresh full/compact literal controls pass; Node does not execute HTML handlers. Actual browser node/event control missing.'),
 row('No-effect read','Opening/updating/closing must not change configuration,storage,requests,method,date choice or reuse settings close/autosave.',S(826,855),C(2950,2979),T('r0019-date-disclosure.cjs',32,32),'Effect counts,storage keys,config,today/tomorrow,truth identical across read cycle.','Fresh explicit effect boundary passes; qaState storage probe excluded and disclosed. No requests/storage in actual handlers.'),
 row('Mutations','Title-only triggers,today-on-click,focused-node rebuild and no-wrap/bounds must be detected by corresponding real consumers.',S(826,855),C(2950,2979),T('r0009-date-mutations.cjs',20,42),'Each fault fails its matching through-event/projection/identity/style guard, with long preset healthy positive intact.','Fresh eight-mutant harness includes all five disclosure variants; every required failure observed without source changes.'),
 row('Browser keyboard','Tab reaches both triggers; Enter/Space open; modal focus contained; Close/Escape restore actual initiator and tick does not lose focus.',S(826,834),C(2950,2958),T('r0019-date-disclosure.cjs',1,2),'Native key events and focus chain actually work at normal/tick/transition state.','RecordingDOM explicitly does not emulate modal focus. Final-v49 proof_ui only clicks CE then Close; it cannot prove this keyboard matrix.','unverified'),
 row('Browser touch/pointer/selectability','Either date works without hover; long full values can be touched/scrolled/selected in bounds; Close usable.',S(434,443),C(2694,2710),T('r0019-date-disclosure.cjs',1,2),'Native tap and long scroll/full value interaction at actual viewport.','Existing pointer click/open/close reuse is narrow only; no matched touch/scroll/selectability receipt established.','unverified'),
 row('Browser long/fallback font','Blocked web font plus repeated long custom literal/long month fully obtainable without horizontal overflow/shrunken font; all preset/input paths native.',S(434,443),C(434,443),T('r0009-browser-fixture.cjs',20,38),'Complete year/tail of08 September2026 and26 Rabi al-awwal1448/preview27; long/fallback content remains contained.','Prepared fallback/very-long/long-month fixture exists, and CSS/source text passed; no executed issue-specific final native overflow/fallback/font receipt.','unverified'),
 row('Browser transitions/safe text/no-effect','Open panel reflects pre/post Maghrib,missing tomorrow,midnight,late arrival,unavailable/hostile values; real effects and focus remain unchanged.',S(800,855),C(2924,2979),T('r0009-browser-fixture.cjs',7,80),'Actual DOM/accessibility text/reason matches same footer decision; no unwanted storage/request/config/selection effects; nodes/focus stable.','Fresh recording controls support source implementation only; native browser matrix not established.','unverified'),
 row('Visual geometry/builder','Capture default/long/open crops at measured325x530 card; prayer stack/header/footer/era direction unchanged; builder actual iframe preserved under owner330x534 shell amendment.',S(427,443),C(2694,2710),D('README.md',34,43),'Readable closed footer and closeable bounded overlay; actual inner card325x530 in owner-approved330x534 outer production iframe.','Current source card retained. Owner shell amendment validly supersedes original325x530 wrapper-only claim; matched disclosure/builder geometry crops remain missing.','unverified'),
 row('Supported-host dialog compatibility','If native dialog unsupported in a supported host, explicitly tested fallback before compatibility closure; title alone not fallback.',S(826,834),C(2950,2958),T('r0019-date-disclosure.cjs',1,2),'Supported actual browsers provide required modal behavior or tested small fallback.','Native dialog is used without alternative fallback. No known unsupported-host defect is established; actual required behavior coverage is missing.','unverified'),
 row('Documentation obligation','README/DESIGN full-value access instructions describe opening either calendar value, complete disclosure and read-only behavior; builder description assessed.',S(826,855),D('README.md',204,205),D('DESIGN.md',76,80),'User can discover how long date values are read without enlarging card or changing religious policy.','README mentions only datefmt and compact footer; reviewed DESIGN does not document the full-value disclosure/open/close access instructions.','unmet'),
 row('Dependency/closure','R0001 inert text and R0009 same selected reason are implemented consumer interfaces; exact-tree native interaction/geometry/compatibility plus independent review precede manual closure.',S(800,855),C(2924,2979),D('docs/real-sky/INTEGRATION.md',79,90),'Preserve accepted projection and security; no new preference/persisted schema/provider fetch/geometry enlargement; primary reconciles publication.','Source16 controls+mutants establish meaningful completed work. Required native/documentation closure proof remains missing; no GitHub effects.','unverified'),
 ],
 'gaps':['Explicit README/DESIGN full-value access instructions are absent.','Mandatory native keyboard/focus/Escape/touch/scroll/fallback-font/overflow/transition/safe-event/effect matrix and measured crops are unverified.','Actual builder-preview/disclosure geometry and supported-host native dialog compatibility have not been mapped to exact issue proof.'],
 'next':'Preserve the stable native buttons/dialog, one selected text projection, literal rendering and no-effect handlers. Add narrow README/DESIGN access instructions. Use the existing calendar fixture in a serial disposable actual-entry browser and qualify both triggers across all presets/saved/long/fallback-font/hostile/unavailable/transition cases. Record Tab/Enter/Space/Escape/Close focus, native touch/scroll/selection, effect counters and unchanged nodes. Capture default/long/open card and builder iframe: inner325x530, approved outer330x534. Add a tested fallback only if a supported actual host demonstrates native dialog missing behavior.',
 'checks':[{'purpose':'Native full-date interaction/containment/accessibility and builder geometry','preparationCommand':'node tests/r0009-browser-fixture.cjs <isolated-evidence-directory> <final-worktree-root>','driverRequired':'Primary serial browser all presets/saved-long/very-long/long-month/fallback-font/literal/stale plus keyboard and touch contexts; inspect card,dialog scroll/client boxes and initiator focus/effect counts.'}],
 'dependencies':['R0001 final-sink inert text and full-value textContent are present and source controls pass.','R0009 same selected calendar projection/reason is present and source22 controls pass.','Owner amendment authorizes330x534 production shell around325x530 card; do not reopen old oversized-wrapper mechanism merely because original work order said wrapper325x530.']}

SPEC[32]={
 'suite':'r0020-clock.cjs','count':44,
 'scope':'Actual temporal source, real model/render/boot/apply/loop source boundaries with injected independent Date/performance and recording DOM; real prayer admission/transport owner, excluded art explicit. Controlled visibility callbacks are not native sleep or operating-system clock changes.',
 'rows':[
 row('Authority predicate','Ordinary no-sim/no-scale mode returns current Date.now on every simNow call before anchor/zone reinit; explicit1x keeps anchored preview/ADVANCING compatibility.',S(858,869),C(2982,2993),T('r0020-clock.cjs',7,16),'0,+/-1h,+/-2h wall steps observed immediately; zone changes affect display only; simDate/nowParts share same current instant.','Fresh default5 step cases pass; Kathmandu reformat does not reanchor current epoch.'),
 row('Single temporal API','nowParts/simDate/model/prayer/day/sky use same simNow authority; do not fix only clock text or add separate clocks/rAF.',S(942,969),C(3066,3093),T('r0020-clock.cjs',7,16),'Corrected current instant reaches actual model/parts/date consumers.','Fresh simNow/nowParts/simDate and actual prayer-model/loop cases pass; one existing rAF owner retained.'),
 row('Explicit mode table','Explicit scale1/60/no-sim anchor; simTime frozen or rate1/60 independent; scale0/empty/invalid/negative retain parsed frozen semantics.',S(863,947),C(2987,3071),T('r0020-clock.cjs',61,75),'Each mode unchanged under +/-1h/+/-2h steps; actual ADVANCING flag agrees with parameter presence/rate.','Fresh36 explicit-mode controls pass; no query parser or forecast intent change.'),
 row('Converter rejected scene','Explicit inverse invalidity cannot retain old numeric anchor; shared R0008 entry guards stay intact.',S(931,966),C(3055,3090),T('r0008-timezone.cjs',88,139),'Invalid explicit scene unavailable before celestial/render/time use; valid recovery allowed.','Fresh R0008 validity/recovery controls pass; no blanket Date.now default branch for explicit simTime.'),
 row('Forward/backward scheduled render','Preserve sec!==lastSec, not increasing-only; next scheduled visible render reflects either wall direction and same coherent model snapshot.',S(3407,3415),C(5436,5444),T('r0020-clock.cjs',18,34),'15:29:59 Dhuhr/Asr ->15:30:01 Asr/Maghrib ->15:29:59 Dhuhr/Asr; backward countdown1/60min.','Fresh actual loop/model/recording DOM boundary case passes; increasing-only mutant retains future Asr and is detected.'),
 row('Day correction actual interface','Forward midnight adopts day-matching completed prefetch; late old request not current; backward day acquisition/reclassification preserves actual day and owning slots/cache identity.',S(1129,1189),C(3253,3318),T('r0005-day-return.test.cjs',21,105),'No yesterday/future labeled current; request finally cannot clear newer owner; prompt reverse day returns correct countdown/date.','Source day classifier/cooldown retirement/ownership inspected; dedicated actual-loop forward/reverse tests read. Worker44 clock cases alone do not qualify every full day/late/cache release sequence; retained exact relevant browser proof not established.','unverified'),
 row('Hijri reverse policy','Backward instant must not hide restored selection behind future Hijri hold; actual provider selection and boundary disclosed.',S(791,824),C(2915,2948),T('r0009-date-selection.cjs',25,39),'Post-Maghrib tomorrow20 returns pre-Maghrib today19; no monotonic clamp; wrong day unavailable.','Fresh R0009 correction/reverse/context cases pass; neutral anomaly/no hold source preserved.'),
 row('Real-elapsed prayer eligibility/ownership','R0006 prayer current/prefetch/rollover cooldown stays on _RAFNOW, not wall/simulated minutes; preserve busy operation and one eligible retry, no request storm.',S(1158,1178),C(3280,3300),T('r0005-day-return.test.cjs',60,76),'Failed acquisition remains60s monotonic cooldown and starts at next eligible visible opportunity even wall correction; old finally cannot clear new slot.','Source beginPrayerRequest uses elapsed+60000 and independent ownership; dedicated source cooldown/return assertions inspected. Full required combined wall-step/deferred release browser evidence remains unverified.','unverified'),
 row('Hidden/offscreen resume','Keep visibility/IntersectionObserver cancellation; first resumed callback reads current wall, one existing eligible opportunity, no missed-second/day catchup or second loop.',S(3427,3434),C(5456,5463),T('r0020-clock.cjs',36,47),'Hidden pending0, resume pending1, new wall18:00:01 renders Maghrib/Isha once and retains one callback.','Fresh controlled visibility source test passes. Actual native sleep/wake remains expressly outside claimed scope.'),
 row('Fallback host precision','Where performance.now absent and _RAFNOW fallback is Date.now, monotonic independent-preview guarantees require actual host qualification; no universal native sleep/NTP claim.',S(863,863),C(2987,2987),T('r0020-clock.cjs',1,4),'Scope clock guarantees to supported monotonic fixture/host; no OS clock mutation or invented actualNTP/sleep incident.','Fixture explicitly provides independent performance.now; no native fallback/suspend result claimed. This limitation is preserved, not waived.'),
 row('Independent mutants','Old anchor formula,broad default predicate,increasing-only loop each fail default-step,explicit-frozen,backward actual-render controls respectively.',S(867,947),C(2991,3071),T('r0020-clock.cjs',49,60),'Default skew repaired without sacrificing explicit modes or backward consumer scheduling.','Fresh all three mutants detected with healthy ordinary/explicit controls.'),
 row('Browser pre-script authority setup','Install independent Date/performance before widget initialization; real boot/render/loop/provider/storage consumer integration must be read back.',S(858,969),C(2982,3093),T('r0008-clock-harness.cjs',34,55),'Actual browser consumer current/next/countdown/date/cache/request identities move under wall steps; mutating captured state after boot or using SalahClock seek is not equivalent.','Fresh fixture is VM/recording DOM. Final-v49 explicit forward/backward native-clock seeks/live-return demonstrate a different control pathway, not injected device wall corrections.','unverified'),
 row('Browser required boundary/day/visibility matrix','Actual prayer boundary forward/reverse,completed day8 prefetch,held day7 response,backward day8 late reply,nextDay reclassification,hidden/show and explicit-rate/frozen modes require matched DOM/caches/slots/crops.',S(1129,1189),C(3253,3318),T('r0020-clock.cjs',18,75),'Each actual release point has correct selected/loaded day,current/next,countdown,cache writes and owner; no acquisition storm.','Source support is substantial; complete issue-specific native-browser transition/release matrix not established. Generic lifecycle/native-clock seek or source helper PASS cannot substitute.','unverified'),
 row('Visual regression controls','Retain readable325x530 card,opaque calendar moon,visible real motion,reduced-motion and offscreen pause on valid corrected scenes; no cloud hash as motion proof.',S(3394,3434),C(5423,5463),D('docs/real-sky/evidence/startup-cloud-20261007/final-v49/QUALIFICATION.json',1,12),'Corrected actual scenes remain readable/opaque and visibly alive where allowed; scopes native suspend separately.','General final-v49 visual/motion receipts remain broader owners. Matched corrected-clock output crop/native transition controls unverified here.','unverified'),
 row('Documentation obligation','Revise DESIGN universal one-formula description to one API/two authorities; explicitly clarify absent overrides wall clock and timeScale1 anchored preview.',S(858,867),D('DESIGN.md',138,143),D('DESIGN.md',318,320),'Design matches actual current-wall default and parameter-presence preview compatibility.','Source comments corrected; DESIGN:140 still universally says simBase+realElapsed*TIMESCALE, and parameter paragraph does not state the required ordinary-vs-explicit1 distinction.','unmet'),
 row('Scope/effects/closure','No new clock preference/provider/config/preset/installer/OS setting/framework or religious policy; final-tree independent caller review+browser evidence before manual closure.',S(858,969),C(2982,3093),D('docs/real-sky/INTEGRATION.md',79,90),'Preserve semantic-owner completed work and requested bounded correction scope; public source/readback and publication separate.','Read-only exact source review and fresh44 clock cases complete; docs/browser gaps prevent closure. No source/GitHub/OS changes performed.','unverified'),
 ],
 'gaps':['Explicit mandatory DESIGN one-API/two-authority and explicit1x compatibility update is inaccurate/absent.','Actual pre-script browser wall-correction consumer/day/cache/late-response/visibility/explicit-mode matrix and output crops remain unverified.'],
 'next':'Preserve direct-wall default, anchored explicit modes, strict invalid-simulation guards, backward-aware loop and real-elapsed prayer ownership/day classifier. Correct the narrow DESIGN formula/parameter paragraph. Complete a disposable actual-browser pre-script Date/performance fixture with deterministic accepted UTC records and deferred request releases. Record both prayer-boundary directions, forward/backward day adoption/cache/late classification/owner slots, hidden/show and explicit1/60/frozen controls; crop clock/prayer/date output and retain the three mutants. Keep native sleep/NTP and the adjacent weather cooldown probe outside this bounded claim unless independently admitted.',
 'checks':[{'purpose':'Actual browser device-wall correction consumer/day ownership proof','command':'No complete existing issue-specific browser wall-step driver was established. Prepare a disposable pre-script Date/performance driver for unchanged final index.html using the exact #32 synthetic UTC record and deferred day responses, then primary serial browser readback.','driverRequired':'Real boot/render/loop; +/-wall steps with fixed monotonic; current/next/countdown/date/cache/slots at every release; hidden/show; explicit1/60/frozen;325x530 crop.'}],
 'dependencies':['R0008 rejects invalid explicit inverse before clock/celestial use.','R0005 owns day matching/adoption/late reclassification and day-specific cooldown retirement; interface source is present.','R0003 owns operation slots/finally; R0006 real-elapsed prayer scheduling stays separate.','R0007 coherent elapsed countdown and R0009 reverse calendar selection consume current instant.'],
 'adjacentCounterexample':{'classification':'Contextual adjacent source counterexample; not automatically a new binding R0020/R0006 obligation. Linked R0006 detailed scope is prayer acquisition, not weather.','evidence':'weather-wall-step-probe.json','source':S(1355,1385),'consumer':C(3479,3509),'expected':'After failed weather attempt plus60000ms independent monotonic time, retry wrapper should reach a new acquisition if extending real-elapsed eligibility to weather.','observed':'Unchanged/+1h wall controls totalAttempts2; -1h wall case totalAttempts1 due Date.now-lastWxTry<60000. Controlled wrapper doubles; no network/browser/host-clock effect.','functionSha256':'0da1140e2c0546aae2514711137ac713d550afc6adb486a67456f54e536fca84'}}

# Final citation ranges were read and corrected against actual target lines,
# not inferred from older versions of the test files.
for index,(a,b) in enumerate([(60,77),(61,77),(28,77),(66,67),(61,62),(63,63),(65,65),(60,69),(12,77)]):
    SPEC[1]['rows'][index]['discriminator']=T('r0001-date-sinks.cjs',a,b)
SPEC[1]['rows'][10]['discriminator']=T('r0001-browser-fixture.cjs',1,127)
SPEC[8]['rows'][5]['deliveredConsumer']=C(5280,5356)
SPEC[9]['rows'][1]['discriminator']=T('r0009-date-selection.cjs',18,19)
SPEC[9]['rows'][2]['discriminator']=T('r0009-date-selection.cjs',20,35)
SPEC[10]['rows'][0]['discriminator']=T('r000a-markers.test.cjs',66,71)
SPEC[10]['rows'][1]['discriminator']=T('r000a-markers.test.cjs',57,65)
SPEC[10]['rows'][5]['discriminator']=T('r000a-markers.test.cjs',24,36)
SPEC[10]['rows'][8]['discriminator']=T('r000a-markers.test.cjs',76,107)

def tidy(s):
    if not isinstance(s,str): return s
    for before,after in {
      'Sol6.1':'Sol 6.1','source25':'source 25','selection22':'selection 22','disclosure16':'disclosure 16',
      'London2026':'London 2026','old18/17':'old 18/17','angle90':'angle 90','Fajr19.37':'Fajr 19.37',
      'Isha274.41':'Isha 274.41','and90min':'and 90 min','universal14':'universal 14','max40':'max=40',
      'suite13':'suite 13','source22':'source 22','source16':'source 16','fresh44':'fresh 44','Worker44':'Worker 44',
      'clock44':'clock 44','cases157':'cases 157','from19':'from 19','today19':'today 19','tomorrow20':'tomorrow 20',
      'UAQ20':'UAQ 20','day26':'day 26','day8':'day 8','day7':'day 7','Fajr12':'Fajr 12','Fajr18':'Fajr 18',
      'Isha17':'Isha 17','Madinah18.5':'Madinah 18.5','method3':'method 3','method4':'method 4','before17:':'before 17:',
      'After18:':'After 18:','exactly18:':'exactly 18:','NY2026':'NY 2026','New York2026':'New York 2026',
      'scale1':'scale 1','scale0':'scale 0','rate1':'rate 1','row325':'row 325','at19:':'at 19:',
      'with60000':'with 60000','plus60000':'plus 60000','after60000':'after 60000','failed60':'failed 60',
      'cooldown60':'cooldown 60','matrix22':'matrix 22','fixture22':'fixture 22','325x530':'325×530','330x534':'330×534',
      'Date.now-lastWxTry<60000':'Date.now() - lastWxTry < 60000',
      '0stars/0moon/0requests':'0 stars / 0 moon calls / 0 requests','pending0':'pending 0','pending1':'pending 1',
      'totalAttempts2':'totalAttempts=2','totalAttempts1':'totalAttempts=1','unavailableReason exact even prayerStale=false':'unavailableReason exact even when prayerStale=false',
      'Sunrise/Maghrib y104':'Sunrise/Maghrib y=104','Dhuhrx149.84':'Dhuhr x=149.84','unchanged44':'unchanged 44',
      'two-authority':'two-authority',
    }.items(): s=s.replace(before,after)
    s=re.sub(r'(?<![\w])([+\-]?\d+(?:\.\d+)?)(ms|px|min|h)\b',r'\1 \2',s)
    return s
for spec in SPEC.values():
    for r in spec['rows']:
        for field in ('contractReference','obligation','expected','observed'):r[field]=tidy(r[field])
    for field in ('scope','next'):spec[field]=tidy(spec[field])
    for field in ('gaps','dependencies'):spec[field]=[tidy(v) for v in spec[field]]
    for check in spec['checks']:
        for field,value in list(check.items()):check[field]=tidy(value)
    if 'adjacentCounterexample' in spec:
        for field,value in list(spec['adjacentCounterexample'].items()):
            if isinstance(value,str):spec['adjacentCounterexample'][field]=tidy(value)

fresh=read_json(OUT/'fresh-test-receipts.json')
configuration=read_json(AUDIT/'reviewer-model-settings.json')
configured_session=next(s for s in configuration['sessions'] if s['session']['agent_path']=='/root/rlgwo_b')
assert configured_session['turnConfigurations'] and all(t['model']=='gpt-6.1-sol' and t['effort']=='max' for t in configured_session['turnConfigurations'])
configuration_confirmation={'status':'CONFIRMED_LOCAL_CLIENT','confirmationKind':configuration['confirmationKind'],
 'sessionId':configured_session['session']['id'],'agentPath':'/root/rlgwo_b','recordedTurns':configured_session['turnConfigurations'],
 'receipt':'reviewer-model-settings.json','boundary':'Local recorded client turn_context and supported spawn configuration; no independent hardware/backend attestation.'}
release=read_json(AUDIT/'release.json')
assert release['status']=='DELIVERED_VERIFIED' and release['AUDIT_SHA']==SHA and release['tree']==TREE and release['runtime']==RUNTIME
distribution=read_json(AUDIT/'public-document-distribution.json')
assert len(distribution)==16 and all(r['status']==200 and r['match'] and r['expected']==r['observed'] for r in distribution)
native_receipt_path='docs/real-sky/evidence/startup-cloud-20261007/final-v49/runs/joined-v49-final-chromium-native-lifecycle/results.json'
native_receipt=read_json(REPO/native_receipt_path)
assert native_receipt['sourceSha256']==INDEX
native_cases={c['name']:c for c in native_receipt['cases']}
assert native_cases['native-prayer-calendar-clock']['passed'] and native_cases['native-prayer-calendar-clock']['assertions']==45
assert native_cases['wall-clock-and-reduced-motion']['passed'] and native_cases['wall-clock-and-reduced-motion']['assertions']==27
SPEC[9]['rows'][13]['observed']='Exact-final-root retained native-prayer-calendar-clock has45 assertions, zero page errors, actual before/at Maghrib, sky-pending countdown and midnight promotion; CE native click/Close also executed. Reuse is narrow: the mandatory unavailable/correction/convention/accessibility cases and matching public crops still require the primary prepared driver.'
SPEC[32]['rows'][11]['observed']='Retained exact-root wall-clock-and-reduced-motion installs controlled Date before real boot, retains independent browser performance.now, and checks actual model/host/sky UTC after +120000ms/-30000ms wall changes (27 assertions, zero page errors). This is valid narrow pre-script caller proof. Direct render/request calls within one day do not establish the complete scheduled loop/cache/day/release matrix.'
SPEC[32]['rows'][11]['partialEvidence']={'preInitializationDateAuthority':'satisfied by retained actual browser','independentPerformanceAuthority':'satisfied by native unchanged performance.now','actualModelHostSkyInstant':'satisfied for +120000ms/-30000ms direct-render controls','scheduledLoopCacheDayRequestReadback':'unverified in this specific case; see next obligation'}
SPEC[32]['rows'][13]['observed']='Retained exact-root wall-forward/backward full-renderer crops and full/reduced media controls exist locally; their public JSON readback is narrowly reusable. General final-v49 visual/motion receipts remain broader owners. Matched prayer-boundary/deferred-day corrected-clock output crops remain unverified.'
mutation=read_json(OUT/'r0009-date-mutations.cjs.log')
source_bytes=(REPO/'index.html').read_bytes()
assert hashlib.sha256(source_bytes).hexdigest()==INDEX
assert subprocess.check_output(['git','-C',str(REPO),'rev-parse',SHA+'^{tree}'],text=True).strip()==TREE
assert subprocess.check_output(['git','-C',str(REPO),'diff','--stat',SHA,'HEAD'],text=True).strip()==''
assert subprocess.check_output(['git','-C',str(REPO),'status','--short'],text=True).strip()==''

for number,spec in SPEC.items():
    packet=read_json(AUDIT/'issues'/f'{number:02}.json')
    assert hashlib.sha256(packet['issue']['body'].encode()).hexdigest()==packet['contract']['bodySha256']
    command=next(x for x in fresh['commands'] if x['test']==spec['suite'])
    assert command['exitCode']==0
    if number in (1,9,25):
        result=read_json(OUT/(spec['suite']+'.log'))
        assert result['sourceSha256']==INDEX and len(result['results'])==spec['count'] and all(x['status']=='PASS' for x in result['results'])
    else:
        log=read_text(OUT/(spec['suite']+'.log'))
        assert re.search(rf'# pass {spec["count"]}\s',log) and '# fail 0' in log
    for i,r in enumerate(spec['rows'],1):r['id']=f'{packet["contract"]["canonicalId"]}-O{i:02}'
    assessment={
      'schema':'rlgwo-delivered-issue-assessment/1','worker':'B','issueNumber':number,'canonicalId':packet['contract']['canonicalId'],'title':packet['issue']['title'],
      'issueUrl':packet['issue']['html_url'],'originalBodySha256':packet['contract']['bodySha256'],'originalUpdatedAt':packet['contract']['updatedAt'],
      'packetCapturedAtUtc':packet['capturedAtUtc'],'commentRevisions':packet['contract']['commentRevisions'],'amendments':[],
      'requestedConfiguration':{'model':'gpt-6.1-sol','reasoningEffort':'max'},
      'effectiveConfigurationConfirmation':configuration_confirmation,
      'target':{'commit':SHA,'tree':TREE,'runtimeSha256':RUNTIME,'rootIndexSha256':INDEX,'date':'2026-10-08'},
      'custody':{'sourceWorktree':str(REPO),'observedHead':fresh['sourceHead'],'clean':True,'targetTreeEqualsReviewedHead':True,'generatedOwner':'tools/build_native.py','authoredOwner':'src/native/index.html and src/native/config.js','sourceUnmodified':True,'publicDeliveryBaseline':{'status':release['status'],'verifiedAt':release['verifiedAt'],'pagesBuild':release['pagesBuild']['url'],'pagesCommit':release['pagesBuild']['commit'],'publicBrowserCases':release['publicBrowserCases'],'origin':'Primary release.json readback; no independently executed worker browser/public-write effect','publicDocumentDistribution':'public-document-distribution.json:16 raw/Pages responses HTTP200 and exact byte hashes'}},
      'scopeOfDone':'Current authored repair and delivered consumer traced; complete issue body and amendments read; independent source review and fresh targeted controls complete. No final closure or publication asserted.',
      'fullRequirementMatrix':spec['rows'],'commandsExecuted':[command],
      'freshExecution':{'nodeVersion':fresh['nodeVersion'],'os':fresh['os'],'caseCount':spec['count'],'failures':0,'expectedExit':0,'observedExit':0,'scope':spec['scope'],'receipt':spec['suite']+'.log'},
      'historicalReuse':{'kind':'Retained exact-root final-v49 source logs and narrowly mapped actual native browser cases; read here, not newly browser-executed by reviewer','basis':'For r0001/r0008/r0009/r0019/r0020, retained log sourceSha256 or SOURCE equals exact final rootIndexSha256 ff728552...; fresh tests independently reconfirm applicable source assertions. Final native-lifecycle sourceSha256 is also exact ff728552. Source equivalence is narrow, not host/input equivalence.','location':'docs/real-sky/evidence/startup-cloud-20261007/final-v49/logs/native/','nativeReceipt':D(native_receipt_path,15934,15939),'nativeCaseReuse':['native-prayer-calendar-clock:45 assertions; before/at Maghrib, midnight promotion, actual CE click/Close'] if number in (9,25) else ['wall-clock-and-reduced-motion:27 assertions; pre-script Date with independent performance.now, actual model/host/sky UTC under +120000ms/-30000ms direct-render steps'] if number==32 else [],'browserBoundary':'Mapped ordinary native/calendar or wall-step receipts are retained where applicable; they do not contain the complete required hostile/unavailable/correction/accessibility/scheduled-day matrices. Native calendar/wall PNGs are local h8 evidence; public JSON is not falsely described as already public PNG proof. No old native bundle hash is mistaken for a root-index hash.'},
      'negativeControls':{'suite':'Immutable tests linked per matrix; fresh corresponding in-memory/disposable mutants detected.','dateMutations':mutation['results'] if number in (9,25) else None,'health':'Actual non-empty prayer/date render and independent positive controls prevent empty/no-render false greens.','nativeBoundary':'Recording DOM does not establish browser event execution, native keyboard/touch/focus/overflow or pixels.'},
      'dependencies':spec['dependencies'],'gaps':spec['gaps'],'verdict':'LEAVE OPEN','proposedBoundedNextIncrement':spec['next'],'missingChecksRequested':spec['checks'],
      'ownerDecision':'No new owner decision needed for in-contract missing proof/narrow required docs. Any later production edit or external publication remains separately authorized by primary/user.',
      'legacyFailureDisposition':'Eight legacy native failures and four TODOs were inspected through the final qualification/runner scope. They map to retired synthetic-glint/pre-CP9 PBR comparisons or placeholder callbacks, not a blanket failure of these calendar/clock obligations. Unmet native issue-specific proofs remain independently unverified.',
      'reviewerVsPrimary':'Reviewer B proposal only, not yet reconciled/approved/posted/closed. Primary Astra challenges every row, establishes delivery baseline and controls GitHub effects.'}
    assessment['rollbackOrContainment']='This audit makes no production change. Preserve completed source/security/calendar/clock work; keep issues open while proof/docs gaps remain. A later authorized increment should roll back only its failed narrow test/docs/disclosure delta, never remove admission, encoding, gap/fold rejection or truthful unavailable output to make a gate pass.'
    if 'adjacentCounterexample' in spec: assessment['adjacentCounterexample']=spec['adjacentCounterexample']
    (OUT/f'{number:02}-assessment.json').write_text(json.dumps(assessment,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
    def mdref(ref):return f'[{ref["path"]}:{ref["start"]}–{ref["end"]}]({ref["url"]})'
    lines=[f'# RLGWO closure audit — {assessment["canonicalId"]} — REMAINS OPEN','',
      f'<!-- RLGWO-AUDIT:{SHA}:{assessment["canonicalId"]}:2026-10-08 -->','',
      f'**{assessment["title"]}**. Recommendation: **LEAVE OPEN**. The implementation has meaningful completed source work; the original contract still has the gaps below.','',
      f'Audit target `{SHA}`, tree `{TREE}`, runtime SHA-256 `{RUNTIME}`, delivered root `index.html` SHA-256 `{INDEX}`. Contract body SHA-256 `{assessment["originalBodySha256"]}`, last original revision `{assessment["originalUpdatedAt"]}`; captured issue discussion has no additional comment amendments. Audit date 2026-10-08.','',
      f'Authored ownership remains `src/native/`; root entry is generated by `tools/build_native.py`. Reviewed head `{fresh["sourceHead"]}` has the same tree as the audit merge and was clean. Prior native repairs are inherited work, not all credited to PR42. No production source or GitHub mutation was made by this reviewer.','',
      f'Fresh command: `{NODE} tests/{spec["suite"]}` on Windows, Node `{fresh["nodeVersion"]}`. Expected exit 0; observed exit 0, **{spec["count"]}/{spec["count"]} source cases passed**. {spec["scope"]}','']
    if number in (9,25):
        lines += ['Fresh additional command: `node tests/r0009-date-mutations.cjs index.html <isolated-worker-output>`; exit0. Both unmodified suites were healthy and eight independent mutants were detected, each retaining its named positive render. Fixture copies were confined to the reviewer output directory. These are correlated source guards, not eight independent visual reviews.','']
    lines += ['Mandatory obligation matrix (a source PASS is limited to the stated discriminator):','',
      '| Obligation / original section | Authored owner → delivered consumer | Discriminator | Expected → observed | Disposition |',
      '|---|---|---|---|---|']
    for r in spec['rows']:
        cell=lambda s:str(s).replace('|','\\|').replace('\n',' ')
        lines.append('| '+ ' | '.join(map(cell,[r['obligation']+' ('+r['contractReference']+')',mdref(r['authoredOwner'])+' → '+mdref(r['deliveredConsumer']),mdref(r['discriminator']),r['expected']+' → '+r['observed'],r['disposition'].upper()]))+' |')
    lines += ['','Retained final-v49 Node logs for date sinks, inverse, selector, disclosure and clock carry this same root SHA, so their source scope is relevant and is labeled historical reuse. The exact-root [native lifecycle receipt]('+D(native_receipt_path,15934,18325)['url']+') separately retains actual ordinary calendar before/at Maghrib and midnight promotion, CE click/Close, and the pre-script device-wall forward/backward caller controls. These are reused only for their mapped paths; they do not contain all missing hostile/unavailable/correction/native-accessibility/scheduled-day controls. Associated calendar/wall PNGs remain local h8 evidence, not public repo PNGs. The eight legacy glint/PBR comparison failures and four TODO placeholders are not promoted to PASS or treated as automatic blockers for unrelated obligations.','',
      'Actual interface dependencies: '+' '.join(spec['dependencies']),'',
      'Remaining gaps:','']+['- '+g for g in spec['gaps']]
    if 'adjacentCounterexample' in spec:
        a=spec['adjacentCounterexample']
        lines += ['','Adjacent finding, outside automatic closure scope: '+mdref(a['source'])+' uses wall time for the weather retry throttle. An isolated actual-wrapper probe after a completed failed acquisition observes two attempts after unchanged or +1h wall time, but only one after -1h wall correction with60000ms independent monotonic elapsed. Function hash `'+a['functionSha256']+'`; root hash remains above. Dependencies were controlled doubles, with no network/browser/OS-clock effect. Linked R0006 details prayer scheduling, so this weather defect is a contextual follow-up for primary scope reconciliation, not an invented mandatory new #32 requirement.','']
    lines += ['','## Next RLGWO increment required for closure','',spec['next'],'',
      'Acceptance/closure proof: satisfy every UNMET/UNVERIFIED row above on the exact final source/environment/input, retain required failing controls and independently reconcile actual consumer/pixels. Preserve the stated invariants; no new provider/calendar/clock preference or broad refactor is requested. If a proof fails, retain the failure and keep this issue open. Missing proof is not automatically a demonstrated runtime defect.','',
      'Requested serial checks:','']+['- '+c['purpose']+': `'+(c.get('preparationCommand') or c.get('command'))+'`. '+c['driverRequired'] for c in spec['checks']]
    lines += ['','Primary delivery baseline is DELIVERED_VERIFIED: exact audit merge/runtime, Pages build1270547036 and16 public root/V1 browser smoke cases; document raw/Pages hashes also match. This distribution/smoke is separate from the issue-specific controls still requested above.','',
      'This is reviewer B’s proposed assessment and comment, not yet primary-reconciled or posted. Primary Astra owns final challenge and publication approval. Requested routing is Sol6.1/max; local client recorded turn_context confirms gpt-6.1-sol and max for this reviewer session. That is a client configuration receipt, not independent hardware/backend attestation. Native sleep/NTP, full Safari/macOS compatibility and unrelated real-sky gate closure are outside this bounded evidence.','']
    (OUT/f'{number:02}-comment.md').write_text(tidy('\n'.join(lines)),encoding='utf-8')

summary={'schema':'rlgwo-worker-summary/1','worker':'B','target':SHA,'tree':TREE,'runtime':RUNTIME,'rootIndex':INDEX,
 'requestedConfiguration':{'model':'gpt-6.1-sol','reasoningEffort':'max'},'effectiveConfiguration':configuration_confirmation,
 'results':[{'issue':n,'canonicalId':read_json(AUDIT/'issues'/f'{n:02}.json')['contract']['canonicalId'],'verdict':'LEAVE OPEN','sourceCases':s['count'],'mandatoryObligations':len(s['rows']),'gaps':s['gaps'],'assessment':f'{n:02}-assessment.json','proposedComment':f'{n:02}-comment.md'} for n,s in SPEC.items()],
 'freshChecks':{'sourceSuites':6,'sourceCases':sum(s['count'] for s in SPEC.values()),'failures':0,'dateMutationRows':10,'independentDateMutantsDetected':8,'correlation':'The two mutation-harness healthy suite rows repeat selector/disclosure source cases; no independent-review or browser counts are inferred.'},
 'historicalReuse':'Final-v49 exact-root source logs and native calendar45/wall27 cases mapped narrowly; no complete issue-specific browser closure inferred from generalized PASS.',
 'publicDeliveryBaseline':{'status':release['status'],'verifiedAt':release['verifiedAt'],'pagesBuild':release['pagesBuild']['url'],'publicBrowserCases':release['publicBrowserCases'],'publicDocuments':16},
 'crossIssueDependencies':{str(n):s['dependencies'] for n,s in SPEC.items()},'missingChecksRequested':{str(n):s['checks'] for n,s in SPEC.items()},
 'adjacentCounterexample':SPEC[32]['adjacentCounterexample'],'effects':'Only workers/B created/modified; no source, generated consumers, Git state, public writes, browser, solver, build, host clock, clipboard or owner storage changed.',
 'publicationStatus':'PROPOSED_UNRECONCILED; primary owns delivery baseline and every publication/closure decision',
 'memoryUsage':'Memory registry lines76-94 informed lineage/configuration/proof-scope caution; all current source identities and test results were independently reverified.'}
(OUT/'summary.json').write_text(json.dumps(summary,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
print(json.dumps({'worker':'B','issues':list(SPEC),'sourceCases':157,'dateMutantsDetected':8,'assessments':6,'comments':6,'verdicts':'LEAVE OPEN','rootIndexSha256':INDEX},indent=2))
