"""Write reviewer E's bounded audit artifacts; never executes product/test code."""
import datetime
import hashlib
import json
import pathlib
import subprocess

ROOT = pathlib.Path(__file__).resolve().parent
AUDIT = ROOT.parents[1]
REPO = pathlib.Path('C:/Users/theis/.codex/worktrees/hotfix-startup-clouds/salah_widget')
OLD = pathlib.Path('C:/Users/theis/.codex/work-products/salah-rlgwo-execution-20261002/evidence/install')
SHA = '18ff14860ff41c084b1db5f396bb62aa9c22b1be'
TREE = '35208181eea714c17f5e77b2644e76434345db60'
RUNTIME = 'f443cf0820e6879dfa7c3ce857d6b2baf554b1fdd2f889433d22e2c532cec260'
INDEX = 'ff728552442f4bcce7f213a089bf01d4cf70ea8d74040bdd3323768ca453beee'
REVIEWED_NATIVE = 'b2dc8b36bfa2fe9290a0c337e784cf93594dd00e'
PSHASH = 'd4d0cd3efef8a1b22f66d4317e464cfe9af667db59b2bddb2f70ebf12a278215'
BASHHASH = '9c3fd523bbd77f3080097ddbd142b7e966795befd008daa36fbfb9f8f1ca1cee'

def git(*args):
    return subprocess.check_output(['git', *args], cwd=REPO)

def proof(path, start, end=None):
    end = end or start
    return {'path': path, 'start': start, 'end': end,
            'url': f'https://github.com/theislampill/salah_widget/blob/{SHA}/{path}#L{start}-L{end}'}

def row(key, obligation, status, owners, tests, expected, observed, basis='fresh source examination; historical execution only where explicitly named'):
    return dict(id=key, obligation=obligation, status=status, authored_owner_and_delivered_consumer=owners,
                discriminator=tests, expected=expected, observed=observed, evidence_basis=basis)

def sh(a,b=None): return proof('install.sh',a,b)
def ps(a,b=None): return proof('install.ps1',a,b)
def rd(a,b=None): return proof('README.md',a,b)
def ts(path,a,b=None): return proof('tests/'+path,a,b)
def native(path,a,b=None): return proof('src/native/'+path,a,b)
def delivered(path,a,b=None): return proof(path,a,b)

GEOMETRY = ('The supplied owner amendment permits a production 330x534 iframe around the 325x530 card. '
            'Only the older wrapper-size obligation is superseded; card size, geolocation scope, encoding and readability remain binding. '
            'The audited source currently uses 325x530 snippets. This review does not demand a geometry change for an unrelated installer/docs issue.')

M = {}
M[19] = [
 row('19-01','All five human inputs share a checked readable controlling-terminal FD3; prompts are stderr; structured record reads retain their data streams; close FD3 without interfering with staging cleanup.', 'satisfied', [sh(63,78),sh(180,189),sh(565,616),sh(703,705)], [ts('install-entry-bash.py',84,115),ts('install-entry-bash.py',187,199)], 'Actual pipe entry consumes terminal all/default/indices/source/store/fallback responses; source bytes never become answers.', 'Retained Bash5.2.21 actual PTY entry records eight healthy normal/NO_OPEN cases, correct later confirmation/source counts, and five pre-effect refusals. Every reachable human read in current source calls read_answer; source is byte-identical to receipt source.'),
 row('19-02','No terminal or EOF fails nonzero before installation effects; a successful empty terminal line may default to all/source1 and cannot count as installation proof.', 'satisfied', [sh(63,78),sh(569,590),sh(703,731)], [ts('install-entry-bash.py',149,151),ts('install-entry-bash.py',188,199)], 'No-terminal/EOF: nonzero, zero effects, unchanged subject, no staged success; empty PTY line: normal selected set.', 'Saved modern-Linux entry observations: no-terminal and EOF exit1/effects0; empty entry exit0 with28 stubbed/contained normal effects. Current manual completion wording remains pending.'),
 row('19-03','Normalize/validate selection before downloads; accept all or existing comma indices only; reject malformed/out-of-range tokens; deduplicate; refuse legacy; zero/legacy-only cannot claim staging.', 'satisfied', [sh(659,662),sh(703,749),sh(760,767)], [ts('install-entry-bash.py',149,174),ts('install-entry-bash.py',187,199)], 'all, empty, explicit, deduplicated1,1,3 work; 999/1,bad/legacy-only/no-target fail before effects.', 'Retained all/empty/1,2 and1,1,3 cases pass. Deduplicated legacy case records one metadata call and refusal; 999/1,bad/legacy-only exit1/effects0. Source separately validates leading/trailing/repeated commas and index membership.'),
 row('19-04','Replace both mapfile calls with current-shell read loops; reset arrays per config, guard zero-array nounset, and preserve zero-profile executable/data-directory fallback.', 'satisfied', [sh(349,384)], [ts('install-bash.py',57,78)], 'Two family loops, no mapfile dependency, guarded empty profile arrays, populated arrays remain in current shell.', 'Current source has two process-substitution read-r loops and explicit profile_count guards before array iteration; retained disabled-mapfile modern Bash control preserves two Chromium and one Firefox paths; actual Firefox zero/one producer control passes. This is implementation and modern-host evidence only.'),
 row('19-05','Complete native Apple Bash3.2 and modern-Bash detector matrix: both families, zero/one/multiple, spaces/Unicode/backslashes, unterminated final line, empty-array nounset; disclose newline-bearing path limitation.', 'unverified', [sh(261,271),sh(349,384),rd(49,76)], [ts('install-bash.py',57,78)], 'Actual /bin/bash --version plus complete named detector cases on macOS and modern Linux; documented retained newline format limit.', 'Native-applicability-2fafcbf explicitly records actual Apple host BLOCKED. Existing modern detector controls prove spaces/Unicode/unterminated final line and Firefox zero/one, but do not individually demonstrate the complete zero/one/multiple/backslash matrix. README does not disclose the newline-delimited profile limitation. Disabled mapfile is not Apple proof.'),
 row('19-06','Successful fresh and valid same-attempt cache downloads emit one newline-terminated absolute existing regular path; diagnostics stay stderr; failure emits no usable path; extraction/copy/open consume quoted unchanged bytes.', 'satisfied', [sh(41,43),sh(421,482),sh(584,615)], [ts('install-bash.py',38,55)], 'First/second same-owned-root calls return equal single paths, one asset fetch; invalid archive fails; status cannot pollute stdout.', 'Retained helper receipt passes exact two-line first/second identity, existing-path and one-fetch assertions; current helpers guard private roots, validate archive, and return only paths. The stdout mutant separately fails cached-path control.'),
 row('19-07','Private-cache interface amendment: one verified download root per attempt, legitimate within-attempt reuse, new root next invocation, no old shared cache/retained-bundle admission.', 'satisfied', [sh(155,172),sh(421,450)], [ts('install-bash.py',38,55),ts('install-bash.py',207,214)], 'No root allocation per helper; first/second same-attempt asset fetch once; roots differ across runs.', 'Retained controls and cross-UID owner caller preserve three local acquisitions for Chromium/Firefox/preset with zero repeat Chromium fetch; repeated-root control records different roots. Source performs initializer once after eligibility.'),
 row('19-08','Builder encoded malicious label/config roundtrip, SALAH_WIDGET_HASH at the Bash process, local mode omits coordinates, and geolocation/manual/embed contracts survive.', 'unverified', [native('builder.html',204,219),native('builder.html',377,390),native('config.js',154,183),delivered('builder.html',377,390)], [], 'Actual final builder malicious literal roundtrip and shell parse, local coordinate omission, unchanged permission scope.', 'Current source uses shared URLSearchParams serialization and assigns encoded hash to the receiving Bash process; authored/delivered builder and config blobs are identical. No final-target adversarial builder execution was performed or independently rebound here. Primary may provide an exact matching consumer receipt; source inspection is not that execution.'),
 row('19-09','README and builder explain normal terminal requirement and accurate reviewed-file route; preserve manual import, dashboard replacement and configured preset; disclose retired cross-run reuse.', 'unmet', [rd(49,76),native('builder.html',370,388),sh(63,78),sh(760,767)], [], 'Public usage describes readable controlling terminal, no EOF-default, retained manual boundary, valid same-attempt cache versus retired shared cache.', 'README retains curl|bash and Bash review-first/manual warning but omits the controlling-terminal requirement and cache compatibility disclosure. Builder source comment L372 points readers to offline/local instructions absent from README.'),
 row('19-10','Restore one stdin read, mapfile, and cache status stdout as separate discriminating parse-valid mutants; preserve RED evidence and do not credit malformed controls.', 'satisfied', [ts('install-mutations.py',15,33)], [ts('install-entry-bash.py',149,174),ts('install-bash.py',38,70)], 'Each targeted mutant parses and fails its intended input/host/path gate separately.', 'Retained bash-mutations-archived-source records syntaxExit0/fixtureExit1 for all three; cached stdout, disabled-mapfile detector, and eight normal PTY cases fail respectively. No host equivalence inferred.'),
 row('19-11','Geometry/permission invariant and production wrapper amendment apply without broad runtime or staging redesign.', 'validly superseded', [native('builder.html',217,219),rd(32,39)], [], 'Preserve325x530 card and allowed geolocation; honor later330x534 production wrapper policy.', GEOMETRY),
 row('19-12','Final exact-tree independent review, actual minimum-host/entry qualification, and public raw-script/generated-command readback before distribution/closure claims.', 'unverified', [sh(1,16),native('builder.html',377,390),rd(57,76)], [ts('install-entry-bash.py',84,115)], 'Complete native and capability matrix plus independently reconciled public source/command identity.', 'Current-source review and historical Linux reuse are available; required Apple floor remains absent. Primary139-file receipt contains delivered builder, but no install.sh or rootREADME readback; source/native receipts do not prove those distributed bytes. Reviewer E has not published or closed anything.'),
]
M[20] = [
 row('20-01','Keep #requires5.1 and exact distributed-file encoding policy; zero native ParseFile errors on actual Windows PowerShell5.1 and supported7; explicitUTF8 explains but does not replace file gate.', 'satisfied', [ps(1,27),ps(529,537)], [ts('install-powershell.ps1',9,20)], 'Exact sourceASCII, native5.1/7 ParseFile0, UTF8control0; record source hash and native versions.', 'Current PS blob fdcf3e86 and SHA256d4d0cd3e match final receipts. Native5.1.26100.9444/7.6.6 each record fileErrors0, UTF8control PASS and ASCII PASS. Source byte scan/hash was freshly read; these are reused native executions.'),
 row('20-02','Remove selector pipeline commas while preserving stable per-tier source order, flattening and exactly one original selected object; diagnostics do not enter success pipeline.', 'satisfied', [ps(317,343)], [ts('install-powershell.ps1',27,42)], 'Exactly one original object with exact name/URL; specific Chromium tier beats earlier generic fallback; same-tier reversals preserve order.', 'Final18-case receipts both pass six positives. Tests assert one object, exactURL and ReferenceEquals original object, including both Chromium within-tier orders. Current selector has statement-separated pipelines.'),
 row('20-03','Chromium tiers: chrom(e|ium) ZIP then tabliss*.zip; exclude firefox/safari/source; Firefox tiers: signed/firefoxXPI then genericXPI then firefoxZIP; exclude unsigned/source.', 'satisfied', [ps(323,340)], [ts('install-powershell.ps1',27,55)], 'Valid preferred names win; unsuitable-only/empty/unsupported reject with exact reasons.', 'Both native final receipts pass exact tier/exclusion/reason assertions. Retained generic.xpi and tabliss-firefox.zip positives characterize filename fallback only; no signature or browser-installability claim is made.'),
 row('20-04','Real Install-TablissNG receives exact selected object and path; Chromium reaches expansion, Firefox manual path; valid assets cannot hide failure through store fallback; preserve spaces/Unicode.', 'satisfied', [ps(444,505)], [ts('install-powershell.ps1',58,83)], 'One exact object/URL download, one correct copy/manager/manual prompt each family; Unicode/spaced path unchanged; no store fallback.', 'Both final native suites pass actual Chromium/Firefox caller rows. Assertions capture original objectidentity/exactURL, extraction equality, copy count/path, manager count/URL and manual prompt count. Fixture path includes a space and Arabic character.'),
 row('20-05','Empty/no-match/unsupported/metadata failure remain defined errors; actual caller may provide honest manual fallback with no accidental asset effects, never installed success.', 'satisfied', [ps(321,340),ps(500,505),ps(610,612)], [ts('install-powershell.ps1',44,55),ts('install-powershell.ps1',85,97)], 'Exact rejection reason; metadata/auth fixture remains labeled; actual catch fallback zero download/extract/copy and exact ordered warn/store/prompt.', 'Both final native suites pass empty, unsuitable and metadata actual-caller fallback controls; unsupported safari helper rejects. Exact normal completion says manual browser installation/import remain pending.'),
 row('20-06','Encoding and reinserted-comma controls independently fail the native file/selector gate; do not credit malformed syntax controls or PS7 masking.', 'satisfied', [ts('install-powershell.ps1',9,20),ts('install-mutations.py',47,61)], [], 'BOMless nonASCII restoration gives PS5.1 fileErrors4 while explicitUTF8 stays0; parse-valid comma restoration fails binding/caller gate.', 'Retained encoding source33b1d359 yields fileErrors4 with UTF8/selector positives intact. Corrected comma sourcec6af27d9 parses0 on native5.1/7 and fails six Chromium-sensitive rows while Firefox positives remain green. Earlier malformed-control receipts are expressly excluded.'),
 row('20-07','Actual native exact-file -File entry uses disposable complete interception before top level; separately prove readiness, post-state and positive consumers.', 'satisfied', [ps(521,614)], [ts('install-entry-native.py',10,55),ts('install-entry-native.py',63,151)], 'Native powershell.exe/pwsh.exe directly receive exactsource -File; private readiness loads; no owner profiles; both normal/manual consumers work.', 'Direct-native-final sourcehash equals auditedPS.24cases (12perhost) pass. Normal21 and NoOpen17 contained effects each host include exact metadata/download/extract/copy/manager/newtab/config/manual arguments; ten preview/refusal controls each have unchanged subject and0effects. Host startup caches are separate; bad-option readinessfalse is correctly refusal-only.'),
 row('20-08','README response-string route and script review/download/-File route name the exact supported host and retain manual boundary; builder changes only if invocation changes.', 'unmet', [rd(49,76),ps(5,16),native('builder.html',370,388)], [], 'Public usage explains WindowsPowerShell5.1 versus pwsh7 and quoted reviewed/downloaded -File path plus manual/install distinction.', 'Script keeps #requires5.1 and -File usage; README L61-L64 says only WindowsPowerShell/irm|iex and its review-first L72-L73 covers Bash only. Previously reviewed b44cf726 docs supplied exact native floor/Windows file route; those mandatory public instructions are absent from deliveredREADME. Encoded builder Windows command itself remains correct.'),
 row('20-09','Preserve encoded configuration, manual extension/import/dashboard boundary and permission/card geometry; do not silently change genericXPI/FirefoxZIP policy.', 'satisfied', [ps(383,441),native('builder.html',204,219),native('builder.html',377,388),rd(66,76)], [ts('install-entry-native.py',125,132)], 'Exact configured preset at normal consumers, geolocation allowance unchanged, manual disclaimer retained, original filename fallback policy unchanged.', 'Direct-native positives assert exact #lat=24.47&lon=39.61&method=4 preset. Current builder serializer/preset/script/manual warnings remain; genericXPI/ZIP selection is explicitly limited to filename behavior. Geometry amendment is recorded separately, without claiming browser installation.'),
 row('20-10','Production wrapper amendment supersedes only former outer iframe-size obligation.', 'validly superseded', [native('builder.html',217,219)], [], 'Owner330x534 outer wrapper policy with325x530 card/permissions retained.', GEOMETRY),
 row('20-11','Qualified Windows interfaces must stay joined with #22 guards; no whole-issue dependency on Bash/macOS or unrelated N001/N002/N003.', 'satisfied', [ps(304,346),ps(540,584)], [ts('install-powershell.ps1',1,101),ts('install-entry-native.py',100,151)], 'Current guards do not reintroduce encoding/binding or mask normal positive; #22Windows cells share identicalsource.', 'Current source/fixtures equal reviewed objects; bounded Windows native cells remain qualified. Apple gaps of otherissues and scientificDAG dispositions are not applied as blanket #20 blockers.'),
 row('20-12','Distribution claim additionally binds authorized raw-script bytes and generated Windows command/readback; final integrated independent review and evidence must precede closure.', 'unverified', [ps(1,27),native('builder.html',377,390),rd(57,76)], [], 'Current main rawinstall.ps1 hash matches exact PS parsed source; actual generatedcommand matches public builder; primary reconciles before posting.', 'Primary public-runtime receipt proves Pagesbuilder bytes, not rawinstall.ps1/rootREADME. No current rawscript readback was acquired by E. Local/historicalnativefile identity alone is not public distribution proof; missing README remains a concrete completion gap even after readback.'),
]
M[21] = [
 row('21-01','Before any effect, validate platform/input/eligible targets and create fresh private scratch plus retained HOME bundle; no eager predictable root, fallback or automatic old-cache admission.', 'satisfied', [sh(35,38),sh(155,172),sh(703,732)], [ts('install-bash.py',207,223),ts('install-entry-bash.py',149,162)], 'Fresh owned0700 roots once per attempt after eligibility; normal scratchTMPDIR, retainedHOME; separate lifetime.', 'Unchanged source allocates checked mktemp roots only after terminal/selection. Retained Linux controls show cross-runfreshness, rejected unsafeparents and scratch-versusretained behavior. No predictable-tree reuse is present.'),
 row('21-02','Verify every supplied parent/ancestor physically and with native stat/id/-O/-L; owned non-group/world-writable HOME; trusted temporary parent or root-owned sticky/tmp; unknown mount fails closed.', 'satisfied', [sh(80,129),sh(155,167)], [ts('install-bash.py',131,140),ts('install-bash.py',216,223)], 'Reject symlink/writable/noncanonical/foreign boundaries; nativeGNUstat identifies UID/mode/device/inode on Linux.', 'Current code checks every component, physical pwd, owner/mode and root identity. Retained nativeWSL2 /tmp filesystem controls reject symlink/writable parents. The existing /tmp wrong-owner-home case combines wrongowner/writable factors; standaloneforeign-owner admission is a separate unverified row.'),
 row('21-03','Native Apple/macOS ownership branch must qualify BSDstat/mktemp/physicalHOME/TMPDIR and minimumBash behavior with actual host, not GNUstat/platform mocks.', 'unverified', [sh(80,172)], [], 'Actual macOS /bin/bash3.2 and BSDstat/mktemp with nativefilesystem root/guard/write/cleanup/retention controls.', 'Retained native-applicability explicitly records AppleBLOCKED. No Apple execution receipt was found in the bounded installer evidence. Linux and PLATFORM=mac dryhelper mock do not satisfy this branch.'),
 row('21-04','Fresh roots own UID0700 and exact identity; output parent must be inside component boundary; reject empty/dot/dotdot/separators/symlinked ancestors and nonregular output before writes/extraction/deletion.', 'satisfied', [sh(118,153),sh(421,449),sh(467,493),sh(533,560)], [ts('install-bash.py',142,156),ts('install-bash.py',193,205)], 'Outside sentinel unchanged and no writes for symlink leaf/parent,prefixlookalike, traversal,dotleaf; identitychanged scratch not deleted.', 'Retained nativehelper controls pass all five named confinement cases, changed-identitycleanup and actual healthy output. Source guard uses root/* component boundary and verifies physical parent before each caller.'),
 row('21-05','Isolated wrongUID retained-parent rejection must discriminate ownership independently of group/world writability.', 'unverified', [sh(99,114)], [ts('install-bash.py',131,140)], 'A reachable non-writable foreignUID HOME fails the real initializer before staging; a sameUID equivalent succeeds.', 'Existing wrong-owner-home uses root-owned sticky/tmp; read-only review explicitly says it combines wrongowner and writablemode. DistinctUID peerDAC below proves root isolation, not isolatedforeign-parent initializer admission. Need a nativefixture for this named matrix cell.'),
 row('21-06','Exact hostile old preset symlink preserves victim and old symlink while normal configuredJSON output is successfully staged only in new ownedbundle.', 'satisfied', [sh(155,172),sh(533,562)], [ts('install-bash.py',80,92)], 'Unchanged sentinel/oldsymlink plus regularretainedJSON exact #lat=24.47&lon=39.61&method=4 and0700root.', 'Retained helpercanary and configuredpositive pass on source9c3fd523. Source uses exclusiveownedpartial file/JSONvalidation/finalmv. Oldpredictable tree is never adopted.'),
 row('21-07','All asset/preset/write consumers acquire freshowned partial, validate then expose artifact; preserve literalencodedconfig; reject malformed/emptyarchive or badpreset and emit no usablepath.', 'satisfied', [sh(421,562)], [ts('install-bash.py',38,55),ts('install-bash.py',158,191),ts('install-bash.py',225,239)], 'Normalcache/newasset valid; badZIP/badJSON nonzero/noartifact; correctJSON exactconfig survives.', 'Retained helpercontrols pass cache/asset/presetpositives, malformedarchive and presetfailure. Source rechecks ownership around acquisition andpublishing. This is validation/confinement, not signature/updateauthentication.'),
 row('21-08','Archive preflight must reject absolute/parent/backslash/link/special/duplicate members before extraction; safe nestedmanifest returns existingin-rootdirectory; use newemptychild.', 'satisfied', [sh(484,530)], [ts('install-bash.py',158,191)], 'Unsafearchive cannot touch outsidecanary or earlierfirstmarker; safeUnicode/spacesnestedmanifest survivesexit/freshconsumer.', 'Retainedarchive controls pass traversal/absolute/backslash/symlink/malformed/no-manifest/safe; adversarialfirstmarker checks preflight ordering. Source also explicitly rejects special and duplicate members, creates newchild andexclusivefiles. No unzip-success confinement assertion is substituted.'),
 row('21-09','Within-attempt cache reuse shares oneverifiedDOWNLOAD_ROOT and identicalvalidatedpath without duplicatefetch; nextinvocation gets freshscratch/retainedroots and never trusts oldsharedor retainedmanualbundle.', 'satisfied', [sh(155,172),sh(421,450)], [ts('install-bash.py',38,55),ts('install-bash.py',207,214)], 'Two calls fetchonce/samepath; two runs differentroots; oldhostilecache untouched.', 'Retainedhelper and separatepredictable-rootmutant establish withinattemptreuse andcross-runfreshness. CrossUIDsourcecaller records only3localdownloads (Chromium/Firefox/preset) withsameAttemptCacheHitDiagnostic=true.'),
 row('21-10','Normalexit, preset/extractionfailure and interrupt retain manualor explicitlypartialbundle; cleanup only ownunchangedscratch; fdcleanup/traps do not delete retainedassets.', 'satisfied', [sh(174,189),sh(484,530),sh(601,615),sh(760,767)], [ts('install-bash.py',193,239),ts('install-entry-bash.py',157,173)], 'Scratchremovedonlyifidentitymatches; completed/partialretainedbundle survives; TERM143; changedscratchcanary retained.', 'Retained helper/entry records match thesecontrols. Source EXIT/INT/TERM traps onlyscratchcleanup; currentmanualpromptnever grantscleanupauthority. TERM and failedpreset retainbundlewithpartialwarning; extractionfailure hasno usablepath and retains itsnewownedchild.'),
 row('21-11','Filesystemlifetime proof uses actual completedunpackedpath/manifest aftersourceexit and freshconsumer/restart, not printedpathname or realbrowserinstallclaim.', 'satisfied', [sh(484,531),sh(174,189)], [ts('install-bash.py',179,185)], 'Manifest/payload/XPI/preset remainreadable byfreshownedconsumer afterownerexit; distinguish that fromlaterpresentliveness/reboot/browser.', 'Retained nativecrossUIDownerexit0 removes scratch; freshUID1000consumer exit0 confirms exactretainedbytes/modes/identity andvalidpreset/manifest/XPI. Laterqualifiedreadback reports fixtureExists=false; causeunknown. Credit is recorded exit+freshconsumer only, nevercurrentavailability orOSrebootproof.'),
 row('21-12','NativeLinux distinctfixtureUID filesystempermissions and relevantpositivecontrols must support crossuserboundary; WSL/DrvFS primitivealone is insufficient; sameUIDadversary remainsoutsideguarantee.', 'satisfied', [sh(80,153),sh(155,172)], [], 'Actual source0700roots onnativeLinuxfilesystem, reachableparents, peerUIDdifferent/nocaps; deniedread/write/link; positivepeerfile/link works.', 'Retained crossuid-nonlogin/result: WSL2Linuxkernel6.6.87.2, Bash5.2.21, native/tmp ext2/ext3, UID1000/65534 with emptygroups/zeroactorcapabilities;49operations=30EACCES13+19allowedcontrols, parentslist/rootlstatsucceed, bytesunchanged/foreignentriesabsent. This supersedes earlier failedlogin only; noDrvFS/macOS/sameUIDequivalence is inferred.'),
 row('21-13','Dry-run integration creates/changes/copies/downloads/extracts/cleans neitherroot; previewcannotreturn existing-artifactclaims.', 'satisfied', [sh(155,177),sh(421,485),sh(533,566),sh(678,700)], [ts('install-bash.py',94,129),ts('install-entry-bash.py',126,138)], 'Earlyofflineentry beforeinitializer, zeroeffects/post-statechanges, helpersnopath, cleanupguarded.', 'Retained Linuxtenpreview/refusal cases records0effects/unchangedsubjects, plushelperguards. NativeApplewholeentry remainsseparateunverifiedplatformobligation under#22.'),
 row('21-14','Predictableroot/linkadmission/retainedEXITdeletionmutants each fail itsfreshness/confinement/lifetimecontrol.', 'satisfied', [ts('install-mutations.py',15,33)], [ts('install-bash.py',80,92),ts('install-bash.py',193,214)], 'Parsevalidmutants fail matchingcontrol whilehealthycontrol passes.', 'EightBashmutationreceipt includes symlink-admission failureatwriteconfinement andretained-deletion failuresathealthyoutput/safearchive/lifetime; separate predictable-root-mutant receipt observes same scratchpathacrossruns despitehealthyprocesses. No malformed/controlbootstrapfailure iscredited.'),
 row('21-15','README and manualconsumers disclose retainedHOMEbundlelifetime, keepunpackedwhileinstalled, optionalmanualpreset/XPIremoval, safepartialretention and retiredcross-runsharedcache.', 'unmet', [rd(49,76),sh(601,615),sh(760,767)], [], 'Accuratepublicretention/cacheinstructions agreewithsource and do notpromoteEnter/filesintoinstalled.', 'Scriptinstructionsarecorrect; deliveredREADME lacks allbundle/cachelifetime paragraphs previouslyreviewed inb44cf726. Requiredpubliccapabilitydescription remainsunfinished.'),
 row('21-16','Preserve encodedconfig/manualdashboardwarning/card/permissions and keepPowerShellstagingoutsidethisBashwitness; wrapperamendmentonly.', 'validly superseded', [sh(533,562),sh(636,640),native('builder.html',217,219),rd(70,76)], [], 'ActualBashstagingfixdoesnotassertWindowsownership orbrowserinstallation; honorwrapperamendment.', GEOMETRY+' Manualconfig/dashboardwarning survives in source; noWindowssecurityclaim isintroduced.'),
 row('21-17','Independentfinal-tree securityreview, completeplatform/nativeconfinement/lifetimecontrols and authorizeddistributedscript/instructionsreadback beforeclaimingpublicclosure.', 'unverified', [sh(1,16),rd(49,76)], [], 'Exacttargetsource+interfaces review, mandatorynativeMac/isolatedownershipcontrols anddistributedbyte/publicusageidentity.', 'E rebindssource andreadsnativecontrols ratherthanrerunning; Apple andisolatedforeignparent cells missing. PrimaryPagesreceipt excludesinstall.sh/rootREADME. Publication/closure remainprimary-ownedandunperformed.'),
]
M[22] = [
 row('22-01','Validateoptions/platform beforeeffects; previewonlyreadslocaldiscovery and exitsbeforeterminal/staging/installloop, refuseslegacy andzeroeligible, prints unresolvedask/remote/version/path ratherthan artifacts.', 'satisfied', [sh(52,61),sh(678,703),ps(18,27),ps(540,584)], [ts('install-entry-bash.py',126,138),ts('install-entry-native.py',133,149)], 'No terminal/confirmation orstage; eligibleplannedtargets only; refusalnonzero/nochangessuccess; askstaysunresolved.', 'Retained Linuxtenofflinecases and Windows10dry/refusalcasesperhost show0effects/unchangedsubjects; askprintsunresolved. Current earlybranches returnbeforeacquire_terminal/Initialize-Staging. Knownremoteinfoisnotfabricated.'),
 row('22-02','Offline meansnometadata/provider/download/DNSavailabilitytests; cachedmetadata cannotgrantpreviewauthority; absentnetworkfacts explicitlyunresolved.', 'satisfied', [sh(386,388),sh(421,423),ps(303,318),ps(345,346)], [ts('install-entry-bash.py',55,72),ts('install-powershell-guards.ps1',14,44)], 'Zeroactualmetadata/downloadboundarycalls underpreview; cachehelperfailsbeforecachedmetadata/pathreturn.', 'Retained guards18? Windowsguardssuitesare10/10each, cachedmetadataguardno usablevalue/effects; wholeentrycached/sourcecases0effects. Current guardprecedesmetadata-cachelookup; capturedsourcehasnoundocumentedpreviewnetworkcall.'),
 row('22-03','Guard everyalternate effectsite: mkdir/chmod/copy/write/removal/extraction/clipboard/open/process/cleanup; previewcopyreturnsfalse andneverclaimsCopied.', 'satisfied', [sh(155,177),sh(202,241),sh(421,566),ps(44,46),ps(65,93),ps(345,418)], [ts('install-bash.py',94,129),ts('install-powershell-guards.ps1',25,46)], 'Nospyeffects/sentinelchanges evenhelpercalls; suppressedcopyfalse; cleanupalsosuppressed.', 'Retained Bashhelperguards andWindows10/10eachguardcases pass, clipboardfalse andcachedsentinelsunchanged. Sourceguardspersistsbeforecache/effects. AlternateopenwithNoOpenmayprintmanualURLbutdoesnotlaunchprocess.'),
 row('22-04','Dryartifacthelpers returnnousablepath/no pretendexistingfile; callerdoesnotextract/copy/storefallback; normalhelperexistingpathcontractretained.', 'satisfied', [sh(421,485),sh(533,566),ps(345,364),ps(383,418),ps(444,445)], [ts('install-bash.py',94,129),ts('install-powershell-guards.ps1',25,44)], 'Guardeddownload/preset/extract/install/import are suppressed; nounresolvedartifactflows intorealconsumer.', 'SavedWindowsguards show null/false/nousablepath withnoeffects; Bashhelperguard requiresemptyartifactstdout. Entryprintsplanitself andbypassesartifacthelpers.'),
 row('22-05','FreshGitHubChromium/Firefox,cachedZIP/XPI/preset/unpackedmetadata,store,ask,fallback,alreadyinstalled,missingpreset,mixed/legacy/zero/malformedbranches allkeeppreviewboundary.', 'satisfied', [sh(678,700),ps(540,560)], [ts('install-entry-bash.py',20,78),ts('install-entry-bash.py',182,186),ts('install-entry-native.py',76,103),ts('install-entry-native.py',147,149)], 'Allnamedofflinepathsnomutations; preexistingmarkersunchanged; fallbackcannotopenorwaitafterinstalled.', 'Retained wholeentrymatricescoverfresh/cached/store/ask/installed/mixed/legacy/none/missingpreset/badoption. Sourceearlyreturnmakesmetadataerror/fallbackunreachableinpreview; separatealternatehelperguardsprove actualInstallguardwithask/fallbacksuppressed. No claimeachnetworkfailurewasactuallyrequestedoffline.'),
 row('22-06','Snapshotfilesystemnames/modes/content includingpreexistingcached/unpacked/presetsentinels; logsharness-createdoutside subject; networkdenied; missinglogaloneisnotnoeffectproof.', 'satisfied', [ts('install-entry-bash.py',13,18),ts('install-entry-bash.py',36,41),ts('install-entry-bash.py',123,138),ts('install-entry-native.py',60,112)], [], 'Subjectbefore/afteridenticaland0effectcalls; poststatecatchesdirectwrites; noproprietaryprofiles/clipboard/browser/network.', 'Retained tenLinuxpreviewcases andWindowsdrycasesrecords bothsnapshotUnchanged=true and0effects; logs/readinessliveoutside subject. NativeCLRstartupcaches recordedseparately. Thisqualifiesinstaller-effectswithincontainedfixture, notzeroOSstartupactivity.'),
 row('22-07','NormalpositiveandNO_OPEN/NoOpen-offline distinction retainexactnormaldownload/staging/config/clipboard/manualconsumers; avoiddisablinginstallationglobally.', 'satisfied', [sh(202,224),ps(65,83)], [ts('install-entry-bash.py',152,174),ts('install-entry-native.py',115,132)], 'Non-drysourcepositivesreachactualspies/configuredassets; NoOpenremovesopensonly.', 'Retained Linuxnormal28effects versusNO_OPEN24; Windowsnormal21versusNoOpen17foreachhost. Exactconfiguredpreset/assets/copy/metadata/extraction/managernewtab/manualoraclespass; nochanges-to-normalclaimbeyondthesecontainedconsumers.'),
 row('22-08','Targetedeagerinit/cacheearlyreturn/previewcopy/EXITcleanupmutants eachdiscriminate relevantbranch/sentinel whilepositivecontrolremainshealthy.', 'satisfied', [ts('install-mutations.py',15,33),ts('install-mutations.py',41,61)], [ts('install-entry-native.py',105,142)], 'Eachparsevalidmutantfailsintendednospy/nochangeoracle; cachemutantrequirespreexistingcache; bootstrapfailureexcluded.', 'Retained eightBash andsixWindowsmutationreceiptsaresourcebound. Genuine direct-native eager/copy controls reject16drycasesacrossbothhosts whileallfournormal/NoOpenpositives remainPASS. Eager filesystemmutation andclipboard-onlymutationaredistinguished.'),
 row('22-09','MandatoryactualAppleBash3.2/macOSandmodernLinuxwholeentry plus actualPS5.1/supported7exact-fileentry afterlaunchprerequisites.', 'unverified', [sh(52,57),sh(678,731),ps(16),ps(540,584)], [ts('install-entry-bash.py',84,115),ts('install-entry-native.py',100,151)], 'Completeplatform-specificpreview/positive/refusal/cachematrix on actualhosts; noplatformemulation.', 'ModernLinux23cases andWindows24directcases retainedonexactsource, #20nativefloorqualified. ActualApple/macOSmatrixexplicitlyBLOCKED; GNUstat/disabledmapfile/PLATFORM=mac helperisnotthisevidence. #19/#21requiredMacinterfacesremainunqualified.'),
 row('22-10','Joinprivatestaging/lifetimes serially: dryrunnevercallsinitializer/chmod/adoptsoldcacheorcleanup; #19humaninputonlynormalexecution; #20guardskeepexactencoding/selector.', 'satisfied', [sh(155,177),sh(678,731),ps(44,46),ps(303,346),ps(540,584)], [ts('install-powershell-guards.ps1',25,46)], 'Onecomposedsourcecarriesbothentry/helper/stagingguards andpreservesnormalinput/pathinterfaces.', 'DeliveredBash/PSandinstallerfixturesmatchreviewednativeobjects; sourceearlyreturnprecedesnormalterm/stagingandcleanupguard. Interfacesareassessedbycurrentconsumers ratherthanissueclosedstate; Macqualificationnotwaived.'),
 row('22-11','Completionwordinghonest: would/unresolved/previewonly onlyaftercontrols; noeligibleorselectorerrorcannotbeinstalled; normalstaged/manualbrowserboundarydistinct.', 'satisfied', [sh(678,700),sh(760,767),ps(540,560),ps(610,612)], [ts('install-entry-bash.py',133,138),ts('install-entry-native.py',132,142)], 'No installedclaim; replacementwarning visible; noeligible/refusalnonzero; previewexplicitoffline.', 'Currentsourceprintsplannedwould/unresolvedwithreplacementwarningandmanualpendingnormalcompletion. Retainedfixturesasserttheseexactmessagesalongwithpoststate; noactualbrowserinstallisclaimed.'),
 row('22-12','BothscriptusageandREADME/builderwherepreviewisexposedstatethesameoffline/noeffect/noartifact/nopromptpolicy andreviewedinvocation; withdrawclaimtogetherratherthanrename mostlypreview.', 'unmet', [sh(5,14),ps(5,14),rd(49,76),native('builder.html',370,372)], [], 'PublicREADMEdescribesDRY_RUN=1/-DryRun, exclusions, unresolvedfacts/localdiscovery,nativehostlimits, andNoOpenonlyopens distinction.', 'Bothscriptheadersaccuratelydescribeofflinepreview; deliveredREADMEcontainsneitherDRY_RUN nor-DryRun/offline/lifetime instructions ininstallsection. BuildercommentL372referstoofflineinstructionsnotpresent. Preservepublicnormalcommands; addonlythemissingaccurateusageprose.'),
 row('22-13','Preservepreset/configencoding/manualdashboard/permissions/cardgeometry andlaterouterwrapperpolicy.', 'validly superseded', [native('builder.html',204,219),rd(66,76),sh(550,562),ps(395,441)], [], 'Originalconfiguration/manualpermissioncontracts; amended330x534outerwrapper,325x530card.', GEOMETRY+' Nativecontrollednormalconfiguredpreset isretained; thisissueauthorizesnoUI/networkpolicychange.'),
 row('22-14','Independentfinalintegratedeffectsreviewandrawscript/usagepublicreadback onbothplatforms beforedistribution/closure.', 'unverified', [sh(1,16),ps(1,27),rd(49,76),native('builder.html',377,390)], [], 'ReconcileexacttreewithallmandatorynativeplatformcellsandpublicBash/Windowsrawscriptusageidentity.', 'E source/receiptreviewproves narrowreuse; primaryPages139hashreceiptcontainsbuilderonlyamongtheseusageowners. Publicrawinstall.sh/install.ps1/rootREADMEabsentfromthatreceipt; noEinstaller/browser/GitHubexecution. AppleandREADMEgapsremainafteranyreadback.'),
]
M[27] = [
 row('27-01','READMEintroduction/tableandbuildernotediscloseexternalservices/localpersistenceisnotlocalcomputation; noblankettracking/serverretentionclaim substitutesforrecipients.', 'unmet', [rd(7,8),rd(121,140),native('builder.html',192),delivered('builder.html',192)], [ts('rlgwo-docs-contract.cjs',278,289)], 'READMEcompletecompactrecipient/fieldtable; buildercorrectshortsummary/detailanchor; unsupportedblanketwordingremoved.', 'Deliveredbuildernoteiscompleteandauthored/rootblobidentical. READMEprivacyisoldGeoJS/ipinfo/geolocation/storageonly, missingNominatim/Zippopotam/BigDataCloudandtable; L126retainsblanket does no tracking/stores nothing on any server andL7 no tracking.'),
 row('27-02','Coarsedetectiontriggers andGeoJS->ipinfofallback/connectionIP are described; no typedquery/locationparameters; devicetimezoneresolvedlocally.', 'unmet', [native('config.js',230,269),native('builder.html',192),rd(123,127)], [ts('rlgwo-docs-contract.cjs',158,167)], 'Tabletrigger/recipient/fieldsaccurate; controlledprimary/fallbackrequestswithnofieldoverclaim.', 'Actualsourceconstructsget.geojs.io/v1/ip/geo.jsonthenipinfo.io/json andlocaldetectTz; READMEmentionsIPprovidersbutdoesnotprovidebindingtrigger/fieldrow. Builderhascorrectfallbacksummary.'),
 row('27-03','Searchdebounce/Enter inbuilder andSettingsEnter sendtypedq toNominatim; digitquerymayaddhomecountrycountrycodes; do notclaimeveryeditcoordinates.', 'unmet', [native('config.js',360,375),native('builder.html',300,325),rd(121,140)], [ts('rlgwo-docs-contract.cjs',119,145)], 'READMErowdescribesactualrecipientq/conditionalcountrycodesandfeaturetriggers.', 'Currentsourcehasexactqencodingandconditionalcountrycodes; builderhas1000msdebounce/Enter. READMErecipient/field/triggerdescriptionisabsent; no freshsourcecallerexecutionhere.'),
 row('27-04','Whitespace-strippedletter-digit-letterprefix sendsupperfirstthree /ca/FSA toZippopotam, inadditiontoNominatim; notpostcodevalidityassertion.', 'unmet', [native('config.js',362,371),native('builder.html',192),rd(121,140)], [ts('rlgwo-docs-contract.cjs',119,136)], 'ExactM5V2T6->/ca/M5V andmalformedprefixtriggercharacterization; Londonnegative excludesCanadianrequest.', 'Implementationandbuildersummarycorrect; READMEmissingCanadianprefixrecipient/fieldsrow. Noactualexternaltransmission/validpostalcodeclaimiscredited.'),
 row('27-05','Eligiblebuilderautomaticname/methodcoordinateorGPSlookup sendsBigDataCloudlatitude/longitude/localityLanguage=en; widgetprecisepathitselfisnotbuilderreversefunction.', 'unmet', [native('builder.html',327,343),native('config.js',272,318),rd(121,140)], [ts('rlgwo-docs-contract.cjs',147,156)], 'READMErowexactcoordinatefields/triggers; bothautooffnomatchingrequest; avoidoverbroadwidgetGPSclaim.', 'ActualbuilderfetchL334andguardsL328-L331matchrequiredledger; buildernoteidentifiesreversecoordinates. READMEhasnorecipient/fieldrow; no freshcontrolledreverseexecutioncredited.'),
 row('27-06','Prayerloading/refresh:Aladhanreceiveslatitude,longitude,method,school,requesteddate; weatheractiveacquisition:Open-Meteocoordinates,zone,units,fieldselections.', 'unmet', [native('index.html',1064,1077),native('index.html',1366),rd(121,140)], [], 'Bothactualfinal-treecallsitefieldsetsinprivacytable, feature/cache/networkconditionshonest.', 'ActualcurrentURLshaveexactfieldsandweathercurrent/hourlyselection; READMEAPI/featuresmentionsproviderselsewherebutprivacytable/fieldsaremissing. Sourceledgerwasread, notliveprovidertransmission.'),
 row('27-07','Radaractiveacquisition:RainViewermanifestrequestandreturnedtilehost/frame/tilepath withlocation-derivedx/y; no falsemm/retentionauthority.', 'unmet', [native('index.html',1430,1457),rd(121,140)], [], 'Privacyrowdistinguishesmanifestrecipientfromtilehostandlocation-derivedindices.', 'SourceRainViewerURLandWebMercatorxt/yt/pathL1444-L1448verified. READMEmissingthisrow; noobservation/intensity/retentionclaimadded.'),
 row('27-08','GoogleFontsstylesheet/fontresourcehostsdisclosedsubjecttocache, URLswithoutwidgetlocation/searchtext.', 'unmet', [native('index.html',7,9),rd(121,140)], [], 'Tablementionsresourcehosts/requestconditionanddoesnotinventlocationqueryfields.', 'Actualfontdeclarationsareexternalstylesheet/preconnect; READMEprivacyhasnofontrequestrow. AssetURIsourceonlyproof, notfreshnetworktrace.'),
 row('27-09','Resetonlyremovessavedconfigurationkey, notprayer/weathercaches orproviderhelddata; descriptionclient-sideconstruction/no providerretentionconclusion.', 'unmet', [native('config.js',216,218),rd(121,140)], [ts('rlgwo-docs-contract.cjs',168,172)], 'SpecificReset/cache/providerboundary andno unsupportedserverretentionassumption.', 'CurrentclearLocalremovesonlyKEY, butREADMEmissingreset/cache/providerboundaryandretainsunsupportedblanketclaim.'),
 row('27-10','Retainpreciseuseraction/permission,hoststrippedallowgeolocation/coarsemanualfallback,storage/persistencefailureguidanceanddetailsanchor; donotclaim#17UIfixwithoutreadback.', 'satisfied', [native('builder.html',192),rd(128,140),native('builder.html',217,219)], [], 'Correcthost/browserpermission/storageguidanceexists, builderdetailslinksREADMEsameanchor.', 'CurrentbuildernoteandREADMEretainpermission/host/persistenceexplanations. DetailsanchorpointsactualREADMEprivacysection, butlinkedcontentincompletenessismappedabove. Noadditional#17UIruntimequalificationisclaimed.'),
 row('27-11','Finalactualsourcefunctiondiscriminators:exactM5V2T6 URLs, reverse51.5/-0.12; Londonnocanadian, trimmedshortnosearch, bothautooffnoreverse; completecallsiteledgerperrow.', 'unverified', [native('config.js',360,375),native('builder.html',327,343)], [ts('rlgwo-docs-contract.cjs',119,172)], 'Executeexactfinalauthored/consumerfunctionswithinterceptedfetch; noexternaltransmission; expectednegativecontrols detectoverbroadtriggerdescription.', 'Exactchecked-infixtureassertionsandfinalcallsiteledgerread. No newNodefixtureexecutionwasauthorizedduringprimarysmoke. Historicaldocsreceiptsfromdifferentsource/docstreesarenotclaimedascurrentexecution. Requiredpositive/negativeexecutioncanbereusedonlyafterexactsource/fixtureapplicabilityorperformedbyprimary.'),
 row('27-12','RenderedREADME/builderlegibility/agreement andpublicdocumentreadbackifclaimingpublisheddisclosure; prose-onlyeditsmustpreservecontrols/payload/runtime/geometry.', 'unverified', [rd(121,140),native('builder.html',192)], [], 'Readrenderedpublishedtextandbuildernoteatreviewedversion; no runtimechange/consent/providerreplacement/legalretentionpolicy.', 'Primary139-filehashreceiptprovesbuilderbyteswith200/SHA66f1cd86; itdoesnotproveREADMErenderingorbuilderprivacyreadability. E ran nobrowser. Textdefectremainsevenifcurrentrenderingislegible.'),
 row('27-13','Originalouterwrapperinvariantisnarrowlyamended; preservecard/permissionsandavoidunrelatedgeometrywork.', 'validly superseded', [native('builder.html',217,219)], [], 'Owner330x534outerwrapperpolicy; card325x530andpermissionpreserved.', GEOMETRY),
]
M[28] = [
 row('28-01','Repaireverypositivequery-onlydiagnosticexampleinAGENTS,DESIGN,OPTICS; configurationanddiagnosticsreadfragmentafter#; retainlabeledquerynegativeandintentionalbuildercachebustingquery.', 'unmet', [delivered('AGENTS.md',48),delivered('AGENTS.md',90,91),delivered('AGENTS.md',108),delivered('DESIGN.md',282,302),delivered('OPTICS.md',99,162),native('index.html',667),delivered('index.html',2791)], [ts('rlgwo-docs-contract.cjs',97,108),ts('rlgwo-docs-contract.cjs',290,310)], 'Allbindingpositiveexamplesusecompletefragmentor&append; actualqexpressionrejectsqueryonly; nocachebustingchurn.', 'DeliveredAGENTS L48/L90-L91/L108, DESIGN L282/L294/L297/L406-L409, OPTICS L99/L104/L116/L122/L127/L131/L162stillusepositive?examples. ActualauthorqL667andconsumerqL2791readonlylocation.hash. Thisisaconfirmedprosediscriminator, notmotionpixelproof.'),
 row('28-02','Sixforce-nameenumexactlyhalo,sundogs,pillar,anticrep,paraselene,lunarhalo; unsupportedcorona/earthshine/refraction/crepuscularrayrequirephysicalinputs; no each-effectforceclaim.', 'unmet', [native('index.html',2732,2746),delivered('index.html',4773),delivered('DESIGN.md',328),delivered('DESIGN.md',390,393)], [ts('rlgwo-docs-contract.cjs',180,205),ts('rlgwo-docs-contract.cjs',311,317)], 'Enumequalsactualsixbranches; parsablecoronastringdoesnotmeanforcebranch; everyeffectblanketclaimremoved.', 'Actualsixbranchesmatchcontract, includinglunarphysicaleligibility. DESIGN L328omitslunarhalo andL392 saysEach can be forced via?debugOptic; L408forceeachisalsooverbroad. Physical-onlyexplanation/qualifiedenumunfinished.'),
 row('28-03','Addrequiredexplanatoryfragment/negative/six-name/physical-onlytextandcompletecopyablereal-timemotion/fullmotion/noonhaloexamples.', 'unmet', [delivered('AGENTS.md',148,164),delivered('DESIGN.md',315,328),delivered('OPTICS.md',99,162)], [ts('rlgwo-docs-contract.cjs',173,205)], 'Completeindex.html#lat=24.47&lon=39.61&label=Madinah&method=4 with&debugMotion=1, optional&motion=full; haloexamplefragmentwithsimTime12:30.', 'ExistingRunning guidancealreadyuses&appendandno-simreal-timeadvice, preservedgoodcontrol; requiredcompletecopyablefragmentrecipes/explanatorynegativeareabsentandpositivequeryexamplesremain.'),
 row('28-04','State simTimewithouttimeScalefreezesclock-driven scene; real-time15-60swatch needed; flagactivationisnotvisiblemotion/opticalpixelproof; lunarforceexamplemustuseeligiblephysicalscene.', 'unmet', [delivered('AGENTS.md',156,164),delivered('DESIGN.md',315,328),native('index.html',2731,2746)], [ts('rlgwo-docs-contract.cjs',311,317)], 'Keepfreezetextandaddexplicitactivation/pixelboundary; noonhaloisnotall-effect/lunarproof.', 'AGENTS alreadywarnssimTimewithouttimeScale andmotionproof; DESIGN preservesclockgotchaelsewherebutno requiredactivation/pixelqualificationtextatdiagnosticrecipes. Blanketeveryopticforceclaimcontradictsactualphysicaleligibility.'),
 row('28-05','Validateeverychangedliteralfromactualboundqexpression; motion=fullmustparsefull; flagbefore#positiveassertionfails; unsupportedcoronaenumassertionfailsdespiteparsedstring.', 'unverified', [native('index.html',667),native('index.html',734,737),delivered('index.html',2791),delivered('index.html',2858,2861)], [ts('rlgwo-docs-contract.cjs',97,108),ts('rlgwo-docs-contract.cjs',173,205),ts('rlgwo-docs-contract.cjs',290,317)], 'Actualsourceparser/executedbranches,literal-by-literaldocsreadbackincludingAGENTScorrections; no manuallyfixed-onlyfixture.', 'Checked-infixturecontainsrequestedpositive/negativeparserandbranchcontrols; source/manualreadbackidentifiesactualremainingbadliterals. No freshNodeexecutionduringprimarysmoke; unchangedbadtextcannotbeclosedbyonlyhealthyhandwrittenURLs.'),
 row('28-06','Openactualcompleteproductionreal-timerecipeondisposablebrowseroriginandconfirmq/debugMotionreadoutactive; motionfullcaseunderreducedmotionmustreadback; stopifbrowserunavailable.', 'unverified', [native('index.html',734,737),native('index.html',3208),delivered('index.html',2858,2861)], [], 'BrowserqDEBUGMOTIONtrue,overlayactive; fullfragmentoverrideactiveunderreducedmotion; normalaccessibilityretained.', 'E holdsnobrowserlease and hasnotperformedbrowserreadback. Primarysmokereceiptwasnotyetavailableatassessmentassembly. Historicalphysicalmotionreceiptsdoproveotherboundedgates,butdo notfixorqualifybadpublishedrecipes.'),
 row('28-07','Anyvisiblemotion/pixelclaimneedsactual15-60swatch/clip/delta/crop byonebrowserowner; neverqaStatecloudhash; physical-onlyeffectsretainconditionfixturesandvisiblecornersun/opaquemoon/failcloseddawn.', 'satisfied', [delivered('AGENTS.md',85,108),delivered('AGENTS.md',151,164)], [], 'Maintainexistingnocloudhash/screenshot/physics/accessibilityinvariants; nosyntaxcountasvisualPASS.', 'Currentguidanceretainsstrongnocloudhash/realwatch/pixel/physicalconditiongates; no EvisualPASSisasserted. Thisrowpreservesexistinginvariantsanddoesnotcreditnewvisualexecution.'),
 row('28-08','Documentation-onlyownership:AGENTSincluded; index/builder/configverification-only; intentionalbuilder?rquerypreserved; no newqueryparser/forceframework/rendererchange.', 'satisfied', [native('builder.html',214,216),native('index.html',667),delivered('AGENTS.md',6,18)], [], 'Fixliteralprose/enumthroughdocumentationintegratorwithoutchangingruntimeoptionsemantics.', 'Authoredqstillfragmentonlyandbuildercache-bustingqueryintentional; boundedproposaleditsonlyexistingdocs. Nomutationhasbeenperformed.'),
 row('28-09','ReadrenderedfinalAGENTS/DESIGN/OPTICS/publicdocsifpublishedclaims; exacttext/recipe/enum/evidencecommentrequiredbeforemanualclosure.', 'unverified', [delivered('AGENTS.md',48,108),delivered('DESIGN.md',282,328),delivered('OPTICS.md',99,162)], [], 'Finalcorrectedliteral/enumtextplusrenderedpublicreadbackandprimaryreconciliation.', 'Primaryruntimehashreceiptcoversruntime/V1assets, nottheseMarkdownrenderedpages. Requiredsource/textcorrectionisabsent; no publishedreadback/closureisclaimed.'),
 row('28-10','Preserveexistingcard/readability/permissionandlaterproductionouterwrapperamendment; thisdocumentationrepairdoesnotowngeometry.', 'validly superseded', [native('builder.html',217,219)], [], 'Ownerwrapper330x534versus325x530cardpreservedwithoutgeometryedits.', GEOMETRY),
]

NEXT = {
19: dict(gaps=['Missing actual Apple /bin/bash3.2/macOS detector and pipe/PTY entry proof.',
              'Complete both-family zero/one/multiple/backslash detector matrix and retained newline-path limitation are not fully demonstrated/disclosed.',
              'README lacks required terminal and same-attempt-versus-retired-cross-run cache instructions.',
              'Current adversarial builder/hash and rawinstaller/publicusage readback remain unverified.'],
         scope='README installer usage, bounded native Apple/modern profile and actual-entry fixtures; preserve existing installer source unless a concrete native failure is reproduced.',
         steps=['Use an authorized actual macOS host. Record /bin/bash --version, native stat/mktemp and filesystem identities. Qualify actual detector/cardinality/path and PTY pipe entry with controlled effect boundaries.',
                'Fill only the uncovered detector path/control cells and exact current malicious-label builder/hash roundtrip; preserve original negative/mutation oracles.',
                'Update README terminal requirement, no EOF-as-answer, file-review route, within-attempt cache versus retired shared cross-run admission, and newline profile limitation. Retain correct builder Bash hash placement/manual warning.',
                'Bind final source/fixtures/docs and authorized rawscript/generatedcommand readback; primary independently reconciles then decides closure.'],
         acceptance='Every mandatory native detector/entry/control cell passes on claimed hosts; path stdout and existing owned cache behavior remain green; README/command/privacy/geometry obligations match current source; negative mutants fail; immutable proof/comment supplied.',
         dependencies=['R0015 private root and retained-lifetime interface; R0016 normal-versus-preview boundary; actual builder/config serializer/command consumers. No whole-issue closure predecessor required.']),
20: dict(gaps=['Delivered README omits the exact WindowsPowerShell5.1/pwsh distinction and Windows reviewed download/-File route required by the public-capability contract.',
              'Rawinstall.ps1 endpoint/current generatedcommand/publicusage readback is not contained in the primary139-file runtime receipt.'],
         scope='README Windows installer instructions and exact raw-script/command acquisition; preserve qualified ASCII selector/entry source and native fixtures.',
         steps=['Add concise WindowsPowerShell5.1 and supportedpwsh7 distinctions plus reviewed/downloaded quoted -File invocation. Keep irm|iex and builder encodedhash grammar/manualdashboard boundary unchanged.',
                'Read authorized rawinstall.ps1 bytes without resaving; bind SHA256d4d0cd3e... or invalidate only affected native/source evidence if bytes differ. Parse downloaded exactbytes on actual5.1/7 and confirm generatedcommand if public distribution is claimed.',
                'Use retained native18-case and direct-entry24-case evidence through exact source/fixture equivalence; rerun affected controls only if those inputs changed. Publish necessary receipt core inline or immutable evidence, then primary reconciles.'],
         acceptance='Public README states actual floor/file route/manual boundary; rawdistributedfile exactly matches qualified source or receives new native parser/consumer gates; every #20 matrix row satisfied. Missing Mac evidence from siblings is not a #20 requirement.',
         dependencies=['R0016 Windows guards share exact source and already qualified native interface; no hard whole-issue Apple/Bash prerequisite.']),
21: dict(gaps=['Mandatory actual macOS/AppleBash3.2 BSDstat/mktemp/filesystem staging/retention controls absent.',
              'Isolated foreignUID non-writable retained-parent initializer refusal lacks a discriminating native receipt.',
              'README lacks retained-bundle/optionalmanual-removal/keepunpacked/cache compatibility wording.',
              'Distributed Bash script/current usage readback unverified.'],
         scope='Native missing platform/ownership controls and README bundle/cache lifetime text; preserve current private roots, validation, confinement, LinuxDAC receipts and scratch-only cleanup.',
         steps=['Qualify actual macOS native initializer/write/extraction/cleanup/failure/interrupt/freshconsumer paths on authorized disposable nativefilesystem parents; record Bash3.2/BSDstat/mktemp/UID/modes/identities.',
                'Use native Linux distinct fixtureUIDs to prove real initializer rejects a reachable foreignUID parent with non-writable mode, while a sameUID equivalent succeeds. Preserve peerDAC49-operation evidence; it is a different established cell.',
                'Add accurate README home-bundle lifecycle, keepunpackedwhileinstalled, optionalmanualpreset/XPI removal, partialretention and retirement of shared cross-run cache; retain correct scriptinstructions.',
                'Bind exact source/current distributions and independent security applicability. Keep archived ownerexit/freshconsumer proof time-bounded and disclose later absent fixture without inferring cause.'],
         acceptance='All parent/nativeMac, confinement/archive/cache/lifetime/dryrun and mutation cells demonstrate original expectations with outside sentinels unchanged; publicprose and rawsource match; never delete unverified old/manual artifacts.',
         dependencies=['R0013 path stdout/same-attempt cache consumer; R0016 initializer/cleanup unreachable in preview; shared installer/README changes use onewriter.']),
22: dict(gaps=['Complete actual AppleBash3.2/macOS whole-entry matrix and its #19/#21 native interfaces absent.',
              'README lacks offline no-effect/no-artifact/no-prompt preview usage and NoOpen distinction.',
              'RawBash/Windows script and usage distribution readback unverified.'],
         scope='README offline preview usage plus missing actual macOS contained wholeentry/guard matrix; preserve existing Linux/Windows entry/source receipts and normal positive behavior.',
         steps=['State identical offline preview policy in README and applicable usage surfaces: read local discovery only; no filesystem/network/clipboard/process/cleanup; remote/version/paths/askchoice unresolved; no installed acknowledgments; NoOpen suppresses opening only.',
                'After actual macOS launch/staging prerequisites pass, execute nativeAppleBash3.2 full fresh/cached/store/ask/installed/missingpreset/mixed/legacy/none/options matrix with subject snapshots, transportdenial/effectspies, normal/NO_OPEN positives and targeted parsevalid mutants.',
                'Keep native5.1/7 directFile and Linux receipts through exact source/fixture equivalence. Do not rerun expensive unrelated sky campaigns or weaken original expectations.',
                'Bind both public rawscript/usage identities and independently review exact composed effects before primary reconciles closure.'],
         acceptance='Every claimed platform shows zero installer effects/unchanged subject in preview and exact intended normal positive/NoOpen consumers; helpersreturnnousableartifacts; required mutants fail; README and actual distributed source agree.',
         dependencies=['R0013 actual Bash launch/FD3 contract and R0014 exact nativeWindows parsing/selector qualification; R0015 private scratch/retained roots and cleanup interface. State individual interface gaps, not administrative closed-state prerequisites.']),
27: dict(gaps=['Delivered README privacy introduction/table/Reset/provider-retention boundary absent, with unsupported blanket wording retained.',
              'Current source-trigger controls and rendered README/builder/public-document agreement are not freshly qualified in this audit.'],
         scope='README privacy/data-flow prose and bounded current source ledger/trigger/readback controls; preserve completed src/native/builder.html L192 and identical delivered builder note.',
         steps=['Replace only incomplete README privacy wording with the original compact introduction and exact final-callsite table: GeoJS/ipinfo, Nominatimq/countrycodes, ZippopotamFSAprefix, BigDataCloudcoordinates, Aladhanlocation/method/school/date, Open-Meteolocation/zone/units/fields, RainViewermanifest/tilehost/location-derivedindices, GoogleFontsresources.',
                'State Resetconfig-only/cache/providerboundary and no provider-retention conclusion. Retain permission/host/storage/coarsemanual guidance and builderdetailsanchor; remove only unsupported blankettracking/server claims.',
                'Execute exact current source functions with interceptedfetch: M5V2T6 exactURLs, reverse51.5/-0.12, LondonnoCanadian/digitbias, shortqueryno requests, bothautooffnoreverse. Document final-callsite fields for each table row.',
                'Read rendered README and builder note and authorized public version, then primary reconciles evidence/comment.'],
         acceptance='Complete prose and per-row source ledger agree; all positive/negative trigger controls pass; rendered/public readback is legible and matches source; no runtime, provider, consent, retention or permission policy change.',
         dependencies=['R0011 persistence-failure wording/actualUI interface; shared config geocodeSearch/coarseDetect/clearLocal and builder reverse/lookup callers.']),
28: dict(gaps=['AGENTS/DESIGN/OPTICS still contain ignored positive query-only diagnostic recipes.',
              'DESIGN force enum omits lunarhalo and overclaims everyeffect forceability.',
              'Complete corrected literals/explanation, literal-by-literal controls and actual productionq/debugreadout/reducedmotion browser/public-document evidence absent.'],
         scope='AGENTS.md, DESIGN.md and OPTICS.md existing diagnostic prose/recipes; runtime owners remain verification-only.',
         steps=['Replace each affected positive?diagnostic literal with samefragment&append or complete index.html#... examples. Keep negativequeryexample visibly negative and intentional builder?r cachebusting unchanged.',
                'State exact six force branches includinglunarhalo and condition-onlycorona/earthshine/refraction/crepuscularray. RemoveEachcanbeforced/forceeach claims; include required simTime/timeScale freeze and flagactivation-not-pixelproof text.',
                'Validate every changed literal through actual finalq declarations/real sixbranches, motionfull value, before# negative and unsupportedcorona mutant. Do not only test manuallycorrectedURLs while publishedbadtext remains.',
                'One browserowner checks complete actual real-time fragment/debugreadout and motionfull under reducedmotion; use actualwatch/delta/crop only for any visualclaim. Read rendered/public correctedMarkdown then reconcileprimary comment.'],
         acceptance='No positive ignored-query examples remain in required docs; enummatchesactualsixbranches; physical-only limitations honest; every literal and bothmutants discriminate; productionbrowserflag/readout and publishedtext readback captured; no runtime behavior change.',
         dependencies=['Documentationintegrator owns shared AGENTS/DESIGN/OPTICS; actual src/native/index.html/generated index q/flags/forcebranches; exclusive sequential browserowner. No new typed-edge or runtime framework.']),
}

def md_escape(text):
    return str(text).replace('|','\\|').replace('\n',' ')

def native_receipts():
    names = ['host-inventory-final.json','native-applicability-2fafcbf.json','final-r0014-ps51.txt','final-r0014-ps7.txt',
             'direct-native-final.json','r0014-mutant-encoding.txt','r0014-mutant-comma-corrected-ps51.txt','r0014-mutant-comma-corrected.txt',
             'bash-helper-archived-source.json','bash-entry-archived-source.json','bash-mutations-archived-source.json',
             'ps51-mutations-qualified.json','ps7-mutations-final-source.json','direct-native-mutants.json',
             'crossuid-nonlogin/result.json','crossuid-nonlogin/post-run-native-readback-qualified.json']
    return [dict(name=n, path=str(OLD/n), sha256=hashlib.sha256((OLD/n).read_bytes()).hexdigest(),
                 provenance='historical retained original execution or applicability receipt; not freshly executed by reviewer E') for n in names]

def main():
    now = datetime.datetime.now(datetime.timezone.utc).isoformat()
    objects = []
    paths = ['install.sh','install.ps1','tests/install-bash.py','tests/install-entry-bash.py','tests/install-entry-native.py',
             'tests/install-powershell.ps1','tests/install-powershell-guards.ps1','tests/install-mutations.py',
             'src/native/builder.html','builder.html','src/native/config.js','config.js','README.md','AGENTS.md','DESIGN.md','OPTICS.md']
    for name in paths:
        blob = git('rev-parse',f'{SHA}:{name}').decode().strip()
        data = git('show',f'{SHA}:{name}')
        record=dict(path=name, blob=blob, sha256=hashlib.sha256(data).hexdigest(), bytes=len(data))
        if name.startswith('install.') or name.startswith('tests/install'):
            record['reviewed_native_blob']=git('rev-parse',f'{REVIEWED_NATIVE}:{name}').decode().strip()
            record['source_or_fixture_identical']=record['reviewed_native_blob']==blob
        objects.append(record)
    target = dict(commit=SHA, tree=TREE, runtimeSha256=RUNTIME, indexSha256=INDEX,
                  examinedCheckoutHead=git('rev-parse','HEAD').decode().strip(),
                  examinedCheckoutTree=git('rev-parse','HEAD^{tree}').decode().strip(),
                  checkoutStatus=git('status','--short').decode(), origin=git('remote','get-url','origin').decode().strip())
    authority = dict(objective='Bounded delivered-target closure audit of exactly #19,#20,#21,#22,#27,#28.',
                     authority='WORKER_BRIEF.md and assigned parent scope; read-only source/evidence; only workers/E outputs.',
                     assumptions=['Supplied initial full issue packets are the audit contract; no comments/amendments beyond captured bodies/events and supplied owner policy.',
                                  'Native receipt reuse is narrow exact source/fixture/environment equivalence, not fresh execution or current fixture liveness.',
                                  'No mandatory native Apple host equivalence is accepted from GNU Bash/PLATFORM mocks or disabledbuiltins.'],
                     acceptance='Six full per-issue matrices/comments plus summary and source/receipt custody; no unsupported closure or publication claim.',
                     compensation='Outputs are reversible local reviewer artifacts. Preserve source and all original retained evidence; corrections replace only E assessment/comment files.',
                     doneWhen='Complete issue packets returned to primary; primary reconciliation/publication remains separate.',
                     requestedModel='gpt-6.1-sol', requestedReasoning='max', actualBackendModel='UNATTESTED', actualEffectiveReasoning='UNATTESTED',
                     modelNote='Requested dispatch is recorded separately; no backend/effectiveconfig attestation is exposed in this worker.',
                     testsExecuted='NONE by E during primary rollout smoke; source/receipt acquisition and output serialization only.',
                     browsers='NONE', installerEffects='NONE', sourceMutations='NONE', gitMutations='NONE', githubWrites='NONE', subagents='NONE')
    rebind=dict(schema='rlgwo.worker-E.native-rebind.v1', capturedAtUtc=now, target=target, authority=authority, sourceObjects=objects,
                retainedReceipts=native_receipts(),
                nativeBoundaries=dict(Windows='Retained actual PS5.1.26100.9444/PS7.6.6 exact-file18cases each; direct -File24cases total, source+fixtures identical.',
                                      Linux='Retained WSL2 Linux Bash5.2.21 native/tmp ext2/ext3:26helpers,23actualentry; UID1000/65534 DAC49operations30EACCES13/19allowedpositives.',
                                      Apple='UNVERIFIED. Actual Apple/macOS /bin/bash3.2, BSDstat/mktemp/terminal/filesystem cells remain explicitly BLOCKED in retained applicability.',
                                      Lifetime='Recorded ownerexit plus freshUID1000fileconsumer only; later fixtureExists=false, causeunknown; no present/reboot/browser-install claim.'))
    public = json.loads((AUDIT/'public-runtime.json').read_text(encoding='utf-8-sig'))
    scope_checks = [c for c in public['checks'] if c.get('path') in ('builder.html','install.sh','install.ps1','README.md','AGENTS.md','DESIGN.md','OPTICS.md')]
    rebind['primaryPublicReceipt']=dict(path=str(AUDIT/'public-runtime.json'), sha256=hashlib.sha256((AUDIT/'public-runtime.json').read_bytes()).hexdigest(),
                                       capturedAt=public['checkedAt'],mergeCommit=public['mergeCommit'],pagesBuild=public['pagesBuild']['commit'],
                                       relevantChecks=scope_checks,
                                       absentRequiredOwners=[p for p in ['install.sh','install.ps1','README.md','AGENTS.md','DESIGN.md','OPTICS.md'] if not any(c.get('path')==p for c in scope_checks)],
                                       limit='Primary receipt source/HTTP hash proof only; E did not repeat public request or render. Publicationhold continues.')
    (ROOT/'native-rebind.json').write_text(json.dumps(rebind,indent=2,ensure_ascii=False)+'\n',encoding='utf-8')
    entries=[]
    for n in sorted(M):
        packet=json.loads((AUDIT/'issues'/f'{n}.json').read_text(encoding='utf-8-sig'))
        bodyhash=hashlib.sha256(packet['issue']['body'].encode('utf-8')).hexdigest()
        if bodyhash != packet['contract']['bodySha256']: raise ValueError(f'Issue{n} body custody mismatch')
        cid=packet['contract']['canonicalId']
        assessment=dict(schema='rlgwo.closure.worker-assessment.v1',worker='E',assessedAtUtc=now,issue=n,canonicalId=cid,
                        issueTitle=packet['issue']['title'],issueUrl=packet['issue']['html_url'], originalBodySha256=bodyhash,
                        originalBodyRevision=packet['contract']['updatedAt'],packetCapturedAtUtc=packet['capturedAtUtc'],
                        commentsRead=packet['comments'],eventsRead=packet['events'],target=target, authority=authority,
                        amendments=[dict(scope='Outer production iframe geometry only',text=GEOMETRY),
                                    dict(scope='R0013/R0015 private-cache interface body amendment',text='Within-attempt verified cache reuse remains; cross-run sharedroot admission retired; not a whole-issue predecessor.') ] if n in (19,21) else [dict(scope='Outer production iframe geometry only',text=GEOMETRY)],
                        requirementMatrix=M[n], evidenceSource='native-rebind.json plus inline comment receipt core and immutable target blob/ranges',
                        executedCommands=[dict(command='git show <AUDIT_SHA>:<listed source/test/doc>; git rev-parse <AUDIT_SHA>:<listed path>; git rev-parse b2dc8b36:<installer/test>; git status --short; Get-Content retained receipts; Get-FileHash SHA256',
                                               scope='fresh read-only acquisition, not product/native execution',expected='Exact target/readable contract and sources; unchanged native object equivalence',
                                               observed='Targettree35208181, clean examined checkout at4bccdf43; all eight installer/test objects match b2dc8b36; nativeBash/PSsourcehashes matchretained receipts; issuebodyhashes match6of6.')],
                        historicalCommands=[dict(command='powershell.exe/pwsh.exe -NoProfile -File tests/install-powershell.ps1; python tests/install-entry-native.py install.ps1',environment='Actual retained WindowsPowerShell5.1.26100.9444 and PowerShell7.6.6',
                                                 expected='Nativeexactfile/selector/caller/directentry controls',observed='18/18each;24directcasesallpass; normal21/NoOpen17effectsperhost; no freshEexecution.'),
                                            dict(command='python3 tests/install-bash.py install.sh; python3 tests/install-entry-bash.py install.sh',environment='Actual retained WSL2Linux Bash5.2.21 native /tmp ext2/ext3, notDrvFS',
                                                 expected='Helperconfinement/cache/lifetime;actualPTYentry/preview/normalcontrols',observed='26helpers/23entrypass; normal28/NO_OPEN24effects; missingactualApplehostnotwaived.'),
                                            dict(command='crossuid-nonlogin/run-control.py -> wsl Ubuntu root supervisor -> setpriv UID1000/65534 actors',environment='Recorded WSL2kernel6.6.87.2, nativefilesystem; groups/capszero foractors',
                                                 expected='Reachablepositivecontrols andprivate0700rootDAC;sentinels/identity unchanged;ownerexit/freshconsumer',observed='49operations30EACCES13/19allowed;ownexit0/freshconsumer0;laterfixtureabsent,causeunknown.') ] if n in (19,20,21,22) else [],
                        reuseBasis='Current installer and native fixture Gitobjects exactly equal b2dc8b36; receipt sourceSHA matches. Every credited result remains historical time/environment/fixture bound. README/docs do not match previously reviewed corrected docs and their prior PASS is not reused as final prose proof.',
                        negativeControls=[r for r in M[n] if 'mutant' in r['obligation'].lower() or 'control' in r['obligation'].lower() or 'discriminator' in r['obligation'].lower()],
                        gaps=NEXT[n]['gaps'], verdict='LEAVE OPEN',proposedNextIncrement=NEXT[n],
                        publicationStatus='PROPOSED_ONLY_NOT_RECONCILED_NOT_POSTED',primaryReconciliation='REQUIRED before publication; reviewer cannot approve closure or claim external human/CI acceptance.',
                        residualLimits=['No new native/browsers/tests execution by E; immutable source/receipt review only.',
                                        'NativeApplemissingproof is unverified, not demonstratedplatformdefect.',
                                        'Publicruntimebuilder hash is not rawinstaller/README/publicrendered proof.',
                                        'N001/N002PARTIAL,N003BLOCKED and8historicalnativefailures/4TODO are not blanket blockers; only mapped obligation evidence is relevant.'])
        (ROOT/f'{n}-assessment.json').write_text(json.dumps(assessment,indent=2,ensure_ascii=False)+'\n',encoding='utf-8')
        lines=[f'# RLGWO closure audit — {cid} — REMAINS OPEN', '',
               f'**Recommendation: LEAVE OPEN.** {" ".join(NEXT[n]["gaps"])}','',
               f'Audit date: 2026-10-08 (local). Repository: `theislampill/salah_widget`. Delivered target `{SHA}`, tree `{TREE}`; runtime SHA256 `{RUNTIME}`, root index SHA256 `{INDEX}`. Contract `{cid}` / #{n}: original body SHA256 `{bodyhash}`, revision `{packet["contract"]["updatedAt"]}`; complete body, empty comments and captured events examined. This proposal is not reconciled or posted.','',
               'The reviewer acquired the exact source/test/doc objects and retained receipts read-only. No installer, new native suite, browser, production mutation or GitHub write was performed. Existing native executions are historical reuse on identical source/fixture objects, not fresh execution. Requested reviewer route: gpt-6.1-sol/max; effective backend/config has no independent attestation in this worker.','',
               'The following matrix preserves the binding obligations. “Unverified” is missing proof; “unmet” identifies the demonstrated delivered text gap. Source links bind the delivered commit.','',
               '| Obligation | Authored owner / delivered consumer | Discriminator; expected → observed | Status |',
               '|---|---|---|---|']
        for r in M[n]:
            links='; '.join(f'[{p["path"]}:{p["start"]}-{p["end"]}]({p["url"]})' for p in r['authored_owner_and_delivered_consumer'])
            tests='; '.join(f'[{p["path"]}:{p["start"]}-{p["end"]}]({p["url"]})' for p in r['discriminator']) or 'Source and retained receipt readback; execution status stated below'
            lines.append('| '+ ' | '.join([md_escape(r['obligation']),links,md_escape(tests+'; EXPECTED: '+r['expected']+' OBSERVED: '+r['observed']),r['status'].upper()])+' |')
        if n in (19,20,21,22):
            core=dict(source=dict(install_sh=BASHHASH,install_ps1=PSHASH),
                      reused_native=dict(Windows=dict(hosts=['5.1.26100.9444','7.6.6'],selectors_callers=[18,18],exact_file_errors=[0,0],direct_file_cases=24,normal_effects_per_host=21,noopen_effects_per_host=17),
                                         Linux=dict(Bash='5.2.21(1)-release',kernel='6.6.87.2-microsoft-standard-WSL2',filesystem='/tmp native ext2/ext3',helpers=26,actual_entry_cases=23,normal_effects=28,noopen_effects=24),
                                         DAC=dict(ownerUid=1000,peerUid=65534,total=49,EACCES_13=30,allowed_positive_and_reachable_controls=19,actor_groups=[],actor_capabilities=0,sentinels_unchanged=True,owner_exit=0,fresh_file_consumer_exit=0),
                                         Apple='Actual macOS /bin/bash3.2 NOT OBSERVED'),
                      receipt_hashes={r['name']:r['sha256'] for r in rebind['retainedReceipts'] if r['name'] in ('final-r0014-ps51.txt','final-r0014-ps7.txt','direct-native-final.json','bash-helper-archived-source.json','bash-entry-archived-source.json','crossuid-nonlogin/result.json')},
                      limits=['Counts are retained exactsource observations, not newly executed suite or source-only PASS labels.',
                              'No signature authenticity, FirefoxZIP installability, realbrowser load/import, Apple platform equivalence, present fixture liveness or reboot persistence claim.',
                              'Later crossUID fixture readback was absent; original ownerexit/freshconsumer record remains time-bounded.'])
            lines += ['', 'Retained receipt core (inline for public inspection; the linked checked-in assertions above define the actual consumer oracles):','', '```json',json.dumps(core,indent=2),'```','',
                      'Recorded contained commands: `powershell.exe` and `pwsh.exe -NoProfile -File tests/install-powershell.ps1`, `python tests/install-entry-native.py install.ps1`; native Linux `python3 tests/install-bash.py install.sh` and `python3 tests/install-entry-bash.py install.sh`. They are reproduction recipes on matching bytes and newly authorized disposable fixtures; this audit did not run them. The direct native test invokes exact source with `-File` (not a wrapper), separately asserts interception readiness, snapshots and exact positive consumer arguments.','']
        lines += ['', '**Next RLGWO increment required for closure**','',f'Semantic owner/scope: {NEXT[n]["scope"]}','',
                  'Preserve completed work and all original negative expectations. This proposal grants no new production, dependency, installation, account/permission or external-publication authority. It adds no broad refactor or replacement runtime.','']
        for i,step in enumerate(NEXT[n]['steps'],1): lines.append(f'{i}. {step}')
        lines += ['',f'Acceptance and closure proof: {NEXT[n]["acceptance"]}','',
                  'Dependencies/interfaces: '+' '.join(NEXT[n]['dependencies']),'',
                  'Containment/rollback: use new owned disposable evidence roots; correct only the named documentation/fixture owner after authorization. Keep accepted source guards, manual bundles and immutable failed/history receipts. If a native control reproduces a defect, repair only that concrete owner and rerun its affected positive/negative gates. No unverified old path deletion or new public effect is proposed.','',
                  'No new owner policy decision is required to satisfy the existing contract. Access to an actual authorized macOS host is required for the missing Apple cells of #19/#21/#22; a different shell/host cannot silently replace it. For #20 this is not a prerequisite. Public/runtime/script/document readback and publication must remain separately bounded.','',
                  'Primary Astra owns independent challenge/reconciliation and any later approved comment/closure. This reviewer recommendation establishes neither publication nor all-widget scientific completion. The supplied outer-frame amendment affects only geometry; N001/N002/N003 and historical native comparison failures are mapped individually, not used as blanket blockers.','',
                  f'<!-- RLGWO-AUDIT:{SHA}:{cid}:2026-10-08 -->','']
        (ROOT/f'{n}-comment.md').write_text('\n'.join(lines),encoding='utf-8')
        entries.append(dict(issue=n,canonicalId=cid,verdict='LEAVE OPEN',assessment=f'{n}-assessment.json',comment=f'{n}-comment.md',gaps=NEXT[n]['gaps'],mandatoryRows=len(M[n]),statusCounts={s:sum(r['status']==s for r in M[n]) for s in ('satisfied','validly superseded','unmet','unverified')}))
    summary=dict(schema='rlgwo.closure.worker-summary.v1',worker='E',capturedAtUtc=now,target=target,authority=authority,assignedIssues=[19,20,21,22,27,28],results=entries,
                 crossIssueDependencies={str(n):NEXT[n]['dependencies'] for n in M},
                 materialCounterexamples=[dict(issue=27,source='README.md:121-140',observed='Requiredrecipienttablemissing; blanketdoesnotrack/serverclaimretained; completedbuildernoteat192preserved.'),
                                          dict(issue=28,source='AGENTS.md:48,90-91,108; DESIGN.md:282,294,297,328,392,406-409; OPTICS.md:99,104,116,122,127,131,162',observed='Positivequery-onlyexamplesignoredbyfragmentparser; lunarhaloenumomission; all-effectforceoverclaim.'),
                                          dict(issue=20,source='README.md:61-76',observed='ExactWindowsnativefloorandWindowsreviewedFileinstructionsabsent; nativePSimplementation/consumerproof retained.'),
                                          dict(issues=[19,21,22],source='README.md:49-76',observed='Terminal/cache/bundle/offlineinstructionsrequiredbycontractsabsent; buildercommentL372pointstomissingofflineinstructions.')],
                 exactMissingChecksRequested=[dict(scope='#19/#21/#22 actual Apple/macOS',command='On authorizedactualmacOS: /bin/bash --version; native stat/mktemp/UID/filesystemreadback; adapted contained detector/PTY/staging/fullpreview/normal-positive original oracles.',purpose='Only actual native host settles mandatory floor/branch/filesystem obligations; no substituteadmitted.'),
                                              dict(scope='#21 isolatedforeignUIDparent',command='Contained nativeLinuxdistinctUID initializer control withreachable foreignUID non-writableHOME versus sameUIDpositive; no accountorhostpermissionchanges.',purpose='Separate owner-admission from existingpeerDAC49operations.'),
                                              dict(scope='#27/#28 exactsource/docsliterals',command='node tests/rlgwo-docs-contract.cjs <matchingrepo> --ref=18ff14860ff41c084b1db5f396bb62aa9c22b1be',purpose='Lightweight source/caller/negativecontrols and mandatorydoc failures; currentlyheldpendingprimaryresourcemessage. Do not interpret unrelatedchangedpolicyfixture failureastheseissues.'),
                                              dict(scope='#19 maliciousbuilder',command='Actualcurrentbuilder/hash sharedserializer adversarialliteral roundtrip with encodedshellvalue/localcoordinateomission/permission readback.',purpose='Finalconsumerproofaftercurrentbuilder/configrebind; sourceonlynotexecutedclaim.'),
                                              dict(scope='Publiccapability',command='Authorizedbyte-preserving rawmaininstall.sh/install.ps1/README/guidancedoc and generatedcommand readback; nativePSParseFiledownloadedbytes; renderedREADME/builder and #28completefragment/readout/reducedmotioncase by primarybrowserowner.',purpose='Primary139runtimehashreceiptcoversbuilderbutnotrawinstallers/rootMarkdownor rendereddisclosure/recipe proof.')],
                 publicationStatus='PROPOSED_ONLY_NOT_RECONCILED_NOT_POSTED',sourceOrExternalMutations='NONE',stoppedAt='Complete six-packet return. Await bounded primary follow-up; no new programme.')
    (ROOT/'summary.json').write_text(json.dumps(summary,indent=2,ensure_ascii=False)+'\n',encoding='utf-8')
    print(json.dumps({'worker':'E','issues':[r['issue'] for r in entries],'verdicts':[r['verdict'] for r in entries],'mandatoryRows':sum(r['mandatoryRows'] for r in entries),'outputRoot':str(ROOT)},ensure_ascii=False))

if __name__=='__main__': main()
