"""Improve reviewer prose only, preserving the matrices, source links and verdicts."""
import importlib.util
import pathlib

root = pathlib.Path(__file__).resolve().parent
spec = importlib.util.spec_from_file_location('review', root/'assemble_review.py')
review = importlib.util.module_from_spec(spec)
spec.loader.exec_module(review)

clear = {
21: [
 ('Create fresh private scratch and a separate retained HOME bundle only after platform, input and eligible-target checks; never admit the predictable old tree.', 'One verified 0700 root of each kind per attempt; scratch under the trusted temporary parent, retained files under HOME.', 'Current source calls the checked initializer after terminal and selection checks. Retained Linux controls demonstrate fresh roots across invocations, unsafe-parent refusal, and separate scratch/retained lifetimes.'),
 ('Verify parent and ancestor ownership, modes, symlinks and physical identity using the native stat/id/-O/-L contract; unusual mounts fail closed.', 'Private owned HOME, trusted temporary parent or root-owned sticky /tmp; physical path and device/inode identity must match.', 'Source checks every supplied component and root identity. Retained WSL2 native /tmp controls reject symlink and writable parents. The old wrong-owner HOME fixture combines ownership and writable-mode factors; the isolated ownership cell is recorded below.'),
 ('Qualify the actual macOS BSD stat/mktemp, Apple Bash 3.2 and filesystem staging branch.', 'Actual /bin/bash --version, BSD utilities and native filesystem execution of initialization, writes, extraction, cleanup and retention.', 'Retained applicability explicitly records Apple/macOS BLOCKED. Linux and a PLATFORM=mac helper mock do not establish this platform cell.'),
 ('Confine all outputs and cleanup to verified roots; reject symlink components, nonregular outputs, empty/dot/parent components and prefix lookalikes.', 'No outside sentinel changes for leaf/ancestor symlinks, traversal or prefix lookalikes; changed scratch identity is never deleted.', 'Retained native helper controls pass five confinement cases and changed-identity cleanup. Current guards verify the root, component boundary and physical output parent at the real write consumers.'),
 ('Separately discriminate wrong-UID retained-parent admission from writable-mode refusal.', 'A reachable, non-writable foreign-UID HOME fails the actual initializer before staging; a matching same-UID HOME succeeds.', 'The retained wrong-owner HOME control uses /tmp and combines wrong ownership with writable mode. Peer DAC tests establish isolation of created roots, not this separate initializer-admission discriminator.'),
 ('Preserve the exact hostile old preset symlink and victim while producing valid configured JSON in a fresh owned bundle.', 'Victim bytes and old symlink unchanged; successful regular JSON carries #lat=24.47&lon=39.61&method=4 in a private retained root.', 'Retained canary and configured-output assertions pass on source 9c3fd523. The source uses an exclusive owned partial, validates JSON, then publishes the final file; it never adopts the old tree.'),
 ('Keep the asset/preset write chain closed: owned fresh partial, validation before publication, exact configuration, no usable artifact on malformed input.', 'Valid new/cached assets work; invalid ZIP or preset fails with no artifact path; configured JSON remains exact.', 'Retained controls pass the cached/new asset, configured preset, malformed archive and failed-preset cases. Actual consumers recheck ownership around acquisition and publication. This is confinement and validation, not signature authentication.'),
 ('Preflight all archive members before extraction; reject absolute paths, traversal and links, then extract into a new empty child and return a valid in-root manifest directory.', 'Unsafe members cannot change an outside sentinel or extract an earlier marker; a valid nested Unicode/spaced manifest remains usable after exit.', 'Retained traversal, absolute, backslash, symlink, malformed, missing-manifest and safe-archive cases pass. The earlier-marker oracle detects extraction before preflight. Source additionally rejects special and duplicate members and creates files exclusively.'),
 ('Retain legitimate same-attempt cache reuse but create new private roots on each invocation and retire old shared-cache admission.', 'First/second same-attempt calls return the same validated path with one fetch; later runs use distinct roots.', 'Retained helper and predictable-root mutation controls establish both behaviors. The cross-UID owner run acquired only Chromium, Firefox and preset inputs, with no second Chromium acquisition.'),
 ('Retain completed or explicitly partial manual bundles through exit, failure and interrupt; cleanup removes only unchanged owned scratch.', 'Failed preset/extraction and TERM preserve the bundle; changed scratch identity preserves its sentinel; no retained EXIT deletion.', 'Retained helper/entry observations satisfy these controls. EXIT/INT/TERM handlers call scratch-only cleanup; TERM exits 143 and preserves the preset with a partial warning. Failed extraction returns no artifact and leaves its fresh partial child.'),
 ('Prove retained filesystem consumption after source exit and a fresh consumer; keep it distinct from printed paths, later liveness, reboot and browser installation.', 'A fresh owner process reads unchanged preset, manifest, payload, XPI and sentinel after owner exit.', 'The recorded owner exits 0, scratch is removed, and a fresh UID1000 consumer exits 0 with exact retained bytes, identities, modes and valid JSON/XPI. A later readback reports fixtureExists=false, cause unknown. Credit remains bounded to the original exit/consumer observation.'),
 ('Support the cross-user boundary with native Linux filesystem semantics, distinct UIDs and reachable positive controls; do not claim same-UID isolation.', 'Actual source-created 0700 roots, reachable parents, distinct peer with no groups/capabilities; read/write/link denial and healthy peer controls.', 'Retained WSL2 Linux kernel 6.6.87.2, Bash 5.2.21 and native /tmp ext2/ext3 evidence records UID1000/65534, 49 operations: 30 EACCES(13) and 19 allowed controls. Parents are reachable, sentinels unchanged and no foreign entries appear. This supersedes only the earlier failed login route.'),
 ('Keep dry-run outside both staging roots and all write, acquisition, extraction and cleanup paths; never return imaginary artifacts.', 'Zero effects and unchanged subjects; initializer and cleanup unreachable; guarded helpers return no usable path.', 'Retained Linux ten preview/refusal cases record zero effects and unchanged subjects, with separate helper guards. The actual Apple whole-entry cell remains unverified under #22.'),
 ('Use predictable-root, symlink-admission and retained-EXIT-deletion mutants to discriminate freshness, confinement and lifetime separately.', 'Each valid mutant fails its intended control while the original positive remains healthy.', 'Retained Bash mutations detect symlink admission and retained deletion. The separate predictable-root mutant completes its processes but returns the same scratch path across runs, detecting the freshness violation without counting a process error as proof.'),
 ('Disclose retained HOME bundle lifetime, keep-unpacked instructions, optional manual preset/XPI removal, partial retention and retired cross-run cache behavior in README.', 'Public instructions agree with the source and separate staging/Enter from manual browser success.', 'Script instructions are correct. Delivered README lacks the required bundle/cache lifetime paragraphs that were present in the earlier reviewed documentation unit.'),
 ('Preserve exact configuration, manual dashboard warning, card and permission contracts; apply only the supplied outer-wrapper amendment.', 'Retain the Bash witness scope and 325x530 card; honor the 330x534 outer-wrapper amendment without a new Windows security claim.', review.GEOMETRY+' Configuration and dashboard warnings remain in source; this Bash witness supplies no Windows staging-security guarantee.'),
 ('Complete exact-tree independent security reconciliation, mandatory platform/native controls and public script/instruction readback before closure.', 'All native ownership, confinement, cache, lifetime and dry-run obligations are bound to the final distributed source and usage.', 'E rebinds existing source/receipts; it does not rerun them. Actual Apple and isolated foreign-parent proof remain missing. The primary Pages hash receipt excludes install.sh and root README; publication and closure remain separate primary actions.'),
],
22: [
 ('Validate options and platform before effects; preview performs local discovery and exits before terminal, staging or installation, with legacy/no-target refusals and unresolved remote choices.', 'No confirmations or staging; eligible plans only, explicit non-success for no eligible target; ask/version/path stay unresolved.', 'Retained Linux ten offline cases and Windows ten dry/refusal cases per host record zero effects and unchanged subjects. Source returns before terminal acquisition and staging; ask remains unresolved.'),
 ('Offline preview makes no metadata, provider, download or network availability requests and does not adopt cached metadata as authority.', 'Zero network-boundary calls; release/cache helpers suppress before returning metadata or artifact paths.', 'Retained Windows guard suites pass 10/10 each, including preloaded metadata. Whole-entry cached/source cases show zero effects. Current guards precede cached metadata lookup; no preview network path was identified.'),
 ('Guard every alternate effect site, including staging, writes, copy, removal, extraction, clipboard, browser launch and cleanup; suppressed copy must be false.', 'No helper effects or sentinel changes; no successful Copied claim under preview.', 'Retained Bash helper and Windows 10/10 guard suites pass; clipboard returns false and cached sentinels remain unchanged. Current guards are before effects and cache returns.'),
 ('Return no usable artifact from preview helpers and prevent expansion, copy or store fallback from consuming proposed paths.', 'Preview prints its own plan; guarded download/preset/extraction/install/import never pass a pretend existing file.', 'Retained guards show null/false or empty artifact stdout with no effects. Current entry bypasses those artifact-returning helpers.'),
 ('Cover fresh and cached Chromium/Firefox, metadata/unpacked/preset sentinels, store/ask/fallback, already installed, missing preset, mixed/legacy/zero and malformed options.', 'All preview branches remain plans; cached sentinels unchanged; no store opening or installed confirmation.', 'Retained whole-entry matrices cover fresh/cached/store/ask/installed/mixed/legacy/none/missing-preset/bad-option. The entry return makes metadata-error fallback unreachable in preview; separate real Install helper guards cover ask/fallback suppression.'),
 ('Combine independent subject filesystem snapshots with effect/transport interception; separate harness logs and host startup writes from installer state.', 'Subject names/modes/contents unchanged and zero effect calls, including cached/unpacked/preset state; denied network transport.', 'Retained Linux and Windows observations record snapshotUnchanged=true and zero effects. Logs/readiness are outside the subject. CLR startup caches are separately recorded; this proves zero installer effects, not zero OS activity.'),
 ('Normal positive and NO_OPEN/NoOpen controls must still reach exact downloads, staging, configuration, clipboard and manual consumers.', 'Opening alone is suppressed under NoOpen; normal operations remain reachable with correct arguments.', 'Retained Linux normal/NO_OPEN counts are 28/24; Windows counts are 21/17 per host. Exact configured preset, assets, copy, metadata, extraction and manual manager/new-tab assertions pass.'),
 ('Detect eager initialization, cached early return, preview copy and EXIT cleanup mutants, using the relevant cached/positive controls and excluding bootstrap failures.', 'Each valid mutant fails its specific effect or changed-sentinel oracle; normal positives remain healthy.', 'Retained eight Bash and six Windows mutation controls are source-bound. Direct native eager/copy mutants reject sixteen dry cases across both hosts while all four normal/NoOpen positives pass; filesystem and clipboard-only effects are distinguished.'),
 ('Qualify complete whole-entry behavior on actual Apple Bash 3.2/macOS and modern Linux, plus exact-file native PS5.1/supported7 after launch prerequisites.', 'Actual claimed platforms execute preview/refusal/cache and normal-positive matrices; no emulated-host substitution.', 'Retained modern Linux 23 cases and native Windows 24 direct cases bind unchanged source. Actual Apple/macOS remains explicitly BLOCKED; GNU stat, disabled mapfile or PLATFORM=mac helper execution is not equivalent.'),
 ('Join the private staging/lifetime, normal terminal input and Windows encoding/selector interfaces without allowing preview initializer or cleanup effects.', 'One composed source preserves the sibling contracts; individual interfaces are assessed rather than administrative issue states.', 'Delivered installers and native fixtures match reviewed objects. Early return precedes normal terminal/staging and cleanup is guarded. Actual Mac prerequisite interfaces remain unqualified.'),
 ('Keep mode-specific completion honest: would/unresolved/preview-only, explicit refusal, dashboard replacement warning, and normal manual installation/import pending.', 'No swallowed error or empty eligible set becomes installed success; preview describes unresolved facts.', 'Current source prints the required would/unresolved, warning and pending messages. Retained controls assert those messages alongside post-state; no real browser installation is claimed.'),
 ('Keep both script usage and README/builder exposure consistent about offline, no effects, no artifacts, no prompts, unresolved choices, and NoOpen behavior.', 'Public README states DRY_RUN=1/-DryRun and the same precise policy as actual script headers.', 'Script headers accurately describe offline preview. Delivered README has no DRY_RUN/-DryRun/offline instructions in the installer section. Builder comment L372 refers to local/offline instructions that README does not supply.'),
 ('Preserve preset configuration, manual dashboard boundary, card and permissions; apply only the later outer-wrapper amendment.', 'Keep the original configuration/manual permission contract and 325x530 card under the 330x534 wrapper amendment.', review.GEOMETRY+' No UI or network policy change is proposed by this preview repair.'),
 ('Complete exact integrated effect reconciliation and public raw scripts/usage readback for both platforms before distribution/closure claims.', 'Every mandatory platform cell and the distributed Bash/Windows capability are tied to current source and usage.', 'E supplies narrow source/receipt review. Primary Pages hashes cover builder but exclude raw install.sh/install.ps1 and root README. Actual Apple and README gaps remain even after distributed-byte readback.'),
],
27: [
 ('Explain local persistence versus external computation in README and builder; list actual recipients/fields rather than blanket tracking or server-retention claims.', 'Complete README introduction/table and correct builder summary/details link; remove unsupported blanket wording.', 'Builder note L192 is corrected and authored/delivered blobs match. README still has the old GeoJS/ipinfo/geolocation-only explanation, no required table, and L126 retains the blanket no-tracking/server assertion; L7 also says no tracking.'),
 ('Disclose coarse-detection triggers, GeoJS then ipinfo fallback and connection IP; provider URLs contain no typed query or location fields and timezone resolution is local.', 'The README row matches exact final request construction and trigger/fallback behavior.', 'Source uses get.geojs.io/v1/ip/geo.json then ipinfo.io/json with local detectTz. README mentions providers and IP, but lacks the complete trigger/field row. Builder summary preserves the correct fallback.'),
 ('Disclose builder debounce/Enter and widget Settings search triggers, Nominatim q and conditional home-country countrycodes for digit-containing queries.', 'Specific request fields and feature triggers; avoid claiming every edit sends coordinates.', 'Source encodes q and conditionally adds countrycodes; builder uses a 1000 ms debounce and Enter. README omits this recipient/field/trigger description. No fresh caller execution was credited here.'),
 ('Disclose whitespace-stripped letter-digit-letter prefixes sent as uppercase /ca/FSA to Zippopotam in addition to Nominatim, without claiming complete-postcode validity.', 'M5V2T6 constructs /ca/M5V; London makes no Canadian request; malformed matching prefixes remain accurately characterized.', 'Implementation and builder summary agree with this trigger. README lacks the Canadian-prefix recipient/field row. These are construction claims, not recorded external transmission.'),
 ('Disclose eligible builder auto-name/method coordinate or GPS reverse lookup to BigDataCloud with latitude, longitude and localityLanguage=en; distinguish the widget precise path.', 'Exact fields and guards; both auto controls disabled means no reverse request.', 'Builder L334 constructs the request; L328-L331 guard edit ownership, automatic controls and coordinates. Builder note names reverse-coordinate transmission. README has no corresponding row.'),
 ('Disclose Aladhan location/method/school/date and active Open-Meteo coordinates/timezone/units/weather-field selections.', 'Final callsite fields appear in the privacy table with accurate feature/cache/network conditions.', 'Current URL construction has those fields. README mentions providers in other sections, but the required privacy rows and fields are absent. This is source construction proof, not a live provider trace.'),
 ('Disclose RainViewer manifest and returned tile-host/frame/tile paths whose x/y indices are derived from location.', 'Distinct manifest/tile recipients and location-derived indices, without new intensity or retention authority.', 'Source L1438 and L1444-L1448 construct exactly those requests. README lacks the row; no observation, millimetre or retention inference is added.'),
 ('Disclose Google Fonts stylesheet/font-resource hosts, subject to browser caching, and the absence of widget location/search parameters from those resource URLs.', 'Font-resource request row matches declarations and contains no invented location fields.', 'Actual external stylesheet/preconnect declarations are present. README privacy has no font row. Resource declarations are source proof, not a fresh network trace.'),
 ('Explain that Reset removes only saved configuration, preserves prayer/weather caches, and makes no claim to erase provider-held information or establish retention policy.', 'Explicit configuration/cache/provider boundary and no unsupported server-retention assertion.', 'clearLocal removes only KEY. README lacks this boundary and retains the blanket server statement.'),
 ('Retain optional user-triggered precise permission, embedding-host allow stripping, coarse/manual fallback, storage limits and the correct Request details anchor.', 'Permission/host/persistence guidance remains accurate without claiming an unverified sibling UI repair.', 'Builder and README retain those explanations. The anchor resolves to the privacy section, but that linked content is incomplete as mapped above. No new #17 UI qualification is asserted.'),
 ('Execute the exact current source controls for M5V2T6, reverse 51.5/-0.12, London, short queries and both automatic reverse controls off; record the complete final callsite ledger.', 'Positive and negative controls demonstrate actual request construction with intercepted fetch and no transmission.', 'Checked-in assertions and final callsites were read. No new Node execution was authorized during primary smoke. Older differing source/doc trees are not credited as final execution; exact applicable receipt reuse or fresh bounded execution remains required.'),
 ('Read rendered README/builder for legibility and agreement and public documents when claiming published disclosure; preserve runtime, controls, payloads and geometry.', 'Legible rendered text agrees with exact source and public version; no runtime, consent, provider or legal-policy change.', 'Primary HTTP hash receipt proves builder bytes, not README rendering or privacy-note readability. E used no browser. The confirmed missing text remains a gap independently of legibility.'),
 ('Preserve card/permission invariants and apply only the supplied outer-wrapper amendment; avoid unrelated geometry work.', '330x534 outer wrapper amendment, 325x530 card and existing permission scope.', review.GEOMETRY),
],
28: [
 ('Repair every positive query-only diagnostic recipe in AGENTS, DESIGN and OPTICS; retain labeled negative examples and the intentional builder cache-busting query.', 'Complete fragment URLs or & append notation activate actual hash parsing; query-only positives do not remain.', 'AGENTS L48/L90-L91/L108, DESIGN L282/L294/L297/L406-L409 and OPTICS L99/L104/L116/L122/L127/L131/L162 retain positive query-style examples. Authored q L667 and delivered q L2791 read only location.hash. This is a prose/source discriminator, not pixel proof.'),
 ('Advertise exactly halo, sundogs, pillar, anticrep, paraselene and lunarhalo; describe corona, earthshine, refraction and crepuscular rays as physical-input cases and remove blanket forceability.', 'The enum equals all six actual branches; a parsed corona string is not an implemented force branch.', 'Actual six branches match the contract and lunar forces preserve physical eligibility. DESIGN L328 omits lunarhalo; L392 says Each can be forced and L408 says force each. The explanation is incomplete.'),
 ('Include the required fragment/negative/six-name/physical-only explanation and complete copyable real-time motion, full-motion and noon halo recipes.', 'Complete index.html#lat=24.47&lon=39.61&label=Madinah&method=4 examples with &debugMotion=1, optional &motion=full and fragment simTime/halo.', 'Existing Running guidance already uses & append notation and real-time advice; preserve it. The required complete examples/explanation are missing while faulty positive query recipes remain.'),
 ('State the simTime/timeScale freeze and activation-versus-pixel boundary; use a physically eligible solar/lunar scene for claimed effects.', 'Real-time 15–60 s motion check; noon halo is neither lunar nor every-effect proof; a flag does not prove visible pixels.', 'AGENTS preserves the existing simTime freeze and motion evidence warnings. Required diagnostic activation/pixel text is missing and blanket force claims conflict with the real physical eligibility boundary.'),
 ('Validate every changed literal against actual final q/flag declarations and executed force branches, including motion=full, before-# and unsupported-corona controls.', 'Literal-by-literal final text readback, all six real branches, both negative controls; no manually corrected URL stands in for unchanged bad docs.', 'Checked-in fixture contains those parser/branch controls; manual final-source readback identifies remaining bad literals. No fresh Node execution occurred during smoke. Healthy handwritten URLs cannot close unchanged published prose.'),
 ('Read actual production q/debugMotion overlay from a complete real-time recipe and verify motion=full under reduced-motion in a disposable browser origin.', 'DEBUGMOTION true and overlay active; full override readback; normal accessibility reduction retained.', 'E has no browser lease and performed no browser readback. Primary smoke receipt was not available at assembly. Historical motion qualification does not correct or qualify the bad literal recipes.'),
 ('Retain the real 15–60 s watch/clip/delta/crop, no-cloud-hash, sequential browser-owner and physical-condition requirements for any visual claim.', 'No syntax/flag count becomes visual PASS; corner sun, opaque Moon, dawn and accessibility gates stay intact.', 'Current guidance retains those requirements. E asserts no new visual PASS; this row credits preservation of the invariants only.'),
 ('Keep AGENTS within the documentation owner scope; runtime remains verification-only and intentional builder ?r reload semantics stay unchanged.', 'Existing diagnostic prose/enum repair only; no query parser, new force framework or renderer rewrite.', 'Actual runtime remains fragment-only and builder cache busting is intentional. The bounded proposal changes only required documentation; no source mutation was performed.'),
 ('Require exact corrected text, literal/enum proof, an evidence comment and rendered/public documentation readback before closure.', 'Correct final documents and actual browser/readback receipts are independently reconciled before posting.', 'Primary runtime hashes cover runtime/V1 assets, not rendered AGENTS/DESIGN/OPTICS. Required text correction is absent; no publication or closure proof is claimed.'),
 ('Preserve card/readability/permissions and only the supplied outer-wrapper amendment; documentation repair does not own geometry.', '330x534 wrapper amendment with 325x530 card and unchanged permissions.', review.GEOMETRY),
],
}

for n, rows in clear.items():
    assert len(rows) == len(review.M[n])
    for entry, (obligation, expected, observed) in zip(review.M[n], rows):
        entry.update(obligation=obligation, expected=expected, observed=observed)

replacements = {
 'WindowsPowerShell5.1':'Windows PowerShell 5.1', 'PowerShell5.1':'PowerShell 5.1', 'pwsh7':'pwsh 7',
 'Bash3.2':'Bash 3.2', 'Bash5.2.21':'Bash 5.2.21', 'Rawinstall.ps1':'Raw install.ps1',
 'generatedcommand':'generated command', 'publicusage':'public usage', 'primary139-file':'primary 139-file',
 'sourceASCII':'source ASCII', 'native5.1/7':'native 5.1/7', 'Native5.1.26100.9444/7.6.6':'Native 5.1.26100.9444/7.6.6',
 'ParseFile0':'ParseFile 0', 'UTF8control0':'UTF8 control 0', 'UTF8control':'UTF8 control', 'SHA256d4d0cd3e':'SHA256 d4d0cd3e',
 'Final18-case':'Final 18-case', 'exactURL':'exact URL', 'genericXPI':'generic XPI', 'FirefoxZIP':'Firefox ZIP',
 'firefoxXPI':'firefox XPI', 'firefoxZIP':'firefox ZIP', 'objectidentity':'object identity', 'explicitUTF8':'explicit UTF8',
 'fileErrors0':'fileErrors 0', 'fileErrors4':'fileErrors 4', 'source33b1d359':'source 33b1d359', 'sourcec6af27d9':'source c6af27d9',
 'nonASCII':'non-ASCII', 'parses0':'parses 0', 'exactsource':'exact source', 'sourcehash':'source hash',
 'auditedPS.24cases':'audited PS. 24 cases', '12perhost':'12 per host', 'Normal21':'Normal 21', 'NoOpen17':'NoOpen 17',
 'and0effects':'and 0 effects', 'readinessfalse':'readiness false', 'deliveredREADME':'delivered README',
 '#requires5.1':'#requires -Version 5.1', 'Owner330x534':'Owner 330x534', 'with325x530':'with 325x530',
 '#22Windows':'#22 Windows', 'nativefloorqualified':'native floor qualified', 'sameownedroot':'same owned root',
 'NoOpenremoves':'NoOpen removes', 'nativehosts':'native hosts', 'sourcechoice':'source choice', 'sameUID':'same UID',
 'foreignUID':'foreign UID', 'UID1000':'UID 1000', 'UID65534':'UID 65534', 'zeroeffects':'zero effects',
 'no controllingterminal':'no controlling terminal', 'no usablepath':'no usable path', 'effectspies':'effect spies',
 'same-attemp':'same-attemp', 'modernLinux':'modern Linux', 'nativeApple':'native Apple', 'actualApple':'actual Apple',
 'nativeMac':'native Mac', 'actualmacOS':'actual macOS', 'completeplatform':'complete platform',
 'sharedroot':'shared root', 'offlinepreview':'offline preview', 'minimumBash':'minimum Bash',
 'disabledbuiltins':'disabled builtins', 'effectiveconfig':'effective config',
}
for n in (19,20):
    for entry in review.M[n]:
        for field in ('obligation','expected','observed','evidence_basis'):
            for old,new in replacements.items(): entry[field]=entry[field].replace(old,new)

next_text = {
19: ('README installer usage and uncovered native detector/PTY controls; preserve qualified installer source unless a concrete native failure is reproduced.',
 ['Use an authorized actual macOS host. Record /bin/bash --version, native stat/mktemp, UID and filesystem identity; exercise the real detector and pipe/PTY entry with controlled effects.',
  'Complete uncovered both-family zero/one/multiple/backslash and empty-array cases, then qualify the exact current malicious-label builder/hash roundtrip. Preserve existing negative and mutation expectations.',
  'Add README terminal/EOF, review-first, same-attempt versus retired cross-run cache and newline-profile limitation instructions. Retain correct builder hash placement and manual warnings.',
  'Bind final source, fixtures, docs and authorized raw-script/generated-command readback for independent primary reconciliation.'],
 'All mandatory host, detector, terminal, path, configuration and documentation cells demonstrate original expectations; negative mutants fail and current public capability matches qualified source.',
 ['#21 private-root/lifetime interface; #22 normal versus preview boundary; actual builder/config serializer and command consumers. No whole-issue closure predecessor is required.']),
20: ('README Windows installer instructions and current raw-script/generated-command acquisition; preserve qualified ASCII selector/entry source and native fixtures.',
 ['State Windows PowerShell 5.1 and supported pwsh 7 explicitly and provide a quoted reviewed/downloaded -File route. Preserve irm|iex, encoded hash grammar and manual dashboard boundary.',
  'Acquire authorized raw install.ps1 bytes without resaving, bind them to the full d4d0cd3e source hash and parse the downloaded exact file on actual 5.1/7 when distribution is claimed. Confirm the current generated command.',
  'Reuse retained 18-case native suites and 24-case direct entry through exact source/fixture identity; rerun only affected controls if inputs changed. Include necessary receipt core in public evidence and obtain primary reconciliation.'],
 'README states the actual floor, Windows file route and manual boundary; distributed bytes match qualified source or receive fresh affected native gates; every #20 obligation is satisfied. Sibling Apple gaps are not #20 requirements.',
 ['#22 Windows guards use the same qualified source. No hard whole-issue Apple/Bash dependency applies.']),
21: ('Missing native platform/isolated ownership proof and README bundle/cache lifetime prose; preserve current private staging, validation, Linux DAC and scratch-only cleanup.',
 ['On authorized disposable macOS filesystem parents, exercise actual Apple Bash 3.2/BSD stat/mktemp initialization, writes, archive refusal, cleanup, errors, interrupt and fresh retained-file consumption.',
  'Use native Linux distinct fixture UIDs to test a reachable, non-writable foreign-UID HOME against a same-UID positive. Keep the established 49-operation peer DAC cell separate.',
  'Add README home-bundle lifetime, keep-unpacked while installed, optional manual preset/XPI removal, partial retention and retired shared-cache instructions; preserve correct source instructions.',
  'Bind exact source and authorized distribution with independent security reconciliation. Preserve time-bounded exit/fresh-consumer evidence and disclose the later absent fixture without inferring cause.'],
 'All mandatory native ownership, confinement, archive, cache, retention, preview and mutation controls meet the original expectations with outside sentinels unchanged; public instructions and raw source match.',
 ['#19 stdout/same-attempt cache consumer; #22 initializer/cleanup preview boundary. Shared installer/README changes use one writer.']),
22: ('README offline preview usage and missing actual macOS contained whole-entry matrix; preserve established Linux/Windows source and entry receipts.',
 ['Describe the same offline policy in README and exposed usage surfaces: local discovery only; no filesystem/network/clipboard/process/cleanup; no usable artifacts or confirmations; remote version/path/ask choice unresolved. Explain that NoOpen suppresses opening only.',
  'After actual Mac launch/staging prerequisites pass, run the complete Apple Bash 3.2 fresh/cached/store/ask/installed/mixed/missing-preset/legacy/none/options matrix with subject snapshots, denied transport, effect spies, normal/NO_OPEN positives and valid targeted mutants.',
  'Reuse Windows direct -File and modern Linux receipts through exact source/fixture equivalence. Do not weaken expectations or restart unrelated sky qualification.',
  'Bind both public raw scripts and usage identities, then independently reconcile exact integrated effects before primary decides closure.'],
 'All claimed platforms show zero installer effects and unchanged subjects in preview while exact normal/NoOpen consumers work; helpers return no usable artifacts, mutations fail, and public usage agrees with distributed bytes.',
 ['#19 actual Bash launch/terminal; #20 Windows minimum-host/selector; #21 private roots and retained/scratch lifetimes. Assess interfaces, not administrative closed states.']),
27: ('README privacy/data-flow prose and bounded source-trigger/rendered readback controls; preserve the corrected authored/delivered builder note at L192.',
 ['Replace the incomplete README privacy explanation with the original compact introduction and final callsite table for GeoJS/ipinfo, Nominatim q/countrycodes, Zippopotam prefix, BigDataCloud coordinates, Aladhan date/location/method/school, Open-Meteo zone/units/fields, RainViewer manifest/tile indices and Google Fonts resources.',
  'State Reset configuration-only/cache/provider boundaries and no retention conclusion. Retain permission, host, storage, coarse/manual guidance and the details anchor; remove unsupported blanket wording.',
  'Exercise exact current source functions with intercepted fetch: M5V2T6 exact URLs, reverse 51.5/-0.12, London without Canadian requests/bias, short query no request and both reverse auto controls disabled. Record each final callsite and field set.',
  'Read rendered README/builder and the authorized public version, then reconcile the evidence/comment with primary.'],
 'Complete prose agrees with the per-row source ledger, all positive/negative trigger controls pass, and rendered/public readback is legible and current; no runtime/provider/consent/retention/permission policy changes.',
 ['#17 persistence-failure explanation and actual UI interface; shared geocodeSearch/coarseDetect/clearLocal and builder lookup/reverse callers.']),
28: ('Existing AGENTS, DESIGN and OPTICS diagnostic prose/recipes; runtime source remains verification-only.',
 ['Fix every affected positive query-style diagnostic literal to the same fragment or a complete index.html#... URL. Keep the negative query example labeled and the intentional builder ?r cache-busting query intact.',
  'State all six force branches including lunarhalo, and physical-input limits for corona, earthshine, refraction and crepuscular rays. Remove blanket forceability, retain the clock-freeze warning and add the activation-versus-pixel boundary.',
  'Check every final changed literal through actual q/flag declarations and force branches, including motion=full, before-# negative and unsupported-corona mutation. Do not test only manually corrected examples.',
  'One browser owner reads actual complete real-time fragment/debug overlay and full override under reduced-motion. Any visual claim additionally needs real watch/delta/crop. Read rendered/public corrected docs before primary reconciliation.'],
 'No ignored positive query recipes remain, the enum matches all six actual branches, physical limits are accurate, all literal/negative controls discriminate, and browser/readout/public text evidence is captured without changing runtime behavior.',
 ['Documentation integrator owns AGENTS/DESIGN/OPTICS; authored/generated index q/flags/branches are verification owners; browser checks are sequential under one owner.']),
}
gaps = {
19: ['Actual Apple /bin/bash 3.2/macOS detector and pipe/PTY entry proof is missing.', 'The complete profile cardinality/backslash matrix and retained newline-path limitation are not fully demonstrated/disclosed.', 'README lacks required terminal and same-attempt versus retired cross-run cache instructions.', 'Current adversarial builder/config roundtrip and public raw-script/usage readback remain unverified.'],
20: ['README omits explicit Windows PowerShell 5.1/pwsh and the Windows reviewed download/-File route required by the capability contract.', 'Primary runtime hash receipt does not contain current raw install.ps1 or root README/usage readback.'],
21: ['Actual macOS/Apple Bash 3.2 BSD-stat/mktemp/filesystem controls are missing.', 'An isolated non-writable foreign-UID retained-parent initializer control is missing.', 'README lacks retained bundle and cache lifetime instructions.', 'Distributed Bash script and public usage readback remain unverified.'],
22: ['Actual Apple Bash 3.2/macOS whole-entry matrix and native launch/staging prerequisites are missing.', 'README lacks the offline no-effect/no-artifact/no-prompt policy and NoOpen distinction.', 'Current raw scripts and public usage readback remain unverified.'],
27: ['README lacks the required recipient/field table and Reset/cache/provider boundary, while unsupported blanket wording remains.', 'Current trigger-control execution and rendered/public README/builder agreement remain unverified here.'],
28: ['AGENTS/DESIGN/OPTICS retain ignored positive query-only diagnostic recipes.', 'DESIGN omits lunarhalo from its enum and overclaims forceability of every effect.', 'Complete corrected literals, controls and actual browser/readout/public text evidence remain outstanding.'],
}
for n,(scope,steps,acceptance,dependencies) in next_text.items():
    review.NEXT[n] = dict(gaps=gaps[n],scope=scope,steps=steps,acceptance=acceptance,dependencies=dependencies)

review.main()
