'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const src=path.join(__dirname,'../src');
function rig({inline=false}={}){
 let clock=0,id=0;const jobs=new Map(),workers=[],nodes=new Map(),events=new Map();let published=0,fallbacks=0;
 const state={utcMs:1000,generation:0,sceneIdentity:'A',fraction:.5,waxing:false,up:1,dpr:1,timeScale:0,paused:false};
 for(let i=0;i<2;i++)nodes.set('moon-embedded-'+i,{textContent:'AAAA',remove(){nodes.delete('moon-embedded-'+i)}});
 const detail={available:false,adopt(s){for(const a of [s.linear,s.calendarLinear,s.coverage])for(const v of a)if(!Number.isFinite(v))throw Error('nonfinite worker result');this.available=true},clear(){this.available=false},dispose(){}};
 class Worker{constructor(){this.sent=[];this.terminated=false;workers.push(this)}postMessage(m){if(this.terminated)throw Error('worker closed');this.sent.push(m)}terminate(){this.terminated=true}emit(m){this.onmessage?.({data:m})}}
 class U extends URL{};U.createObjectURL=()=> 'blob:mock/'+(++id);U.revokeObjectURL=()=>{};
 const w={__SALAH_MOON_OFFLINE__:true,__SALAH_MOON_EMBEDDED__:true,SalahMoonHost:{capture:()=>({...state}),publish:()=>published++,fallback:()=>fallbacks++},SalahRealSky:{compose(){}}};
 const doc={currentScript:{src:inline?'':'https://test/moon/moon-host.js'},baseURI:inline?'about:blank':'https://test/',hidden:false,getElementById:k=>nodes.get(k),createElement:()=>({width:0,height:0,style:{},getContext:()=>({putImageData(){}}),remove(){}}),head:{append(){}},addEventListener:(n,f)=>events.set(n,f),removeEventListener:n=>events.delete(n)};
 const c=vm.createContext({window:w,document:doc,URL:U,Blob,Worker,performance:{now:()=>clock},structuredClone,Uint8ClampedArray,Float32Array,ImageData:class{constructor(d,w,h){this.data=d;this.width=w;this.height=h}},startMoonDetail:()=>detail,blendCalendarBytes:a=>a,setTimeout:(f,ms)=>{const n=++id;jobs.set(n,{f,ms});return n},clearTimeout:n=>jobs.delete(n),setInterval:()=>++id,clearInterval:()=>{},MOON_DEFAULT_PROFILE:{profile_id:'calendar-neutral-v5-01',mode:'calendar'},MOON_WORKER_SOURCE:'',MOON_OFFLINE_CHUNKS:[{name:'dem',index:0,last:true},{name:'colour',index:0,last:true}]});
 vm.runInContext(fs.readFileSync(path.join(src,'moon-precision.mjs'),'utf8')+'\n'+fs.readFileSync(path.join(src,'moon-native.mjs'),'utf8'),c);
 const flush=()=>{for(let guard=0;guard<20;guard++){const j=[...jobs].find(([,v])=>v.ms===0);if(!j)break;jobs.delete(j[0]);j[1].f()}};
 const request=()=>workers.at(-1).sent.findLast(m=>m.kind==='render');
 const response=(kind='result')=>{const r=request(),n=r.scene.size,out=r.scene.outSize;return {kind,id:r.id,identity:r.identity,scene:structuredClone(r.scene),width:out,height:out,rgba:new Uint8ClampedArray(out*out*4),calendarRgba:new Uint8ClampedArray(out*out*4),surfaceSize:n,surfaceExtent:r.scene.extent,surfaceLinear:new Float32Array(n*n*3),calendarLinear:new Float32Array(n*n*3),surfaceCoverage:new Float32Array(n*n),physicalIdentity:'physical',profileIdentity:'profile',diagnostics:{kernel:'metric-radial-terrain-wasm-mb1',quality:{status:'PASS'}}}};
 return {w,workers,state,detail,nodes,events,jobs,flush,request,response,get published(){return published},get fallbacks(){return fallbacks},advance:t=>clock+=t};
}
test('embedded source survives boot-error and a retry replays every chunk',()=>{const r=rig();r.flush();assert.equal(r.workers[0].sent.filter(m=>m.kind==='asset-chunk').length,2);r.workers[0].emit({kind:'boot-error',error:'controlled'});assert.equal(r.w.SalahMoonRuntime.retry(),true);r.flush();assert.equal(r.workers[1].sent.filter(m=>m.kind==='asset-chunk').length,2);assert.equal(r.nodes.size,2);});
test('malformed numeric surface withdraws safely without publishing',()=>{const r=rig();r.flush();r.workers[0].emit({kind:'ready'});const m=r.response();m.surfaceLinear[0]=NaN;assert.doesNotThrow(()=>r.workers[0].emit(m));assert.equal(r.published,0);assert.equal(r.w.SalahMoonRuntime.state.legacyFallback,true);assert.equal(r.w.SalahMoonRuntime.state.status,'unavailable');assert.equal(r.workers[0].terminated,true);});
test('complete result becomes current, preview remains pending',()=>{const r=rig();r.workers[0].emit({kind:'ready'});r.workers[0].emit(r.response('preview'));assert.equal(r.w.SalahMoonRuntime.state.status,'refining');assert.equal(r.w.SalahMoonRuntime.state.pending,true);assert.ok(r.w.SalahMoonRuntime.surface());r.workers[0].emit(r.response());assert.equal(r.w.SalahMoonRuntime.state.status,'ready');assert.equal(r.w.SalahMoonRuntime.state.pending,false);r.w.SalahMoonRuntime.dispose();});
test('A B A generations cannot publish the original request',()=>{const r=rig();r.workers[0].emit({kind:'ready'});const stale=r.response();r.state.generation=1;r.state.sceneIdentity='B';r.w.SalahMoonRuntime.request();r.state.generation=2;r.state.sceneIdentity='A';r.w.SalahMoonRuntime.request();r.workers[0].emit(stale);assert.equal(r.published,0);assert.equal(r.w.SalahMoonRuntime.state.rejected,1);});
test('profile change rejects predecessor even at identical phase',()=>{const r=rig();r.workers[0].emit({kind:'ready'});const stale=r.response();r.w.SalahMoonRuntime.setProfile('reference');r.workers[0].emit(stale);assert.equal(r.published,0);assert.equal(r.request().scene.profile.lift,0);});
test('DPR change rejects predecessor',()=>{const r=rig();r.workers[0].emit({kind:'ready'});const m=r.response();r.state.dpr=3;r.w.SalahMoonRuntime.request();r.workers[0].emit(m);assert.equal(r.published,0);});
test('native invalid input withdraws accepted surface',()=>{const r=rig();r.workers[0].emit({kind:'ready'});r.workers[0].emit(r.response());r.state.utcMs=NaN;assert.equal(r.w.SalahMoonRuntime.request(),false);assert.equal(r.w.SalahMoonRuntime.surface(),null);});
test('native time seek invalidates same-geometry work',()=>{const r=rig();r.workers[0].emit({kind:'ready'});const m=r.response();r.state.utcMs-=10000;r.w.SalahMoonRuntime.request();r.workers[0].emit(m);assert.equal(r.published,0);});
test('hide return does not retain a predecessor',()=>{const r=rig();r.workers[0].emit({kind:'ready'});const m=r.response();r.state.paused=true;r.w.SalahMoonRuntime.request();r.state.paused=false;r.w.SalahMoonRuntime.request();r.workers[0].emit(m);assert.equal(r.published,0);});
test('dead-worker cleanup is nonthrowing and bounded retries',()=>{const r=rig();r.workers[0].terminated=true;assert.doesNotThrow(()=>r.workers[0].onerror({message:'crash'}));for(let i=0;i<3;i++){assert.equal(r.w.SalahMoonRuntime.retry(),true);r.workers.at(-1).emit({kind:'boot-error',error:'again'});}assert.equal(r.w.SalahMoonRuntime.retry(),false);});
test('dispose revokes publication and further retry',()=>{const r=rig();r.workers[0].emit({kind:'ready'});const m=r.response();r.w.SalahMoonRuntime.dispose();r.workers[0].emit(m);assert.equal(r.published,0);assert.equal(r.w.SalahMoonRuntime.retry(),false);assert.equal(r.events.size,0);});

test('fully embedded document needs no relative resource base',()=>{const r=rig({inline:true});r.flush();assert.equal(r.workers[0].sent.filter(m=>m.kind==='asset-chunk').length,2);});
test('wrong surface extent is rejected before publication',()=>{const r=rig();r.workers[0].emit({kind:'ready'});const m=r.response();m.surfaceExtent=NaN;r.workers[0].emit(m);assert.equal(r.published,0);assert.equal(r.w.SalahMoonRuntime.state.status,'unavailable');});
test('wrong output footprint is rejected before publication',()=>{const r=rig();r.workers[0].emit({kind:'ready'});const m=r.response();m.width=m.height=8;m.rgba=new Uint8ClampedArray(256);m.calendarRgba=new Uint8ClampedArray(256);r.workers[0].emit(m);assert.equal(r.published,0);assert.equal(r.w.SalahMoonRuntime.state.status,'unavailable');});
test('startup deadline triggers fallback, not a main-thread solver',()=>{const r=rig();const d=[...r.jobs.values()].find(v=>v.ms===120000);assert.ok(d);d.f();assert.equal(r.w.SalahMoonRuntime.state.status,'unavailable');assert.equal(r.published,0);assert.equal(r.workers[0].terminated,true);});
test('refinement deadline withdraws preview safely',()=>{const r=rig();r.workers[0].emit({kind:'ready'});r.workers[0].emit(r.response('preview'));[...r.jobs.values()].find(v=>v.ms===240000).f();assert.equal(r.w.SalahMoonRuntime.surface(),null);assert.equal(r.w.SalahMoonRuntime.state.status,'unavailable');});
